### ISSUE TITLE
Allow grouping of chats in mail client

### ISSUE THREAD

**Issue by svenpilz** [deltachat/deltachat-core#10]
One of my friends recently started using you messenger, he uses the Android client and  seems to really like it. On the other side, I just use my mail client and quickly got lost in all those small mails. Would it be possible to tag them, so mail clients can use a threaded view? 
The easiest way may be one mail subject per chat, like a named chat room. Or linking mails via message ids.

**Comment by r10s** [comment]
All Delta-Chat-Mails start with the subject `Chat:` or `Chat: Groupname:` - isn't this sufficient for automatic  tagging?

**Comment by rizzopablo** [comment]
Conversations could be like gmail conversations. If the chat message would be only the body of the email, then we could open a new conversation with a contact by letting the system choose a default subject, or writing a custom subject. Then email clients would group the chat/mail conversations accordingly, and one could have many conversations with the same contact, with different subjects. If you do not what to write a custom subject, the subject could be as simple as "Chat 20170108 My Name - Contact Name".

**Comment by go2null** [comment]
Adding to the comments above - a quick fix until Subject can specified would be to _exclude_ the message from the Subject line.
For example, `Chat with PersonName` or `Chat with GroupName`.

**Comment by r10s** [comment]
As we use the References: header in newer versions, this should be far better now.

**Comment by go2null** [comment]
Please re-open this ticket; The `References` header apparently is not sufficient to segregate conversation streams.

Also, it does not provide a direct way to name those conversation streams.

**Comment by r10s** [comment]
Well, but this also depends on the MUA of the other side, or not? A set References-header works well at least with Thunderbird and mutt. 
But as always, any PR is welcome :)

**Comment by Ar2000jp** [comment]
It does work in threaded view in Thunderbird, and it's probably true it depends on the other side's MUA, but still we gain a lot by being able to specify a Subject. OTOH, I'm not sure what is the advantage of giving each unencrypted message a new Subject.

I already use E-Mails to chat sometimes, and the Subject is usually like a name for the chat or a status message of some sort. Testing Delta Chat with a friend and with another device of mine for a day has already made my inbox a mess. I'd say people would start avoiding or even blocking me if I chat with them like this. :grin: 

This is probably for another issue, but the read receipts also mess up my mailbox. Maybe they should all refer to the same first message? Or maybe the read receipt of the first message?

PS: Really great app. I love the idea of being able to use the undying E-Mail system efficiently and in a modern way. But still there's the hurdle of actually fitting in with the system.

**Comment by r10s** [comment]
I don't like the idea to put threading information to the subject just because some MUA rely on that.

However, i am sure, the collaboration with other MUA can be improved, eg. by using the In-Reply-To carefully (currently it is not set because MUAs may have problems with potentially deeply nested threads)

Regarding the read receipts: Well, I also do not have a good solution for this, maybe they should just be hidden by the other MUAs, which of course, would require changes there.

Please feel free to create new more concrete issues for these (or other) points.
