### ISSUE TITLE
start test suite for a few "happy paths", integration with travis

### ISSUE THREAD

**Issue by hpk42** [deltachat/deltachat-core#100]
From a discussion with @r10s today: before going for g-play it'd be good to have automated tests which run with each commit/push to the delta-core codebase.  @flub has done some work on creating python bindings for delta-core and i have experience in writing tests (have eg authored http://pytest.org). So this issue here is about writing a few basic tests (create chat, send a message, receive a message) and integrating it into travis such that the tests run on PRs and pushed commits.

**Comment by t-oster** [comment]
nice idea. Any FakeSMTP/IMAP libraries which can run during the test and assert incoming/outgoing messages?

**Comment by flub** [comment]
The python stdlib has a stmpd implementation which can probably be used.  imap might be some more work.

**Comment by t-oster** [comment]
well there is http://www.icegreen.com/greenmail/ but this need java

**Comment by ralphtheninja** [comment]
I'm going to try and push this further. Enough discussing :wink:

https://github.com/deltachat/deltachat-core/pull/250 is a start to get Travis up and running.

**Comment by ralphtheninja** [comment]
I've tested `deltachat-node` with `Greenmail` but I can't get it to work. A client can connect to IMAP and SMTP (and IMAPS and SMTPS works as well), but sending messages back and forth doesn't work.

**Comment by r10s** [comment]
cc @hpk42

**Comment by ralphtheninja** [comment]
Also see https://github.com/deltachat/deltachat-node/pull/98

**Comment by flub** [comment]
Starting the greenmail docker container was what I was thinking of doing for the tests as well, so it makes sense to use this in the node bindings tests too.

**Comment by hpk42** [comment]
python bindings have a test suite https://github.com/deltachat/deltachat-core/tree/master/python/tests
and the tests run against travis.   creating a follow up issues  #339  and closing this one here.
