### ISSUE TITLE
Why is no padlock shown beside messages signed by Thunderbird/Enigmail

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-core#110]
seen on mails from me (Thunderbird) to @Ampli-fier (Delta), however, might be another problem as my Thunderbird/Enigmail/GnuPG setup is a little weird; maybe i just used a bad key for signing.

**Comment by r10s** [comment]
checked this issue, it was just my weird setup, i signed the mail with an old key ... that's exactly the reason why we need autocrypt. @Ampli-fier i've send you another message from Thunderbird/Enigmail, this should be encrypted and signed correctly and the padlock should be shown in Delta Chat then.

**Comment by Ampli-fier** [comment]
Yes, I acknowledge(d) that the padlock is shown correctly.

**Comment by r10s** [comment]
perfect, thanks for checking this :)
