### ISSUE TITLE
Constructor delta_handler complications in Node bindings

### ISSUE THREAD

**Issue by karissa** [deltachat/deltachat-core#111]
Hey, I'm currently [writing node bindings](
https://github.com/karissa/deltachat-node) for deltachat-core, just in case anyone wants to make an electron app for it :)

So far it's going well, but I find that the constructor for receiving mailbox events doesn't follow node's async rules. Events propagate from the deltachat-core library up to v8, and it isn't clear if it's possible to send any response  back down to the deltachat-core library.

I'm talking about this handler that is passed to the constructor:
```c
uintptr_t my_delta_handler(mrmailbox_t* mailbox, int event, uintptr_t data1, uintptr_t data2)
{
    return 0; // for unhandled events, it is always safe to return 0
}

mrmailbox_t* mailbox = mrmailbox_new(my_delta_handler, NULL, NULL);
```

This means that when using Node, the delta_handler will *always* return 0, because v8 won't be able to propagate messages back down to the caller. Does this get in the way of any critical workflows for deltachat? 

What might be some other workarounds here? Can there be a function to call on the mailbox that sends the event response?

I also find that converting the `data1` and `data2` objects to their respective types for all events is quite tedious. Is there a cheat sheet somewhere for the return types for all events?

**Comment by r10s** [comment]
Hi  karissa,

thank you for pushing this forward. I am not sure if I understand your questions correctly, but I will try :)

> This means that when using Node, the delta_handler will always return 0, because v8 won't be able to propagate messages back down to the caller. Does this get in the way of any critical workflows for deltachat?

For the "pure notifications" sent from the core to the handler, returning 0 is just fine. Among these pure notifications are MR_EVENT_ERROR, MR_EVENT_MSGS_CHANGED, MR_EVENT_INCOMING_MSG, MR_EVENT_MSG_DELIVERED, MR_EVENT_MSG_READ, MR_EVENT_CHAT_MODIFIED, MR_EVENT_CONTACTS_CHANGED and so on, see [mrevent.h](https://deltachat.github.io/deltachat-core/html/mrevent_8h.html), all events marked with `return 0` - for these events it is just fine if they are propagated async from the handler further to the UI or wherever.

Moreover, there are some other "functional" events that are more a sort of function calls - the core wants to know sth. from the system using it. These "functional" events require a return value and among them are functions to check if the system is currently online or to get a translated string, in mrevent.h they are marked by requiring a return value. Maybe it is possible to handle them differently in the wrapper? So call the async handler only for "pure notification" events?
However, for the first start, you can also just return 0 for the functional events, the core will assume the function is not implemented and use a default then.

> I also find that converting the data1 and data2 objects to their respective types for all events is quite tedious. Is there a cheat sheet somewhere for the return types for all events?

Well, this is a C thingie, not nice, indeed. However, maybe it is possible to convert them in sth. more usable in my_delta_handler()? You could eg. check the type of the event there and convert it to the correct var. For the Java-Port I've created some helper functions to convert the ugly pointer to a Java-String.
But, also here, I think this is not required for the very first start.

**Comment by r10s** [comment]
iirc this is soved in https://github.com/deltachat/deltachat-node by handling the few events that expect a return value separately from the c-side.
