### ISSUE TITLE
support apps to subscribe to general (non-chat) push notifications?  (Email-note spec?)

### ISSUE THREAD

**Issue by testbird** [deltachat/deltachat-core#113]
This issue is to let interested devs find out about the idea of building an IMAP based push notification alternative, to be used instead of proprietary third-party push message services:

https://gitlab.com/foss-push/planning

It looks as if deltachat-core has most of the needed features implemented, except a spec that allows the separation of notification messages from chats.
So it looks as an ideal basis to implement a mobile push client service (daemon).

**Comment by testbird** [comment]
A further thought:
Once there actually is one push message client (daemon) available per device. May it then make sense to also let deltachat-android subscribe to chat messages through this daemon, instead of shipping and runninig its own deltachat-core?

**Comment by r10s** [comment]
I do not think deltachat-core gets superflous, it's only the IMAP-IDLE call that would be replaced by sth. else to wake up on new messages. However, it's not 100% clear to me how this "sth. else" should work.

**Comment by testbird** [comment]
I see, it depends on if it would make sense for the push client daemon (the sth. else) to fetch and store messages in a db, or just "ping" appropriate apps with change notifications when detecting a new notification message.

I don't know what the referenced android inter-process communication is capable to support. https://stackoverflow.com/questions/5740324/what-are-the-ipc-mechanisms-available-in-the-android-os But hopefully message passing is possible.

An advantage of having the daemon run the whole deltachat-core (including chat message database) may be that it could allow other protocol chat apps to (also) communicate over Email-chat using the deamon (in addition to getting change notifications for any other protocols).

**Comment by testbird** [comment]
Well, and not all chat apps that want to support Email-chat would have to ship its own deltachat-core, if there were some local server/daomon access available.

**Comment by testbird** [comment]
A stand-alone daeomon with deltachat-core (providing messages through IPC or local loopback network?) could hide its permanent notification, while allowing the frontends to display one upon new messages.

**Comment by testbird** [comment]
Maybe it's these "content-providers" to let deltachat-core provide other apps access to the database?
https://developer.android.com/guide/topics/providers/content-providers.html

**Comment by testbird** [comment]
This even sounds as if notification of DB observes is possible: https://stackoverflow.com/questions/15610527/notifychange-with-changed-uri-from-contentprovider-update

**Comment by testbird** [comment]
Hm, thinking about design consequences..., there might then be a set of three abstraction package levels:

**deltacore-lib** (the current deltachat-core, with added support to handle not just chat messages, but both Email-chat and Email-notify folders separately)
**deltacore-android** (uses deltacore-lib to create android content-providers for notifications and chat messages, effectively also consolidating itself into the "foss push client service for android". Other platforms may have their own packages to provide apps with data access.)
**deltachat-android** (depends on deltacore-android and provides the chat frontend)

Other android apps can depend on deltacore-android to get notifications and/or the Email-chat messages.

**Comment by DJCrashdummy** [comment]
well, it gets pretty confusing now with several streams on different platforms and different naming...

but if i got this discussion right, i simply want to record, that the _Push Client_ should only process the signaling and no messages (payload) which are only relevant to the different _App Clients_.

in the case of DeltaChat it may imply that there will be 3 levels, since the _App Client_ is split into 2 levels ("backend/frontend") which is completely up to the respective app (_App Client_) developers.

---
for the _emphasized vocabulary_ please have a look at https://gitlab.com/foss-push/planning#vocabulary. i tried to use it to stay in one line and not further confusion.

**Comment by testbird** [comment]
Thanks for your note, I now tried to adjust the bolded parts above to follow the vocabulary.

Email based messages don't require a "payload" like in the body, and the envisioned Email-notify spec won't need to require nor forbid either.

The point here was that deltachat currently consists of two packages, deltachat-core and the frontend UI.
But it could be possible to split the current deltachat-core functionality into a deltacore-lib package (imap support coded in C) and a new package that resembles the push client functionality (if apps desire, passing "payload" to app-client frontends as well). And this newly split-off package could be the basis for implementing a more generic free push client (for android and others).

**Comment by DJCrashdummy** [comment]
ok... now i've got the point: you are talking about the concrete possibility of implementing this in one way (with the DeltaChat-base), and i am talking about a general foss-push eco-system.
for sure separating the software which handles the IMAP-push system and IMAP-messages is a kind of unnecessary if you think about this one use-case... but as you somehow already wrote: hopefully someday we have a generic foss-push system supporting different push methods which can be extended.

**Comment by testbird** [comment]
> hopefully someday we have a generic foss-push system supporting different push methods which can be extended

Right, separating some "deltacore- or pushcore-android" push client package could be done in a way that allows extending it to support additional on-the-wire protocol methods.

**Comment by r10s** [comment]
closing this for now here, of course, the discussion can go on in the new support forum at https://support.delta.chat
