### ISSUE TITLE
Non-INBOX-folders may be synchronized faster

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-core#12]
Currently, by design, only messages arriving in the INBOX are shown instantly. Messages in other folders are synchronized only about every 30 minutes. 

While this is **sufficient for the core functionality,** a chat with another person or group, this is not perfect for other situations:

- MultiClient, when using Delta Chat on different devices, messages send from one device does not appear instantly on the others
- Messages send from other E-Mail do not appear instantly in Delta Chat

Again, this does not affect the core functionality.

However, for the moment, I have no idea which IMAP commands to use for this functionality.

**Comment by rizzopablo** [comment]
I don't get the issue. Why would you care about msg in other folders? Every new message should arrive to the inbox... isn't it?

**Comment by EMK2000** [comment]
No. For example, in Gmail you can set a filter, which can make a new incoming email go to certain folder directly and skipping the inbox.

**Comment by rizzopablo** [comment]
Ah ok. I think there is a standard feature in imap protocol which is 'suscription' to folders, may be all subscribed folders make a push notification to client. I really don't know if it works this way. Else Delta could poll each subscribed folder every 30 or 60 secs.

**Comment by andreygursky** [comment]
> Currently, by design, only messages arriving in the INBOX are shown instantly.

Is INBOX being monitored with IMAP IDLE?

> Messages in other folders are synchronized only about every 30 minutes.

To have the IDLE functionality not only for INBOX but also for other mail boxes there are at least 2 ways avoiding polling: open many connections to the server (for each mail box) and issue IDLE on each. Or a better way: use [IMAP NOTIFY](https://tools.ietf.org/html/rfc5465).

**Comment by r10s** [comment]
IMAP NOTIFY sounds very promising, however, I've not any server supporting in my testing repository (which, of course, is not complete ;-)

Where is this feature used "in the wild"?

**Comment by Ampli-fier** [comment]
May I ask about the "synchronization" details?

It looks to me as if DC only detects new messages in mail folder, but it does not detect that messages got deleted or moved, right?
At the moment this leads to the situation that the message "state" is unsynchnronized when somebody uses DC and other MUAs at the same time.

**Comment by r10s** [comment]
Delta Chat searches for new messages in the other folders about every half hour, moving, etc. is handled this way. 
Delta Chat does not delete messages in its own chats that are deleted with other MUAs.

**Comment by r10s** [comment]
I think, until IMAP NOTIFY is more widely supported, this is out of scope. 
The alternative, keeping several connections open would require possibly more battery which is the opposite we want to aim in general.
However, if we go more toward https://github.com/deltachat/deltachat-android/issues/269 , this may also improve the sync of non INBOX-folders.

**Comment by testbird** [comment]
Keep IMAP-push, or -notify in the future, by default.

Reducing the scanning interval for deltachat/deltachat-core#12 will only increase the battery and data usage.
Custom folder ignore list allows to limit battery and data usage.
