### ISSUE TITLE
[consolidated] (auto-)archive / delete message history (support continuous daily usage)

### ISSUE THREAD

**Issue by testbird** [deltachat/deltachat-core#120]
To avoid overgrowing amounts of old messages using all device "disk"-space, there should be an option to limit the retained history.

(The underlying functions will also be usefull when checking and hard-limiting storage usage on server and device, to support continuous usage.)

----

ToDo things:

Chat message selection
* [ ] **implement pinned/sticky/starred messages** (edit according to comments)
Allows to exempt messages from getting deleted by the following (automatic) bulk archiving and deleting.

Archiving and deletion management
* [ ] **implement managing and archiving of chats**
To keep chatting simple, manageable and search-able, only distinguish between active chats and  archived chats (no weekly, monthly etc. separate sub-archives).

  * [ ] core function to "delete all (non-sticky) older messages up to this one"
  * [ ] core function to "archive all (non-sticky) older messages up to this one"
  * [ ] UI option to "delete/archive old (non-sticky) messages up to this one" in *active* chats
  * [ ] UI option to "delete old (non-sticky) messages up to this one" in *archived* chats
  * [ ] UI button in chats to jump to first message (like existing button to jump to last message)
  * [ ] UI feature to auto-archive older messages from chats (default those exceeding a 100 messages count?)
  * [ ] UI feature to auto-archive stale chats (default to "no message since 6 weeks"?). If this gets to be the default, disabling this option for a chat could be called pinning / sticking / staring the chat to the active chat list.
  * [ ] the chat archive should get configuration options to
    * delete archived chats from server (and thus from other clients in a multi-client setup)
    * (?) move chats into a separate database (possibly encrypted if placed on external, removable storage that may have to be connected before access is possible, but would still allow to open and search the archive, and respond, if needed)
<br>

Storage Restrictions
* [ ] **Enable database compression (vacuum)**
     Actually free storage space when messages get deleted.
* [ ] **auto checks & deletes based on storage space limits (device & server)**
When the local filesystem, or the server space, is full, no more chat or email messages can be received.
  * [ ]  On incoming messages, let DC check the available space on the server and on the device, and when the free space falls below say 6% or 110MB, notify the user that DC will soon (below  5% or 100MB) have to start automatically deleting the oldest chat messages on the server or on the device.
  * [ ]  UI to manually set the storage usage limits (percentage and absolute) for automatic deletion of old archived and current messages.

Non-chat emails ("contact requests")

* Emails deleted/moved from INBOX on server, need also be removed from "contact requests" #195

---

**Implementing the above solves at least the following issues:**
* Option to limit history download deltachat/deltachat-android/issues/21
* Limit retained history deltachat/deltachat-android/issues/22
* Contact requests are never emptied https://github.com/deltachat/deltachat-android/issues/132
* Introduce a limit for number of messages in a chat deltachat/deltachat-android/issues/244
* Request: POP protocol implementation deltachat/deltachat-android#227

**Comment by csb0730** [comment]
Here my last comment from ...android's issue 22

My proposal for a *handy* function:
1) IMPORTANT: make messages stickable or pinable first (I don't know the best wording ;-)  ).
That means that a message can be marked manually and then it is not touched by an automatic garbage collection. This enables the user to keep important messages!
I think for that function database has to be extended?
2) introduce an option to set max number of messages in a chat's setting (and show somewhere current number of messages in a chat).
3) trigger the garbage collection whether manually or automatic
(with new message in a chat or once per day or even with a button?)

Comments welcome ;-)

**Comment by r10s** [comment]
for 1. do you mean sth. like "starring" messages in Whatsapp?
In fact, the core of Delta Chat already has this functionality :) see: https://deltachat.github.io/api/classmrmailbox__t.html#a8ed1c3bd08cd6515abf6046ebad9cafc

**Comment by webratte** [comment]
@testbird if you write "delete all older messages up to this one" you mean also delete from server?
I think this is important to save online storage. Some providers have strictly limited storage.

**Comment by webratte** [comment]
Ok. now as I read your first post it seams my post is unnecessary.

**Comment by csb0730** [comment]
Hi @r10s, yes,
 as far as I found this is similar to that. Because I don't have whatsapp I thougt about a pin needle icon to indicate that a certain message is fixed. Therefore I used the wording "pinnable".

**Comment by testbird** [comment]
Just added database vacuum, as it is a prerequisite.

**Comment by testbird** [comment]
(from #164)

Concerning **multi-client**, I generally think old chat messages can be assumed to have been downloaded, and if several clients try to delete some old messages from the server, even different ones (until a threshhold is reached) there should not be a problem. After they are deleted, all clients will sync to the same state again (server state taking precedenc

Concerning the **concurreny to classic emails**, autodeleting chat messages allows classic email to consume chat storage space. Classic email may fill the mailbox, and block all incoming messages.

But it makes sense for Email-chat to operate in a cautious mode that by default avoids blocking classic email comunication:

Because of the more transient nature of chat messages, and that chat clients aremore likely to listen to IMAP-push (part of the spec), and download/archive before deleting, I think an autodeletion threshold for old chat messages by default is ok. (Deltachat deleting classic email would not be ok. That needs to be handled by a resposible user or MUA.)

**Comment by r10s** [comment]
> core function to "archive all (non-sticky) older messages up to this one"

> UI option to "delete/archive old (non-sticky) messages up to this one" in active chats

> UI feature to auto-archive older messages from chats (default those exceeding a 100 messages count?)

this won't work this way as "archiving" is an action [taking place on chats](https://deltachat.github.io/api/classdc__context__t.html#a27915f31f37aa5887e77dcc134334431), not on messages.

**Comment by testbird** [comment]
Hm, is see, the current archiving is just an "inactived" property or flag on chats. That means auto-deleting would lead to incomplete "chat archives", that can only hold the last messages and never more than the limit.

I'm trying to avoid such unpleasant surprises by looking at the whole picture before looking on single problems (like auto-deleting messages).

I assumed "archived" was already a property of messages, because that allows consistent actions based on that distinction.

* auto limit active chat (view), without risking to delete too much
* messages first only expiring into the archive, possibly long history if storage space permitts
* delete actions on archived messages (manual and auto-limits, auto-local-storage-restrictions)

Sure archiving won't help with deleting (cutting down own storage space), but both might be designed to allow them to work nicely together.

**Comment by r10s** [comment]
> That means auto-deleting would lead to incomplete "chat archives", that can only hold the last messages and never more than the limit.

sure, when the space on the device is limited, sooner or later this will lead to incomplete chats. this, however, has nothing to do with "archived chats" that are only a flag that remove them from the main chat list (as in whatsapp, signal etc.)

> by looking at the whole picture before looking on single problems (like auto-deleting messages).

this is always useful :) however, in practice, with limited resources and limited skills, we have to work with "what we have" what we can realistically achieve :)

i think the intent of this issue is described in #244 so we can close this one.

**Comment by testbird** [comment]
Björn, I suspect you already know that wrong paths can easy get one lost in a mess, especially concerning basic things. "What we have" includes evaluations, analysis, and proposals made. Limited resources means of course limited pace, that is absolutely ok, but I truly think a too a high pace in dismissing and closeing issuess, isn't really solving anything, rather the contray.
If you need, take a time off, to get back in a state that allows detecting and considerating crucial things.

The intent of this issue isn't just #244 (fixed: history <-> local deletes), but working on a concept for all the related things to form a consistent solution, that may be implemented in small steps (finally reordering checkmarks above, you have write access).

Concerning a practical implementation sequence, it may not be necessary to enhance the "archived chats" implementation at first, but why not stay on top of things by developing or having a collaborative concept.

**Comment by testbird** [comment]
Moved these points to the top, does the beginning of the concept above match you intention, now?:
  * core function to "delete all (non-sticky) older messages up to this one" in a selection
  * UI option to "delete old (non-sticky) messages up to this one" in *active* chats
  * UI feature to auto-delete older messages from chats (default those exceeding a 100 messages count?)

**Comment by r10s** [comment]
i won't got for an auto-archive, i would see #244 independent of archived or not. in fact, the "archived" state typically used on messengers is a very unstable state - one message coming in and it has a different state. i do not think the user should worry about this.
generally, for now, i see just very few options, and they are covered by #244

**Comment by testbird** [comment]
The local-only deletes of #244 won't help with server space limitations, and neither work for multi-client nor for a consistent, user understandable view of "incoming email" in the server's INBOX.

Auto-archive isn't a must at all, it could be left out in the list above. Local archives would just be a useful split to limit the server space, that even works with multiple chatclients.

Mind you though, that it makes no sense for me evaluating, checking and optimizing different options for a project, if the results are just thrown away.

**Comment by testbird** [comment]
Fhere are reasons behind the concept, that might not be obvious on the first view. Therfore please post your doubts or ask, before closing prematurely.

(For example, deleting "archived messages" from the server can work for multi-clients on a "if still exists" basis, since they should all be in the local database already.)

**Comment by r10s** [comment]
well, the discussion can be continued anyway :) or, even better, for a high-level discussion with the wider community, being continued in the new forum.

**Comment by testbird** [comment]
That would not follow any due diligence. I updated the first post, separating the auto-delete feature, anyway, before I forget about this.

**Comment by testbird** [comment]
Hint: Instead of fighting against an overwhelming amount of issues, you may make this one, that was consolidated from many issues, your own, and covers a lot of other issues. The plan may still be adjusted over time, if more aspects come in.

**Comment by r10s** [comment]
i personally prefer to have smaller issues.

**Comment by testbird** [comment]
Well, the individual issues to work on in a meta-issue like this one are as small as the checkmarks above.

See how github says "1 out of 19 are done"?: https://github.com/deltachat/deltachat-core/issues?utf8=%E2%9C%93&q=is%3Aissue+consolidated+is%3Aclosed+

**Comment by r10s** [comment]
i know the display "x of y" and i also use these lists sometiems.

but the 19 points here are more 19 points, to _discuss_. eg.  it's not clear if an option as _UI option to "archive old (non-sticky) messages up to this one" in active chats_ will ever exist. same for other points in this "todo"-list.
this can be done, but, however, this is not an open issue in the meaning "there is sth. to do on the code".

**Comment by testbird** [comment]
And, any better idea for a single option that allows bulk managing the chat history length? This is the best plan currently.

**Comment by r10s** [comment]
#244 i'm not saying this is a better idea, however, this is sth. that will probably happen.

**Comment by testbird** [comment]
#244 does not mention a UI for bulk deletion, same as the first 5 points here, even if an implementation may already keep that in mind.

Even if you choose to throw my work away, and not to reopen the consolidated overview: Please properly limit #244 to chat messages that need also be deleted on the server by default, and have the incoming emails (former "contact requests") be reduced by classic MUAs that clean up the INBOX. (Then one would only miss the "delete all old messages up to this one" to clean up the incoming emails from withing deltachat in the rare case of deltachat using a separate account, but individual email deletion is possible).

**Comment by r10s** [comment]
yes, #244 is very basic, of course.

and: closing issues does not throw work away, eg. it is linked from other, open issues :)

**Comment by r10s** [comment]
> Please properly limit #244 to chat messages that need also be deleted on the server by default

see comment at https://github.com/deltachat/deltachat-core/issues/244#issuecomment-416221265

**Comment by testbird** [comment]
It's that closing consolidated issues and implementing and closing "limited basic issues" that have been reviewed as not solving all the known problems, disregards the work gone into devising and documenting these things.

And it further guarantees that users will create new issues, without having a relevant *open* issue available to point to, that provides some status (checkmarks) and overview and plan to work with.

**Comment by r10s** [comment]
closing an issue does not disregards the work gone into it imo. 
it stays available, searchable, visible, and is linked from other issues.
also it can be reopened, as needed.
it's not deleted or so.

**Comment by r10s** [comment]
> make "archived" a property of messages instead of chats (so messages can be moved into archives).
>
>  let the "archive chat" UI option add the property to the contained messages. Further incoming messages then simply open in an empty chat view again.

the "archive" function then would be different from the archive function that we have today and different form the one people know from other messenger. not sure if this makes sense.

**Comment by testbird** [comment]
Because old, "archived" messages would stay archived, and not just temporarily disabled or hidden, i.e. not popping up again completely with new messages arriving, I think it does something understandable that makes sense. No problem. It's perfect if the active chat length is configurable per chat, and if it is easy to extend the view to (load) the archived messages (could be default for searching/filtering). The active and archived chat lenght are intuitive ways to control the storage usage on the devices and server (smallest active chat length is kept on server).

**Comment by testbird** [comment]
I've had an idea that might be a very slim way to implement auto-archive and -delete, even not requiring any frontend support to ensure continuous daily usage, but allowing.

Couldn't the existing message property that holds the "stared" value be extended to also hold an "archived" value?

The -core may then just
* add the "archived" state to any non-stared message surpassing the most recent say 100, by default
* check free storage space (local / server) and if required delete messages, selecting from the oldest "archived" messages.

Maybe this could work regardless whether the frontends already implement UI support for any selection of the features, or not (stared/archived messages, configuring auto-archive/delete). Even the legacy way of suspending and resuming "archived chats" from the chat list could stay as is, until improved.

**Comment by testbird** [comment]
also updated the above to use "synced-new" and "synced-history" now
