### ISSUE TITLE
[consolidated] allow to track down sender evaluation errors (origins)

### ISSUE THREAD

**Issue by testbird** [deltachat/deltachat-core#124]
There seem to be inconsitencies in the known sender privileges, and it is not possible to track these down to the messages that triggered granting the privilege. Examples are, contact lists containing strange addresses, and inconsistent message categorization errors that are neither traceable nor revertible.

One idea was to replace the MR_ORIGIN_ decimals of contacts with a set of property fields corresponding to the granted privilege/status, that if granted/true contain references to the triggering message.

**If this is implemented it should help to track down issues like these:**
*  Make messages appear in chat if contact is known https://github.com/deltachat/deltachat-android/issues/225
* (Also mentions inconsistencies:) No alert for new message in Contact Requests https://github.com/deltachat/deltachat-android/issues/228
* (Also mentions inconsistencies:) IMAP folder ignore list: additional entries & custom string https://github.com/deltachat/deltachat-android/issues/239

**And to implement:**
* graceful handling of false negative spam https://github.com/deltachat/deltachat-android/issues/240

**Comment by r10s** [comment]
closing this for now here, of course, the discussion can go on in the new support forum at https://support.delta.chat
