### ISSUE TITLE
Group member list

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-core#129]
This issue is about how the _Group member list_ is handled currently and if it can be improved.

**Current state**

- the group members are selected on group creation and propagated in the `From:` and `To:` headers. The member list of incoming messages is read from the `From:`, `To:` and `Cc:` headers.  
We expect normal MUAs to use the "Reply-All" function to reply to a group.
- adding and removing members require the special headers [`Chat-Group-Member-Added:` and `Chat-Group-Member-Removed:`](https://delta.chat/en/spec#add-and-remove-members), only when these headers are present, the member list is recreated. To force this recreation immediately, Delta Chat sends out a message after every member added/deleted, the content is sth. like "A added member B to group G".  
If normal MUAs always reply to the last message, they will always reply to the correct group member list.
- I a normal MUAs replies to an old message with a smaller mailing list, this mail is nevertheless shown in the corresponding Chat. Assuming, the Group member list shows the current state and does not guarantee all legacy messages are sent to the full member list, this seems to be okay.  For detecting accidental Reply-Clicks there is a [special handling](https://github.com/deltachat/deltachat-core/blob/master/src/mrmailbox_receive_imf.c#L780).

**Ideas**

- sending out the special mails seems to be a good idea to keep the user list in sync between the group members. However, maybe we should allow normal MUAs also to _add_ a member; as a result the `Chat-Group-Member-Added:` would be superfluous. 
- Removing members would be harder, as the removed member won't be informed and still thinks, he is in the group. Moreover, for a group of only 3 members, we cannot distinguish between a removed member and an accidental click on "Reply" instead of "Reply-All". 
- On the other hand - maybe a user of a normal MUA is not aware that adding a user to a message will add the user to all future group messages as well. 

So, maybe the current state is just fine, but I would like to discuss this.

**Comment by testbird** [comment]
I think if with p2p recipient lists someone removes a person, the reply-all button of MUAs will not send a notification to the removed address, so it is probably ok not to require the `Chat-Group-Member-Added/Removed` Header.
However, it may still be usefull to inform the receipients of a enlarged/reduced receipient list about the changes and possibly confirm/reject to leave out/add the recipient for the answer.

**Comment by testbird** [comment]
> for a group of only 3 members, we cannot distinguish between a removed member and an accidental click on "Reply" instead of "Reply-All".

Does it matter? In both cases its a two person communication. Shouldn't it be just fine to sort the messages into the persons chat instead of into the group chat.

**Comment by r10s** [comment]
> Does it matter? In both cases it's a two person communication. Shouldn't it be just fine to sort the messages into the persons chat instead of into the group chat.

In fact, currently this is desired by the ["special handling"](https://github.com/deltachat/deltachat-core/blob/master/src/mrmailbox_receive_imf.c#L780) - by setting chat_id to 0, the caller will create a persons chat (however, the code needs some review, smells like possible off-by-one-errors ;)

**Comment by r10s** [comment]
closing this, no actionable item.

in general, in between we try to sort messages into the correct groups and avoid group splits.
