### ISSUE TITLE
Send–receive address pairing (aka. per-chat subaddressing)

### ISSUE THREAD

**Issue by JRHaigh** [deltachat/deltachat-core#13]
I use [subaddressing](https://en.wikipedia.org/wiki/Email_address#Subaddressing) to reliably separate correspondence with different contacts or groups of contacts. This involves giving a unique email address, for receiving, to each person or group that I correspond with.
&nbsp;&nbsp;&nbsp;&nbsp;This given address, let's call it the ‘receive address’, goes in the From field of sent messages and the To field of received messages. A ‘send address’ of a contact is the email address that they give you, which goes in the To field of sent messages and the From field of received messages. The send address and receive address form a pair.
&nbsp;&nbsp;&nbsp;&nbsp;I need Delta Chat to define chats in terms of send–receive address pairs, i.e. to be able to allow me to specify receive addresses on a per-chat basis, in order for it to be viable for me, because otherwise I'd lose the separation advantages gained from the subaddressing scheme unless I change the receive address in the Delta Chat outgoing account settings (i.e. the From address) each time I send chat messages in a different chat, which is really not practical! It seems that Delta Chat doesn't even have a way to configure separate account profiles, so it seems that the only way, currently, to use more than 1 receive address in Delta Chat is to keep changing its settings.
&nbsp;&nbsp;&nbsp;&nbsp;So, **please define chats in terms of send–receive address pairs**, accompanying the existing send address with the missing receive address, and add an account setting to enable requirement that all new chats prompt for the receive address.

**Comment by aHVzY2g** [comment]
+1
@JRHaigh Do you use mailcow?

**Comment by r10s** [comment]
Well, for me, the highest priority of Delta Chat is to create an messenger "for the masses", eg. an alternative to WhatsApp for my grandfather ... I think, these people do not care about subaddressing - especially, as Delta Chat only displays explicitly selected chats.

So, for the moment, subaddressing as a low priority for me. I'm not even sure, if this follows any standard (Do you have any information about this? Which other e-mail-programms support "subaddressing"?)

However - Delta Chat is Open Source - I would be glad for a pull request supporting subaddressing.

NB: Are incoming messages using subaddressing shown up correctly in Delta Chat?

**Comment by JRHaigh** [comment]
@aHVzY2g: Not directly / not that I'm aware of. Why; what's the relevance?

**Comment by JRHaigh** [comment]
> Well, for me, the highest priority of Delta Chat is to create an messenger "for the masses", eg. an alternative to WhatsApp for my grandfather ... I think, these people do not care about subaddressing - especially, as Delta Chat only displays explicitly selected chats.

&nbsp;&nbsp;&nbsp;&nbsp;Why should the masses flock to a complex email–chat bootstrapping project if not subaddressing? The masses are plagued with spam. Subaddressing promises an end to the spambot vs. heuristic spam filter arms race, making them both irrelevant for communication with trusted correspondents. Furthermore, using public keys as extensions could really lead to some practicality breakthroughs in the security of the masses.

> I'm not even sure, if this follows any standard (Do you have any information about this? Which other e-mail-programms support "subaddressing"?)

&nbsp;&nbsp;&nbsp;&nbsp;Email. As far as this issue is concerned, a subaddress is simply any valid email address. I've retitled and heavily-edited this issue report to try to clarify and focus more on what it means for implementing in Delta Chat (i.e. chats are defined on send–receive address pairs) rather than specifics of subaddressing.

> NB: Are incoming messages using subaddressing shown up correctly in Delta Chat?

&nbsp;&nbsp;&nbsp;&nbsp;They weren't being shown at all. Nothing sends, nothing gets received.

**Comment by JRHaigh** [comment]
@r10s:
Hopefully I've clarified the issue description better, now, wrt. to exactly how it relates to the chats, so I might as well say some more about subaddressing in a (non-top) comment.
&nbsp;&nbsp;&nbsp;&nbsp;Subaddressing, as far as this issue is concerned, is any means to receive emails on multiple distinct email addresses. Among other uses, this can be used to identify the source of incoming emails without relying on the spoofable From header, and thus can be used to **[_dispose_](https://en.wikipedia.org/wiki/Disposable_email_address) of entire sources of spam!**
&nbsp;&nbsp;&nbsp;&nbsp;Other than being a valid, standard email address, the specifics of subaddressing are entirely up to the server. People can do what they like with how their server interprets the email address. However, by convention, a ‘+’ symbol in the `local-part` is interpreted as a separator of username and extension. Furthermore, people can do what they like with how their server or client interprets the extension, which is often used to filter the mail into separate mailboxes – or ‘_chats_’.
&nbsp;&nbsp;&nbsp;&nbsp;Some interesting subaddressing schemes include:
* ‘username+extension@example.org’ (most common);
* ‘extension@username.example.org’;
* ‘username@extension.example.org’;
* ‘USERNAME@example.org’ where the capitalisation of the username is an extension _code_ (In this case the code is 8-bit, so can represent 256 unique codes. Note: The part of an email address before the ‘@’ symbol is supposed to be case-sensitive; its case is preserved by standards-compliant systems. However, many email service providers ignore case, and this allows for this subaddressing scheme.);
* ‘username@EXAMPLE.ORG’ where the capitalisation of the domain name is an extension code (In this case, 10-bit. Note: Unlike all the previous, this one works for _any_ email address, because domain names are case-insensitive by definition. However, it requires that your correspondents don't attempt to normalise the case. Normalisation can be easily detected by never issuing the expected ‘normal form’ to anyone, i.e., by always having at least 1 character in the domain name be uppercase.);
* ‘u.s.e.r.n.a.m.e@example.org’ where the presence of each dot in the username is a bit in an extension code (Note: The size of the extension code in bits is the size of the username in characters minus 1 – in this case, 7-bit. Unlikely to be normalised, but as before, normalisation can easily be detected by always having at least 1 dot in the username.);
* any combination of the above and more (e.g.: ‘U.sE.rN.aM.e+Extension@GmAiL.cOm’ = ‘uS.eR.nA.mE@GoOgLeMaIl.CoM’ = ‘U.S.Ername+Extension@Gmail.com’, etc. – the number of unique codes for an 8-character username on Gmail is 2<sup>8 + 7 + 8</sup> + 2<sup>8 + 7 + 13</sup> = 2<sup>28</sup> + 2<sup>23</sup> = 268435456 + 8388608 = 276824064, i.e., there's log<sub>2</sub>(276824064)b = 28.04b of extension coding even if the arbitrarily-long extension string isn't used).

&nbsp;&nbsp;&nbsp;&nbsp;If you've never tried subaddressing before then it's worth experimenting to see whether any of these schemes work with your existing email address. Not only will it allow you to test Delta Chat's support of send–receive address pairing, but you may actually find it useful yourself.
&nbsp;&nbsp;&nbsp;&nbsp;Subaddressing has allowed me to identify that the majority of my spam is received on subaddresses that I've submitted on domain name registrations, which are public in the WHOIS database. I use a different subaddress for the domains than for the registrar, so I can be sure that any email that claims to be from the registrar about general matters, such as billing, sent to specific domain subaddresses (usually duplicated to all the domain subaddresses) is phishing.
&nbsp;&nbsp;&nbsp;&nbsp;The exact source of the spam is always known – in this case, it came from spammers who got my contact details from the WHOIS database. This really locks-down their ability to deceive – if I receive, on the subaddresses that I only use for the WHOIS database, mail claiming to be from WhatsApp then it's _obviously_ phishing, not least because I don't have a WhatsApp account! 😆
&nbsp;&nbsp;&nbsp;&nbsp;Most spam is pretty obvious to me because I don't use most of the proprietary, corporate crap that scammers target, but I can see how it can be unobvious for many people, which is why I think that subaddressing should be made easy for those people too.

**Comment by r10s** [comment]
Hi thank you very much for your clarification. As soon I'll find some time, I will dive into this issue...

**Comment by QuibblingAsh42** [comment]
The name I think I've heard it most as is "alias".  Those are limited relative to sub-addressing, but fit most people's needs.

BTW, I have my domains with Namecheap.com, and they offer a service called "WhoIsGuard".  I think it's like $2/year/domain, but when you're queried in WhoIs, it'll return their contact infomation instead of yours.  Mail sent to the address listed are just relayed to you so you don't have to reveal your actual address.  I use it because my physical address isn't listed anywhere. 

Q

**Comment by r10s** [comment]
Unless there is another one who would like to volunteer of this issue, this is out of scope of Delta Chat for now. Of course, we can re-open this issue, for now, it is closed (maybe someone should collect such ideas somewhere else - maybe the Wiki?)
