### ISSUE TITLE
command line client.

### ISSUE THREAD

**Issue by mogorman** [deltachat/deltachat-core#130]
Can someone post a how to on getting the command line client connected to an imap/smtp server? I got it running on my distro but wasn't sure where to go from there in developing my own client.

**Comment by mogorman** [comment]
ya, i dont intend to use this as a real client but i wanted to see the c code go through sending and receiving messages so i could apply it to the client i am writing. thank you

**Comment by Ampli-fier** [comment]
I found it helpful reading these [comments](https://github.com/deltachat/deltachat-core/blob/00e12b1a4459040c30ccea2f866ca24d1206244c/src/mrmailbox.c#L362) in the source code.

**Comment by mogorman** [comment]
thank you for that too @Ampli-fier
