### ISSUE TITLE
Use "In-Reply-To" header

### ISSUE THREAD

**Issue by annando** [deltachat/deltachat-core#131]
Delta Chat is able to communicate with non Delta Chat users as well. This could be improved, when Delta Chat would send a ```In-Reply-To``` header with the message id of the previous message or the starting message.

There could be an additional rule to automatically start a new thread when the last post had been done X days ago.

**Comment by testbird** [comment]
> There could be an additional rule to automatically start a new thread when the last post had been done X days ago.

Or when the chat had been moved to the archive and a new one starts (which could happen with an auto-archive for orphaned chats https://github.com/deltachat/deltachat-core/issues/120).

---
related:
https://github.com/deltachat/deltachat-core/issues/72

**Comment by annando** [comment]
@testbird thanks for pointing to #72 - I hadn't found it.

**Comment by r10s** [comment]
i think you mean the `In-Reply-To:`-header? The `Reply-To:` header is similar to `From:` and is used to define the email-address where replies should go to, see https://tools.ietf.org/html/rfc5322 for more information.

**Comment by annando** [comment]
You are right, sorry,

**Comment by r10s** [comment]
these two are sometimes also confusing to me :)

**Comment by annando** [comment]
Great, I just wanted to change the subject as well :-)

**Comment by csb0730** [comment]
_In-Reply-To_ header has been dismissed because of problems with standard MUA's. See some (closed) issues.
IMHO I'm not convinced if that was the best solution, but it was one!
Maybe this should be configurable by user (extended settings).

**Comment by r10s** [comment]
yeah, i think we will set In-Reply-To sooner or later (hopefull sooner :)
however, closing this issue in favor of https://github.com/deltachat/deltachat-core/issues/72
