### ISSUE TITLE
Revisiting FAQ: Which messages do appear in Delta Chat?

### ISSUE THREAD

**Issue by testbird** [deltachat/deltachat-core#134]
From what I read the FAQ may not be fully up to date, after the prompting has been introduced.

This is a draft based on my currrent understanding, and a possible problem:

---
## Which messages do appear in Delta Chat?

Delta Chat automatically opens messages coming from **"known contacts"** in a chat:

- Messages from contacts in your **address book**
- Messages from contacts **contacted by you** (at least one message or email sent)

Thus, your "sent" folder and address book is watched to gather your known contacts.

And Delta Chat asks to open a chat for **"engaged contacts"** (that heard of you):

- Messages from contacts that have been **engaged by a known contact** (found in the `To:` or `CC:` field of messages from known contacts.)
- **Replies from unknown contacts** to messages originally send by you (but coming from unknown, because otherwise they would already be "contacted by you")

Other incoming messages do not appear in chats automatically.  New chat attempts coming from not yet known addresses need to be looked out for by selecting **~~Contact requests~~Unapproved Chats** from the main menu, where all other incoming email messages get listed and can be answered, if desired.

---

Problem?
**Why** is it necessary to ask for messages from engaged contacts?
* Because a lot of engaged addresses might be collected over time, and spam may easily seem to come from engaged contacts.
* Because messages might not be chats but longer email that are better answered with an email program.

Alternative?
* Authenticate based on key gossip from the engaging known (and possibly verified) sender?
* Only allow (or still ask for?) replies from engaged contacts to answer an engaging message (require engaged contact AND reply-to/reference)? (Group chat should already exist.)

**Why** is it necessary to ask for opening replies from unknown? To see replies when messages got forwarded.
* Is this worth the risk? :

Prompting for all "replies from unknown" may be problematic and possibly easily improved.
* It is enough to know a message id sent by deltachat to create pop up spam messages for deltachat. This is especially problematic with public mailing lists.

Alternative?
* Treat "replies from unknown" as all other messages from unknown senders? MUAs that support multiple email accounts are able to reply forwarded messages from the correct address anyway. "Replies from unknown" as well as "chat messages from unknown" could be counted and indicated separately from other random unrelated email messages.

**Comment by testbird** [comment]
I could imagine an improvement to more easily find chats attempts from unknown contacts:

"Unapproved Chats" could count and list chat messages (E-Chat compliant or subject starting with `Chat:`) separately.

**Comment by WinAuthFan** [comment]
Only emails in which the header indicates that it's a chat OR emails that are replies to my emails that are chats should be displayed in Delta Chat. 

Even if a contact is emailing me, it doesn't mean the message should show up in the Delta Chat main screen. They might be sending me a longer-form / more traditional email, which is too long to read and reply to in Delta Chat. In Delta Chat, I only want to see chats. Chats are replies to chats that I have initiated or emails in which the header indicates that it's a chat. 

There could be a button on the main screen (similar to where the `Archived chats` words are currently on the main screen) that has incoming emails from contacts that are not chats. That way, I can, if I want to, check incoming emails from contacts, and then reply to them with chat. Or, I may choose to open them in a regular MUA, if it's not a chat, but a more traditional email.

**Comment by testbird** [comment]
Allowing any email with a subject starting with "Chat:" would open a way for spam, but maybe have a look at https://github.com/deltachat/deltachat-core/wiki/Use-Cases, it propoess

       4) have a max. chat message length option

The "contact requests" available in the menu (see issue https://github.com/deltachat/deltachat-core/issues/48) show your incoming emails.

**Comment by WinAuthFan** [comment]
> Allowing any email with a subject starting with "Chat:" would open a way for spam

Subject starts with `Chat:` PLUS the sender is one of my contacts (which is already the requirement now). 

> The "contact requests" available in the menu (see issue #48) show your incoming emails.

Yes, I am saying it would be better if it was not in the menu, but on the main screen. Getting it now takes two presses, and it's hidden away in the menu, so you don't even know it's there. On the main screen, it only takes one press, and you see it easily.

**Comment by r10s** [comment]
closing this for now here, of course, the discussion can go on in the new support forum at https://support.delta.chat

also, any pr that clearify things on the webpage are very welcome :)
