### ISSUE TITLE
Subject prefix

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-core#136]
This issue is about the `Chat:` prefix of all subject lines sent by Delta Chat.

This issue continues the discussion started in at https://github.com/deltachat/deltachat-android/issues/47 at part of other issues.

The idea of the subject prefix `Chat:` was to be equal for all users and make it easier to filter such messages in other e-mail-clients (analogue to `Re:` or `Fwd:`).  
(if other e-mail clients [cannot filter for this](https://github.com/deltachat/deltachat-android/issues/47#issuecomment-376815583), i think these e-mail clients are broken :)

For this point of view, it does not make sense to make it editable to the user or let the user disable the prefix (btw. in one of the next versions the subject will be moved to the encrypted part, same as enigmail does - EDIT: the subject is protected now) 

However, **maybe we can skip the prefix at all?** This could improve the integration with existing MUAs and make Delta Chat messages look more "normal" - for replies we could use the Re: form instead of the text excerpt. This would also make the support of mailing list easier (#125).

EDIT: without the prefix it might also be easier for some MUAs to follow the threads, esp. if Delta adds more correct In-Reply-To and References headers.

**Comment by testbird** [comment]
Using the `Re:` convention seems fine to me. (At least it is common and doesn't introduce yet another thing that is hard to translate.)

**Comment by testbird** [comment]
For filtering of Email-chat compliant messages: What is the `Chat-Version:` header's meaning? Is this the onel?

**Comment by r10s** [comment]
The `Chat-Version` header is for [detecting messenger messages as such](https://github.com/deltachat/spec/blob/master/spec.md#email-chat-specification). If the client allows it, this can be used perfectly for filtering.

**Comment by testbird** [comment]
A thing I didn't realize earlier is that dropping the `Chat:` prefix would also improve the "DC as full MUA" use-case.

**Comment by testbird** [comment]
On the other side, without `Chat:` is there still some way to filter email answers from non-Chat clients into the chat folder on the server (e.g. sieve), before DC gets online and can do it based on the `in-reply-to`?

**Comment by testbird** [comment]
> Edit: This drawback becomes irrelevant if the subject is encrypted anyway.

Actually, the memoryhole standard seems to allow to have different headers in the unencrypted part.

So __in encrypted messages__, it might thus be possible, and useful for better MUA compatibility?, to provide an additional, unencrypted subject header that lets users at classic MUAs know what kind of message they have at hands, and allows filters to still work based on the (generic) subject. Something simple like `Chat:` or more explicit and translatable like `Autocrypt Email-Chat Message`, that would allow automatic filtering of encrypted chat messages in all languages [^Autocrypt Email-Chat .*]?.

But it won't help to filter answers to unencrypted messages from classic MUAs. So, in the end this looks like a default setting and per contact preferences (possibly autodetected) is needed, indicating whether to use `Chat:` prepended subjects (separate chat use-case) or the plain `Re:` compatible convention (full MUA use-case).

**Comment by testbird** [comment]
Considerations:

* The only drawback of the `Re:` convention is that non-chat-compliant answers would sit in the inbox (not filtered by server) until a chat client moves them according to `in-reply-to` (more or less instantly), but already having caused a duplicate notification by classic MUAs. Does this warrant using `Re:` in the messages for greater simplicity and compatibility? 

* In any case, a not-encrypted subject in encrypted messages could still make autocrypt chat message identifiable by others `Chat: Encrypted Message`.

**Comment by testbird** [comment]
* For classic MUAs the `Chat:` with the message content in the subject has the advantage that the message list (with subjects) show the course of the conversation (more simmilar to chat view).

**Comment by kevincox** [comment]
I vote for dropping the prefix (or at least having it configurable), it would make delta chat quite useful for replying to regular mail. I would never do that as is because the `Chat:` prefix is unsightly. 

>  (if other e-mail clients cannot filter for this, i think these e-mail clients are broken :)

While I agree with you, I would also say that if you make a product that doesn't work on the most popular email client your product is also effectively broken.

**Comment by Hocceruser** [comment]
What about this:
If _the other user_ uses DC as well, the `Chat:<beginning of mail>` prefix is used.
If _the other user_ does not use DC, `Re:...` or no prefix is used.

**Comment by r10s** [comment]
i do not get the point of making a difference here - if the other user uses Delta Chat, the subject is not displayed at all.
what, if the other user uses Delta Chat _and_ another non-Delta client?

**Comment by testbird** [comment]
Maybe, use `Chat:` as long as no subject specified (in DC and by others)?

And how to specify a subject in DC? Maybe by writing a message in the same way a subject is shown? `This is a subject - This is the beginning of the message body...`

**Comment by Hocceruser** [comment]
@r10s personally, I have two kinds of contacts:

1. they also use DC. We usually write a lot of short messages and I am glad that they are sorted into a different folder. If I didn't use DC for a longer time I would probably set up a filter in Thunderbird to sort these messages in another filter.

2. They do not use DC. We usually write longer emails. But I mostly do not use DC to answer as I think that the Chat: prefix would look weird.

**Comment by r10s** [comment]
> They do not use DC. We usually write longer emails. But I mostly do not use DC to answer as I think that the Chat: prefix would look weird.

to be honest, this is also what i am thinking sometimes :) would be nice if the delta messages look very "normal" in these cases.

**Comment by WinAuthFan** [comment]
Here is an idea. 

If DC is initiating an email, or if it's replying to an email with a `Chat:` prefix in the `Subject`, add / keep the `Chat:` prefix. 

If DC is replying to an email without a `Chat:` prefix in the `Subject`, do not add the `Chat:` prefix. 

This keeps the best of both worlds. 

If you are exchanging short messages, the `Chat:` prefix lets people know about it. If you are using DC as a regular MUA to reply to your normal email, there is no `Chat:` prefix.

**Comment by r10s** [comment]
> If DC is initiating an email, or if it's replying to an email with a Chat: prefix in the Subject, add / keep the Chat: prefix.

in case of initial group messages, we could even use just the group name as the subject. this would also address https://github.com/deltachat/deltachat-android/issues/290 (request of an editable subject - i would not like this) in a way.

**Comment by r10s** [comment]
> Just the group, won't that be too sparse?

Why?
For compatibility with existing clients, this seems not the worse approach.

If i create a group "Meeting in Brussels" and add 5 members and send a message to them, this looks good to me. Answers from other MUAs as well as from Delta could be just "Re: Meeting in Brussels" so that there is just no break.

> I don't understand the relationship here yet.

well, in general, the request is about editable subjects. using the editable group name as the initial subject should mitigate the issue. (esp. as, in my experience, people not tend edit the subject line when replying)

**Comment by testbird** [comment]
I see, haven't created a group for a while. 

If the group creation message text is pre-filled with an editable template like "I just created this email group. Just use answer (all) to communicate in the group.", the receivers would be explicitly informed anyway.

**Comment by WinAuthFan** [comment]
@r10s - you are thinking of groups as "topical groups" -- groups on a particular topic, such as "Meeting in Brussels". 

In my case, groups are not on a particular topic, but just groups of similar people. "Family", "Work Friends", "School Friends", etc. Similar to "Circles" in Google+. With these kinds of groups, I personally don't like the subject `Chat: [group name]: [first few words of message]`. It's just not informative. 

The most important part of the `subject` is `[first few words of message]`. In the `Chat: [group name]: [first few words of message]` approach, that part is at the very end, where many MUA's will hide it anyway. The most important part of the `subject` should be closer to the front. 

Why do people even need to see in the subject that other people are receiving the email too? With regular emails that are sent to multiple people, you don't indicate that in the subject.

**Comment by WinAuthFan** [comment]
@testbird - I don't like all the group-related emails either. Group creation email, and email when someone is added or removed from the group. 

For people using other MUA's, these emails are just confusing, even scary. "What group? I am not part of any group! Why are you adding me to some group **without my consent**?" 

Instead, I suggest this: 
* Other MUA's already show all the recipients of an email. Emails to more than one person are very common, and people know how to deal with them. They don't need any special extra emails informing them about multiple recipients. 
 * In DC, you should show all the group members at the top of the screen. If members are added or deleted, DC can detect it -- if the headers say that the message is part of the same thread, but the recipients are different, then someone was added or deleted. DC should show a change of group members in the same place it now shows the date when the date changes.

**Comment by r10s** [comment]
@WinAuthFan i've seen many folks using the groups of messengers for topics or for sorting stuff. in my experience this is especially true for younger folks that grew up with messengers.

**Comment by testbird** [comment]
Concerning removal of `Chat:` also see above (MUA replies).

Thus, maybe use a symbol, like in `> text of message` or `group | text of message` **if no specific subject was defined in deltachat** (i.e. to write to classic MUA contacts) https://github.com/deltachat/deltachat-android/issues/290#issuecomment-401919062 It would make the `Chat:` identifier shorter and not have any translation problem (the translated footer still provides an explanation).

Groups:
Don't the member changing messages have the purpose to inform others, providing a new shared receipient list for further messages (answers in MUA)? They enables users to remove themselves or others, with group wide effect.

I have only the `From:` in the message list (not `To:`) and like to have a short group name (abbrevation) that allows filtering by group.
The [group name] tag is common with mailing list servers, maybe not so with "recipient groups" https://github.com/deltachat/deltachat-core/issues/49, but it it's probably the only way to provide a recognizable grouping and context for messages in classic MUA inboxes (with changing recipient lists).
As preferences differ, it may warrant a per group option.
 - [x] include [recipient group name] tags in message subjects

**Comment by testbird** [comment]
Or empty square brackets ("no distribution group") as a `Chat:` symbol? 

`[] Hi, there. A chat this is.`

**Comment by testbird** [comment]
`[Deltachat] A problem with this identifier symbol is that` 
 `[Deltachat] it is not distinguishable from mailing lists messages.` 
 `[Deltachat]  (So they could falsely end up getting filtered into the chat folder.)` 
 `Re: [Deltachat]  So it would need some modification!` 
`-[Deltachat] Yes, maybe something like in this subject?`

**Comment by testbird** [comment]
(The brackets -[ ] in my proposed solution are to be part of the subject, not demarking substitutions)

There is also #49. Talking about "recipient lists" should also help avoid misunderstandings like the "I'm not part of any group/ don't add my without my consent, etc.", from above.

**Comment by WinAuthFan** [comment]
We could let the user decide whether there is a prefix at all and if so, what it should be. Different users might have different preferences. The preferences might also depend on the specific chat. #239

**Comment by r10s** [comment]
closing this in favor to https://github.com/deltachat/deltachat-core/issues/128
