### ISSUE TITLE
Always send mails BCC

### ISSUE THREAD

**Issue by genyuz** [deltachat/deltachat-core#14]
To be able so see all messages (even the own ones) in the INBOX or ARCHIVE of the desktop-mail-client it would be great to have the possibility to define a general BCC-address to be used for every message that is sent.

**Comment by r10s** [comment]
I do not really understand this issue. All incoming and outgoing messages are already present on the server - by default, they're copied to the "Chats" folder.

**Comment by genyuz** [comment]
Hello Björn,

I was on vacation - so sorry for my late reply.

Here is my use-case:

I want to be able so see the complete conversation (my messages and the messages of the communication-partner) in one view in the usual e-mail-client (like Thunderbird). Therefore I usually send all
messages in BCC to myself so they appear next to the ones that I receive. The nice side-effect with this work-flow is that the message-ID of my reply is the correct one in this case and Thunderbird
and most other e-mail-clients shows the message correctly in the threaded view

Using Delta Chat currently the incoming messages got to the INBOX while the send messages go to Chats, which is nice as it fits the usual behavior of other email-clients putting outgoing messages to
some kind of SEND-folder. So for me the only thing that is currently missing is the possibility to define a BCC-address where each of my messages is send to.

Greetings from Dresden,

Stefan

**Comment by r10s** [comment]
Okay, I think I understand.

I'll try to summarize this from the view of Delta Chat:

- Delta Chat moves in incoming and outgoing _chat_-messages both to the chats folder, I think, this is just fine.

- _Non-chat_-messages are not moved to any folder by Delta Chat. Delta Chat leaves this up to the "normal" email client or up to the user

I think, you want to address the second case with your BCC approach, so that send messages are shown beside the incoming ones in the INBOX. 

Well, I'm not sure, if this is something, Delta Chat should worry about. Seems to me this is a job of the "normal" client to show the messages as desired. However, any discussion on this point is welcome.

**Comment by bokf** [comment]
I also like this feature request. On normal email conversations I send mails always BCC to myself to have them in the INBOX. As I use multiple devices with POP, I have the whole conversation on every device. 

I made a similar proposal in issue #28 https://github.com/r10s/deltachat-android/issues/28 and I like the idea to use BCC for this improvement. People who like it can add the BCC adress, people who dont need it, leave it blank.

For now I move every few weeks all messages from CHAT folder to INBOX folder manually on the webinterface of the provider, to have pictures etc. in my normal mailbox.

**Comment by csb0730** [comment]
If some people need it, why not?!
It seems not to be a big deal. Simply add a setting for it and add the bcc header to each message sent.
Isn't it?

**Comment by stefan-niedermann** [comment]
Because adding mindless an option for every edge-case feature will lead to much code complexity, bad maintenanceability and clutter the user interface (what could result in less or confused users).

Especially "noobs" - as far as i understand - are the primary target for this app.

**Comment by genyuz** [comment]
> Because adding mindless an option for every edge-case feature will lead to much code complexity, bad maintenanceability and clutter the user interface (what could result in less or confused users).

I totally agree! But who said, that this option is mindless ;).

I don't think that having this would confuse anyone. I've seen (and been using) this feature in every single e-mail-client I was ever using in the last 20 years (Thunderbird, Amiga YAM, Apple Mail, Evolution, mutt, Maildroid, even Outlook seems to be able to do so) and never heard anyone complaining about this option. For me this would make delta-chat integrate chats perfectly into my usual e-mail-workflow (which currently does not). 

> Especially "noobs" - as far as i understand - are the primary target for this app.

Really? I think delta chat is for people that care about privacy and existing free standards and therefore don't want to use WhatsApp. I'd say noobs will use WhatsApp and Co. but not an e-mail-based-messenger. I'm sure that noob will not be able to setup gpg-encryption - regardless how much effort someone will spend to build a usable GUI.

However I strongly vote for this feature.

**Comment by genyuz** [comment]
> I'll try to summarize this from the view of Delta Chat:
> 
> * Delta Chat moves incoming and outgoing chat-messages both to the chats folder, I think, this is just fine.
> * Non-chat-messages are not moved to any folder by Delta Chat. Delta Chat leaves this up to the "normal" email client or up to the user
> 
> I think, you want to address the second case with your BCC approach, so that send messages are shown beside the incoming ones in the INBOX.
> 
> Well, I'm not sure, if this is something, Delta Chat should worry about. Seems to me this is a job of the "normal" client to show the messages as desired. However, any discussion on this point is welcome.

Ah, I understand the approach now and this may work, if every person I'm chatting with would use delta chat. But actually everyone I send a message using delta chat replies using a different e-mail-client. And all these responses end up in the INBOX. So at the end I have some of the messages in the Chat-folder, some in the Sent-folder and some are in the INBOX.

**Comment by bokf** [comment]
For me the idea behind is an easy storage of all messages (and pictures) and the availability on all devices.

I use pop accounts on several computers/devices. By sending each email message also BCC, I have the full history on every device.

I never use the webinterface of my email providers. I delete messages automatically after one year.

For Deltachat to integrate into this system this means, every sent message should also be sent to myself BCC to be also in my inbox. The received messages should be copied and not moved to the chat folder. At the end the full history of Deltachat of sent and received messages is in my local inbox on each computer/device.

**Comment by r10s** [comment]
At least for now, this is out of scope of Delta Chat, I think this should be solved by server, if really required, which also fits better into a multi-device setup.

**Comment by testbird** [comment]
> Ah, I understand the approach now and this may work, if every person I'm chatting with would use delta chat. But actually everyone I send a message using delta chat replies using a different e-mail-client. And all these responses end up in the INBOX. So at the end I have some of the messages in the Chat-folder, some in the Sent-folder and some are in the INBOX.

As these are replies to deltachat messages, I think it might be OK to solve this by letting deltachat also move non-delta MUA replies into the chat folder, based on the `in-reply-to` header.

And it would fit with the filtering needs of switching to using the `Re:` convention.
https://github.com/deltachat/deltachat-core/issues/136#issuecomment-377172662

**Comment by r10s** [comment]
nb: the current android-dev and the upcoming f-droid release uses bcc-self instead of a separate imap-upload, see https://github.com/deltachat/deltachat-core/issues/370
