### ISSUE TITLE
Detection of incoming/outgoing messages fails under some circumstances

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-core#150]
@Ampli-fier has a setup where the messages are not detected correctly as _incoming_. Instead, the messages are shown as _outgoing_ with oneself as a sender.

To detect if a message was sent or received is not so easy as it seems; afaik, there is no clear information about this in the headers or somewhere.

Currently, we do roughly the following to find out the state.
1. set state to _outgoing_ and continue with the next step
2. if there is a `Return-Path` header, set state to _incoming_ and continue with the next step
3. if the `From` header contains the users address, the message is _outgoing_

(see https://github.com/deltachat/deltachat-core/blob/master/src/mrmailbox_receive_imf.c#L926)

So, if there is a mail that does _not_ have a Return-Path it will always be shown as _outgoing_.

@Ampli-fier can you confirm this? (this would also explain the automatically created chats - for outgoing messages there is a lower barrier to pop up)

If, so, we should **make things simpler** and skip the `Return-Path` test and just rely on the `From`-field. This would result in messages send by yourself from other e-mail-addresses as being marked as ingoing, however, this is not that wrong and maybe even a thing the user expects.

**Comment by testbird** [comment]
Hey, as the return-path is optional, this can really be a reason for the unexpected chats popping up.

As the above sequence starts with an unconditional "outgoing" assumption, the last step 3. seems reversed to me. (Expecting it to set "incoming", exept if `From:` equals own address.)

But my naive thought was simply that in outgoing emails the `From:` equals the own address, and all others are incoming.

If the return-path is really to be evaluated (But why?) I would have also tested it for the own address to find outgoing emails (with forged From?) in the same way.

**Comment by r10s** [comment]
The return-path is evaluated as my first idea when starting Delta Chat was that outgoing mails may have different senders (eg. when restoring a mails from IMAP this may easily happen for older mails (currently, due to other problems, this function is not available in Delta, but it was at the beginning)

**Comment by Ampli-fier** [comment]
The `Return-Path:` is present, just at the bottom. The `From:` field is above. Maybe this matters.
The mails are from Outlook, maybe this also matters.

I can do debugging on the mails ... later.

**Comment by testbird** [comment]
> eg. when restoring [... different account] mails from IMAP this may easily happen for older mails

I'd imagine that `return-path` would also not help much, in this case.
IIUC the use of `return-path` is to explicitly direct bounces to another address, so when used accordingly it does not equal the sender, and is rather some trash or statistic/evaluation destination. Only optionally, even if often, might it get set as a redundant "From:".

**Comment by r10s** [comment]
> The Return-Path: is present, just at the bottom. The From: field is above. Maybe this matters.

_Should_ not matter.

> The mails are from Outlook, maybe this also matters.

More probable :)

**Comment by testbird** [comment]
Ok, maybe now I got what you intended: You let deltachat unset the return-path when it uploads outgoing messages to imap servers as backup, to mark them as outgoing?

**Comment by r10s** [comment]
> Clever solution!

Thanks, also for the great explanation. however, this kind of detection might be not necessary when one accepts that the outgoing mails always match the sender's address.

> Then, let's hope the detection error in this issue has a different cause.

I was a little bit hoping, @Ampli-fier could confirm the missing Return-Path and this issue is solved ;)

**Comment by Ampli-fier** [comment]
The `Return-Path` is present, just not detected as _regular field_ but as  MAILIMF_FIELD_OPTIONAL_FIELD (in mrmimeparser.c).

What could be a possible fix:
a) Perform a lookup in optional fields as well? 
b) Or try to figure out, why it is not detected as regular field? Any hint how to do that?

This is an excerpt from the mails source:
```
X-Originating-IP: [www.xxx.yyy.zzz]
X-MS-Exchange-Organization-Network-Message-Id: 54289<...>
X-MS-PublicTrafficType: Email
X-Microsoft-Exchange-Diagnostics: 1;DB6PR0701MB2519;35:XAAQ<...>==
Return-Path: <given name>.<name>@<company>.com
X-MS-Exchange-Organization-ExpirationStartTime: 16 Apr 2018 15:54:53.8232
 (UTC)
X-MS-Exchange-Organization-ExpirationStartTimeReason: Original Submit
X-MS-Exchange-Organization-ExpirationInterval: 2:00:00:00.0000000
```

**Comment by r10s** [comment]
> The Return-Path is present, just not detected as regular field but as MAILIMF_FIELD_OPTIONAL_FIELD (in mrmimeparser.c).

Ahh, thank you, this is super-helpful.

> a) Perform a lookup in optional fields as well?

Though I already done this - mrmimeparser_lookup_field() is used for checking; its data is created by hash_header() which puts optional and regular fields into the same namespace (the type is checked, however, to access the data later, but this is not needed for just checking the presence)

> b) Or try to figure out, why it is not detected as regular field? Any hint how to do that?

We have to dive into libEtPan for this. However, as this is available as source code, this should not differ from regular debugging.

OTOH, i am wondering if we can just skip the Return-Path test.

**Comment by testbird** [comment]
> which puts optional and regular fields into the same namespace

Is overeriding regular fields with optional fields possible? Or prevented, to not allow the sender to mess with them?

**Comment by testbird** [comment]
> There is nothing around, just the plain address

Didn't see that before, but now I searched and found it in a mail someone sent like that with "kmail". Maybe the header is lower down, and plain, when the some MUAs actually set the return-path before sending.

**Comment by r10s** [comment]
> What is the equivalent to [...] display_cc

i've just commited some lines that print the Return-Path when it comes as a regular field (see https://github.com/deltachat/deltachat-core/commit/59cf43a254bfa12d1838b4b63e80b3cb00055153 ).
just noticed that it comes _always_ as a non-regular but optional field for me.

would be interesting if the Delta Chat-check at https://github.com/deltachat/deltachat-core/blob/master/src/mrmailbox_receive_imf.c#L923 is reached.

**Comment by Ampli-fier** [comment]
Ups, these lines lead to 'quick exit' of DC Core:

```
>> Message-ID: 738...@<server>
Segmentation fault
```

I think I understood why my mail to you does not cause the issue for you: I am within the 'organisation'.

**Comment by r10s** [comment]
I have done some research:

There are two basic function parsing headers:

1. [mailimf_field_parse()][1] forwards it to [mailimf_return_parse()][2] which creates the _regular_ structure.
    - mailimf_return_parse() failes with error MAILIMF_ERROR_PARSE if the argument is not put into angle brackets. Depending on the calling function, an _optional_ structure _may_ be created then.
2. [mailimf_envelope_field_parse()][3] always creates an _optional_ structure

These two functions are called under a larger number of circumstances.

In all of my tests, I could only success to reproduce 2. However, 1. seems to cause the error of the missing Return-Path.

@Ampli-fier Regarding the Segmentation fault: I cannot reproduce this as well here, however, I've hardened the printing a bit in https://github.com/deltachat/deltachat-core/commit/c23e63da3f24372859243c60585c7b2d140f80bb

[1]: https://github.com/deltachat/deltachat-core/blob/master/libs/libetpan/src/low-level/imf/mailimf.c#L4299
[2]: https://github.com/deltachat/deltachat-core/blob/master/libs/libetpan/src/low-level/imf/mailimf.c#L6631
[3]: https://github.com/deltachat/deltachat-core/blob/master/libs/libetpan/src/low-level/imf/mailimf.c#L7330

**Comment by r10s** [comment]
Apart from all these weired things - maybe we should just change the logic and do not rely on Return-Path at all. A little overview

Current logic ( /_ and _\ show the direction the bubbles point to):

&nbsp;   | has Return-Path  | no Return-Path
---|---|---
**From == Sender** | &nbsp;&nbsp; outgoing_\ | &nbsp;&nbsp; outgoing_\
**From != Sender** |  /_incoming | &nbsp;&nbsp; outgoing_\

The 3rd  "outgoing" above is the problem we're talking about. We do not check the sender here as we assume a missing Return-Path is always an outgoing message; the advantage of this assumption is that we can also show messages from ancient/different e-mail-adresses as outgoing.  
_If_ we would check the sender, we can skip the return path check at all:

&nbsp;   | &nbsp;
---|---
**From == Sender** |  &nbsp;&nbsp; outgoing_\ 
**From != Sender** |  /_incoming 

Messages from ancient/different e-mail adresses would no longer be shown as outgoing then. Instead a new chat would be created with the ancient/different e-mail-address as a normal contact.  
Maybe this is even more logic and useful - eg. otherwise you have no chance to see the real sender.

**Comment by csb0730** [comment]
What about cc: ? Is is seen like To: ?

**Comment by r10s** [comment]
Cc: yes, there is no difference to To: in Delta Chat, I think this is okay.
Bcc: i've just checked this, they also go to the member list, however, I think they shouldn't. Not sure what to do with this field, probably the best would be to ignore it.
(both situations may only happen when cc: or bcc: are used from another app, eg. Thunderbird in a multi-device setup)

**Comment by r10s** [comment]
I've disabled the check for now, just to check how it works. below is a screenshot for a typical scenario: 
_Alice_ sent a message to _r10s_ that is forwarded to my account used by Delta Chat. All three addresses could be clearly identified:

![image](https://user-images.githubusercontent.com/9800740/39152558-0d281306-4749-11e8-91e8-e0f5cb5726be.png)

Before, when checking the Return-Path header, the r10s mails are shown as being outgoing on the right side - in fact, they were not sent on another device with another e-mail address, so not _really_ outgoing in this meaning.

Also, before, I was not aware, the r10s address was involved in a chat - now this is no problem.

So, apart from the issues above, I think this is simply the better solution for such cornercases.

**Comment by Ampli-fier** [comment]
A quick check with self-compiled Android version shows good results:

Before, basically all messages created ad-hoc groups and the sender was always 'Me'.

Now, new mails go to Contact Requests and mails received to existing groups have the correct sender information.

:smiley: 

Regarding the seg faults. They did not disappear, even with the hardening. I would remove this part you added for trouble shooting:

```
case MAILIMF_FIELD_RETURN_PATH:
...
```

It simply crashed the Core part (with a certain message being parsed), even when I did only have a printf statement insinde the case statement.
