### ISSUE TITLE
Old mails are downloaded sometimes

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-core#156]
Sometimes, Delta Chat starts to download old messages, i could not figure out the reason for this yet, seems to be an issue with the UID logic in the IMAP processing, https://github.com/deltachat/deltachat-core/blob/master/src/dc_imap.c

**Comment by testbird** [comment]
How can this downloading be noticed?

(In case that delta chat got newly installed, it could actually be desirable to download the messages from the server. Then only the setup message could be enough to (re)set up a (new) device, no need to transfer backup anymore, then.)

**Comment by r10s** [comment]
> How can this downloading be noticed?
well, there are old mails in the chats (older that the time Delta Chat was installed)

**Comment by testbird** [comment]
> old mails in the chats (older that the time Delta Chat was installed)

Hm, somehow I would expect that from a decent email client: To show all the messages that are on the server. (Also needed e.g. to delete messages.)
Of course Email-chat clients may default to show only chat messages.

**Comment by r10s** [comment]
"It's not a bug, it's a feature" :)

**Comment by testbird** [comment]
> "It's not a bug, it's a feature" :)

Yeah, was the server import introduced, or rather solved :) to some degree recently?
I remember @Ampli-fier providing instructions that I did not manage to try out, before somehing was changed. https://github.com/deltachat/deltachat-android/issues/210

**Comment by testbird** [comment]
In case you plan to further disable all downloading, to avoid filling up deltachat with huge archives:

Maybe instead just limit the inital download to the last 20 messages (even already seen) in INBOX, to not fill-up DC, and still have some current messages to be found by new users when they start exploring the app.

**Comment by sketet** [comment]
hello, I really would like to show old emails - that I used as chat.
if I can't view them I can't find the reason to use this messenger.

in the faq there is:

> Which messages do appear in Delta Chat?
> 
> Delta Chat automatically shows …
> 
>     Messages from contacts in your address book
>     Messages from contacts contacted by you
>     Replies to messages send by you
> 
> Other messages do not appear automatically. You can see the other messages in the main menu at Contact requests and, if desired, start a chat from there.


I've the contacts in the addressbook, but no one email is showed.

**Comment by testbird** [comment]
I think we all agree, and need this. But it needs work to get implemented. @Ampli-fier tried to trigger downloading manually, and it seemed to work for him in an older version.

**Comment by testbird** [comment]
@sketet Just in case, maybe the import/export function in the advanced settings can help you in the meantime.

**Comment by sketet** [comment]
I'm doing several tests. I think there is something wrong.
I moved all the emails of the Chats folder to another folder, the Chat folder is empty now but in DC remain the last conversations... why?

**Comment by testbird** [comment]
Yep, for configuring the downloading of server **Chat** deletes I added a draft for a "Local Chat History" option to  https://github.com/deltachat/deltachat-core/wiki/IMAP-strategy. For **Emails** I reported https://github.com/deltachat/deltachat-core/issues/195

**Comment by sketet** [comment]
hi, I installed an old version, now DC show all the emails in **Chats** folder.
what would happen if I update?

--- DC is very a great app, a messenger app that use the email... it's what I've always been looking for. Unfortunately it still has some features that I don't like at all. It's a very pity, it's unique and there are no alternatives. ---

**Comment by csb0730** [comment]
I think it's time to introduce some simple user options to give every user the control back how to use DC. It is not a good think to rule them to a certain workflow. As I experienced, there are some different approaches existing. But ok.
See other discussions here around options. For example "delete messages on server" or not.

**Comment by r10s** [comment]
while i agree in general, i do not agree that this is the correct time to introduce additional features :)
we should make the current set stable first.

**Comment by Ampli-fier** [comment]
I might have captured what is described here. I noticed that my phone was warmer than normal.
This started to happen when I could not connect to a PC. Around half an hour later I could do it and I saved the logcat information and an excerpt of the messenger.db's job table. I think I missed some parts, as I just quickly performed a 'grep' on a 'dump file'.
The logs are available [here](https://gist.github.com/Ampli-fier/10902670f56c6561441e2623dfa13a4c).

**Comment by Ampli-fier** [comment]
Created a new [gist](https://gist.github.com/Ampli-fier/28de0d1456a2a36e12e88f1772c93bd8), where 3 Read Receipts triggered more than 7000 Jobs. This could be related to downloading of old mails.

**Comment by r10s** [comment]
the bug seems to be still alive as just reported by @adbenitez on #deltachat irc.

**Comment by r10s** [comment]
@Ampli-fier with the account you gave me, i could enforce the behavior of the endless download loop somehow, not yet sure how to reproduce it and if it is really relating to the opening issue, however, it's a first step :)
