### ISSUE TITLE
Remove e-mail-address from pgp user-id?

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-core#158]
By convention, the e-mail-address is used as the user-id in public pgp keys, so does Delta Chat currently, see https://github.com/deltachat/deltachat-core/blob/master/src/mrmailbox_e2ee.c#L247 .

For Autocrypt as well as for Delta Chat, however, the user-id is [decorative](https://autocrypt.org/level1.html#openpgp-based-key-data), so we could replace the e-mail-address by a random string on key generation (maybe by a string that looks like a valid e-mail-address).

The advantage is less privacy leakage, eg. when keys are uploaded accidentally on a keyserver by a 3rd person. Moreover, on key changes, senders cannot use old keys from keyservers as there is no binding to the e-mail-addresss.

IIRC, we did not do this in the beginning to be compatible with Enigmail, however, AFAIK, meanwhile the Enigmail-Autocrypt-Implementation does not longer rely on the user-id - @pbrunschwig can you confirm this?

**Comment by pbrunschwig** [comment]
@r10s yes, Enigmail does not rely on the user-id anymore.

**Comment by r10s** [comment]
@pbrunschwig thank you for confirmation :)

**Comment by r10s** [comment]
the generated user IDs are a 64 bit random value that looks like an e-mail-address now, eg. `<643C9869@6B8B4567.org>`

**Comment by testbird** [comment]
Using an existing top level domain like .org might not be that good, as the full domain could be registered and made available in dns and keyservers.

Aren't there some known-not-to-exist-and-fail (reserved, not-register-able) domain alternatives? 

Or the other way around, a known blacklistable "domain" part like in 643C98696B8B4567@autocrypt?

**Comment by r10s** [comment]
> as the full domain could get registered and made available (and queried, metadata) in dns and keyservers.

What would be the harm or the attack scenario then? there is no relation from the user-id to the real e-mail address. this relation is only done implicitly when the key is used in a message for a given address. but not when you see the key alone - if it is eg. uploaded accidentally to a keyserver.

But in general, i agree, that `.org` may not be the best choice; I re-opened the issue therefore.

> But aren't there some known-not-to-exist-and-fail (reserved, not-register-able) domain alternatives?
> Looks .invalid is defined as such.

So maybe `643C9869@6B8B4567.invalid`. Maybe we could also use always the same e-mail address sth. like `foo@bar.invalid`, however, this may break indexing in other apps.



where did you read that the tld .invalid

**Comment by testbird** [comment]
`643C98696B8B4567@invalid` or ubiquitous `nobody@invalid`?

**Comment by testbird** [comment]
> However, as eg. Enigmail displayes the user-id in "Good signature from <user-id>,
> for now, we decided to leave the address in the user-id */

That may favor something more descriptive and rather using the reserved .example domain

`643C98696B8B456@example`
`643C98696B8B456@autocrypt.example`
`643C98696B8B456@random.autocrypt.example`

**Comment by testbird** [comment]
643C98696B8B456@current.autocrypt.example

**Comment by r10s** [comment]
as you may have noticed, for now, the user-id is still the e-mail address in 0.18.

- enigmail shows the user-id in a prominent place above the mail as "Good signature from <user@addr>" - i would have expected the e-mail-address here - @pbrunschwig is this by design? or are there changes planned?
- another point is that people could still upload _other_ keys with the user's e-mail-address and cause harm (thanks for this view @dkg)

i still believe that it might be a good idea to get rid of the e-mail-address in keys, however, meanwhile i am not convinced that the advantages are larger than the disadvantages.

**Comment by testbird** [comment]
So, IIUC only the fingerprint identifies a key. As the fields can be arbitrary, maybe the most correct thing would be to just fill it with `address@field.example`

Or, to allow local indexing of "Random" users:

`Random 643C98696B8B456 <address@field.example>`

**Comment by pbrunschwig** [comment]
> enigmail shows the user-id in a prominent place above the mail as "Good signature from user@addr" - i would have expected the e-mail-address here - @pbrunschwig is this by design? or are there changes planned?

Be careful here. The sender of an email may not be the person who signed the mail. Just displaying the email address without any further check is wrong in the first place. What matters is who **signed** the mail. 

I may in future versions of Enigmail consider looking up the sender's name in the Autocrypt store, but right now the information is only taken from the key. If a UID in the key matches the sender address, then that UID is displayed, otherwise the primary UID is displayed.

**Comment by r10s** [comment]
@pbrunschwig thanks for the insights.

**Comment by testbird** [comment]
So, would a valid info only be "from x, signed with *fingerprint* y" because the UID in the key is arbitrary, anyway, just as `Random Key 643C98696B8B456 <address@field.example>`.

**Comment by pbrunschwig** [comment]
I think you need to be a bit careful here. 

Let's assume I have an email signed by Alice's key ABCDEF01234567890. If I send you a modified version of that message with my email address in the From: field, and Alices public key in the Autocrypt header, then you have to avoid to display information that may trick the user into thinking he got an email signed by me. 

That is, something like `From Patrick, signed with ABCDEF01234567890` is less than ideal.

**Comment by testbird** [comment]
Hm, right.

So, as NO info is valid without having the key confirmed, maybe just show some form of "unvalidated message appearing to be from user@server" (or no assurance at all).


With autocrypt, the entire "level 1" communication in unvalidated by default.

As long as keys have not been confirmed, only upon a request for "manual key confirmation", a full `signed by key with unvalidated fingerprint AAAA BBBB CCCC ...` (not key ID or UID instead of the full fingerprint) might be displayed together with "Can you confirm this key and fingerprint to belong to the sender?", if the computation succeeded.

For autocrypt keys, the UID should even be displayed for confirmed keys, because they are just the "current setup keys" (similar to session keys?). (Detectable by using an invalid UID address `@*.example`?).

**Comment by r10s** [comment]
postponed.
