### ISSUE TITLE
Don't mark non-chat mails as read

### ISSUE THREAD

**Issue by censlin** [deltachat/deltachat-core#16]
Currently, when I open the mailbox in DeltaChat, all my mail is marked as read, including mail unrelated to chats. So I end up losing track of unread mail that I prefer to open in traditional mail client.
Could this please be changed to only affect mails that are part of some chat thread?

**Comment by r10s** [comment]
Thank you for your post, we leave this open for discussion.

**Comment by kskarthik** [comment]
*Temporary workaround:* use a separate mail for chatting

**Comment by JRHaigh** [comment]
Ah!!! So that's why a whole load of messages in my Inbox were marked unread today!!! Wait, it isn't just my Inbox, is it! Please remove the mark unread code in the very next release!!!

**Comment by luisfsr** [comment]
I also think that this feature makes life harder. It would be better if mails weren't marked as read when we visualize the inbox or other boxes...

**Comment by elfrinjo** [comment]
I would like to see deltachat completely ignoring non-chat messages.

- This should be optional, as I guess many user like to use dc as a replacement for their email client.
- Possible implementation: This might be achieved by filtering for a tag in the subject line.
- Other possible solution: only work on a subfolder. In this case, there is a relation to [Issue 12](https://github.com/deltachat/deltachat-core/issues/12)

**Comment by kollokollo** [comment]
Also I have observed that when I have read some of the Chat messages in the INBOX from Thunerbird on another comuter, they are not recognized by Delta-Chat anymore and thus not shown in the Chats.
When I move them out of INBOX and then again into INBOX, then they are again recognized by delta chat.

**Comment by r10s** [comment]
Not 100% sure, however, IIRC the stuff I've written before the holiday break, this issue should be fixed with the upcoming version 0.9.4 :)
