### ISSUE TITLE
Show only messages sent to a special address

### ISSUE THREAD

**Issue by webratte** [deltachat/deltachat-core#163]
I use a extentionaddress like "myName+deltachat@mailbox.org" to separate Chat and Mail. And I also have more alias addresses there.

Now, if I get a mail to my regular address "myName@mailbox.org" or to a other alias address hosted in the same Mailbox.org account it will also shown in Delta Chat.

But this Mail I would like handle like a "normal" Mail with e.G. K9 Mail. 
Mails which are not sends to "myName+deltachat@mailbox.org" will only spam my Delta Chat App.

**Comment by violoncelloch** [comment]
To read these mails you could import the key for witch mailbox encrypts to Delta Chat...

**Comment by webratte** [comment]
Yes of course.

But I still would like to receive in Delta Chat only mails which sendet to my "Chat Mail address".

Do you understand what I means.

I want keep Email an Chat separated without create another Mailaccount.

**Comment by r10s** [comment]
we now follow a "single-folder" approach and try to make things easier and better understandable for the user.

if you could manage server-sided to move all +delta addresses eg. to the folder DELTA and specifiy this folder and address in Delta Chat (the feature is available in the core, but not yet in the android/desktion ui), this may solve your problem.
the feature is not yet released, but at least some of the programming work is done, see https://github.com/deltachat/deltachat-core/milestone/2; also in android-dev, it will be available soon-ish.

closing this issue now as there is not work directly releated to it, however, free free to continue discussion here or on https://support.delta.chat/

**Comment by webratte** [comment]
I have just installed dev version 0.0.9.

But I can't find this feature.

Is it not implemented yet in this version?
Or I'm only to blind to see?

How ever, I like the idea behind Delta Chat and looking forward to first stable release 👍

**Comment by r10s** [comment]
@webratte it's implemented in the core, android-dev is still lacking an option, i'll file an issue

**Comment by webratte** [comment]
Thank you.

I can wait 😀

**Comment by r10s** [comment]
here's the issue https://github.com/deltachat/deltachat-android-ii/issues/132
