### ISSUE TITLE
Web-based Client

### ISSUE THREAD

**Issue by JonasDralle** [deltachat/deltachat-core#166]
Maybe this is a feature request to be reviewed in 2020 again.

In the first day of using this client the idea of having a web frontend similar to https://riot.im got loud in our d.c group. It would be nice!
Especially if it could run independently from the smartphone app.

Could be electron-wrapped and thus turned into an desktop app (#30)

**Comment by r10s** [comment]
wondering if web clients can speak IMAP/SMTP today - but maybe they can in 2020 :)

**Comment by labdsf** [comment]
@r10s 
In 2020 email servers speak [JMAP](https://jmap.io/).

**Comment by t-oster** [comment]
Well... a small webserver in the smartphone app would at least allow for operating the app from the browser if they are in the same LAN.
If we want an app independently from the smartphone app I agree, this won't work without an additional webserver...

**Comment by labdsf** [comment]
In 2020 web clients speak [JMAP](https://jmap.io)

**Comment by r10s** [comment]
@labdsf yes, a wider acceptance of JMAP would be great, possibly with the option to let the JMAP server feed push messages to APN or FCM/GCM.

**Comment by r10s** [comment]
well, in between, the [node.js bindings](https://github.com/deltachat/deltachat-node/) are there and a [desktop-version](https://github.com/deltachat/deltachat-desktopn/) based on this is started :)

to keep things open to a broader audience, in future, we should move such discussions to the new forum at https://support.delta.chat which is better for higher-level discussions.

this will also keep the issue tracker free for bugs and _concrete_ things to do :)
