### ISSUE TITLE
Cannot append message to "Chats", error #4

### ISSUE THREAD

**Issue by csb0730** [deltachat/deltachat-core#170]
Delta Chat version 0.17.1

Here a rough description of the error situation.
@r10s has a more detailed log excerpt.

  T2: Executing job #6, action 700...
  T2: Appending message to IMAP-server...
  T2: IMAP stream lost; we'll reconnect soon.
  Error message: 'Cannot append message to "Chats", error #4'
  T2: Job #2 delayed for 600 seconds
  T2: Executing Job #7, action 100...
  T2: Marking message xxxxxx for deletion....
  T2: IMAP stream lost; we'll connect soon

This process is going on then! error #4 comes up again and again.

Seems that  there is a problem in synchronisation of some internal things?

**Comment by t-oster** [comment]
Hi, which mail-provider are you using? I do not have that problem, so I cannot reproduce

**Comment by t-oster** [comment]
it looks to me as if error 4 is `MAILIMAP_ERROR_STREAM` which occurs here: https://github.com/deltachat/deltachat-core/blob/master/libs/libetpan/src/low-level/imap/mailimap.c#L611.
This could mean the IMAP stream is lost exactly after the APPEND command is sent, which may result in the mail being appended, but DC thinking it was not, which would explain why it was tried over and over again.
But the question is, why the stream is lost exactly then. As I understand, you can not reproduce this issue?

**Comment by csb0730** [comment]
I'm not shure if it can be reproduced. I'm simply waiting now to see it again.
I saw this situation now two times and first time after installing 0.17.1. It's possible that there is a relation to the DC version, but it's possible also, that the mailserver forced this behaviour. I don't really beleave that this is a mailserver's issue.

If this `T2: Executing job #6, action 700...` is the first action and DC doesn't check the connection state before then it could be a problem in DC's logik.
That could explain why the error happens immediately after launching the APPEND command because the   connection is not stable or existing any more.
Something like that is my assumption so far.

I think this issue here can be in relation to the new efforts @r10s  is doing to make connection handling more reliable and clear.

**Comment by csb0730** [comment]
With new versions (v0.18.x) after reworking imap handling never seen again :)
So I assume this issue was related to that and can be closed now.

**Comment by r10s** [comment]
thanks for closing :)
