### ISSUE TITLE
AppStore, Google Play beside F-Droid

### ISSUE THREAD

**Issue by niebert** [deltachat/deltachat-core#174]
Thank you very much for your release on F-Droid. Your work is great for having a privacy friendly messager that uses existing institutional e-mail infrastructure as a messenger network.

Looking forward for reaching a wider audience with AppStore an Google Play. Maybe it will relevant for institutional and organisational applications.

**Comment by r10s** [comment]
Thank you for your post :)

With respect to Google Play, we have a milestone for this:
https://github.com/deltachat/deltachat-android/milestone/1
when these issues are (more or less) solved, we can make it in Google Play :)
