### ISSUE TITLE
add Chat-Server support

### ISSUE THREAD

**Issue by momedo** [deltachat/deltachat-core#178]
Delta Chat is a very nice project!

Maybe you know, 
- that Gmail offers, if you create a new account for delta chat, in the first month only 500 emails, which means chat lines over delta.
- and Gmail requires a setup to allow unknown foreign clients, which is set in a very deep path in the web, not easy to find,
- furthermore we tested delta over a period of 3 months with web.de until they disabled cryptographic traffic to delta, the client was disfunctional at a certain point of time
- switching to gmx.net also showed the same.

How do we know, that not further e-mail-provider will also not allow the access to IMAP with delta?

Hence this issue should report a feature request, to allow delta also with a dedicated server software in a hybrid architecture.

We suggest to use the very easy to administer server software of e.g. SmokeStack, found here:
https://github.com/textbrowser/smokestack

The gui code to work with this server is very small and easy to add:
https://github.com/textbrowser/smoke
 
Maybe you want to consider an enhancement of the delta friendslist to add not only e-mail addresses, but also the identifier of the smoke chat tool, which is a SIP-Hash.

thanks for an evaluation, if this chat server next to IMAP could be added, also for backup processes.

Many thanks

**Comment by STPKITT** [comment]
Interesting findings regarding Web.de and GMX! In which way did you get to know about Web.de and GMX "disabling cryptographic traffic". Did they send you an E-Mail telling you what's going on or what? And what do you mean exactly with "disabling cryptographic traffic"?

What does SmokeStack have to do with E-Mail? Isn't SmokeStack something totally different?

**Comment by r10s** [comment]
hi @momedo - thank you for your post. 
where where did you see the gmail-limit of 500 mails/month?
i am only aware of a [limit of 500 mails/day](https://support.google.com/mail/answer/22839).

however, in general, gmail and other very limited servers are not the providers i would recommend - and the good thing with Delta Chat is that you have a choice :)

**Comment by t-oster** [comment]
@r10s is right, you can use whatever provider you want or just be your own provider. Adding more protocols does not make sense IMHO, delta-chat has already a library which can be used in other Multi-Protocol-Messengers (like pidgin or other libpurble based clients) so here we should concentrate on the E-Mail-as-Messenger-Protocol stuff and not bloat the project with other features, which slows down the overall progress. No offence, just my 2 cents.

**Comment by testbird** [comment]
> tested delta over a period of 3 months with web.de until they disabled cryptographic traffic to delta, the client was disfunctional at a certain point of time

My contacts don't confirm this either. As DC does not yet auto-delete, may the mailbox have run out of space?

**Comment by r10s** [comment]
i do not think that we will add another protocol; therefore i close this issue for now
