### ISSUE TITLE
Feature: Move messages to DeltaChat folder on receive rather than or read

### ISSUE THREAD

**Issue by t-oster** [deltachat/deltachat-core#180]
When I receive a DeltaChat Mail, it stays in my INBOX until i read it in DeltaChat (eventhough it is already received by DC and shown as unread message).
I would like to change that behavior, so mails are moved to the DeltaChat folder on receive (they can still be marked as unread though).

This has to do with deltachat/deltachat-android#307 and #117 
This would be closer to the wanted sieve filters and may partly solve the double notification problem with K9 and other mail programs, if DC moves the message away before the other mail programs can recognize it.

**Comment by r10s** [comment]
iirc, then reason for moving messages only when "seen"  is multi-client: only the INBOX is watched via push and if it a messages is moved away by a device currently not in use (eg. the computer), the device in use (eg. the handy) may get the message delayed)

watching multiple folders at the same time might be a solution, however, this would increase the overall complexity, may have a bad battery impact (multiple IMAP-IDLE threads) and/or may not be supported by servers ([IMAP NOTIFY](https://tools.ietf.org/html/rfc5465)). i would not target this now; maybe if the app is overall stable after a first release.

however, maybe there is also another smart solution.

**Comment by csb0730** [comment]
I would suggest to be patient with that too.
If You are using another MUA's in parallel it is better to let it really in inbox.

For example I'm using Thunderbird and K9 in parallel with the same account and sometimes I need to
have the messages there in the inbox too. Especially if there are mails which are still not handled properly by DC.

**Comment by testbird** [comment]
Maybe the single-folder INBOX watch mode (current implementation) could be made to work well, by
1) keeping the current "move on read" behavior, and
1) having (requesting/setting) server filters that set the "seen" or "read" flag instead of moving.

May this be able prevent notifications in other clients, while supporting muli-client operation and working when only one folder is watchable (the general case), and continuing to leave messages in INBOX until (really) read and auto-moved with an Email-chat client?

The problem then shifts to solving the behavior of option 5) in https://github.com/deltachat/deltachat-core/wiki/Use-Cases.

**Comment by csb0730** [comment]
My experience is that DC sets the "read" flag for mails in INBOX properly so that they are seen as read in other mail clients (and vice versa no notification for new mails in DC if they are read by other MUA first).

**Comment by testbird** [comment]
> no notification for new [chat] mails in DC if they are read by other MUA first

That is why parallel clients using POP (but also doing unintentional browsing through chat messages using IMAP) makes notifications in DC unreliable.

Therefore the default of option 5) was intended to notify about all new chat messages (even with the "seen" flag). IIUC with the new strategy above, the option 5) default would become standard and the config option obsolete.  Multiple DC clients are envisioned to reliably not notify about messages already seen at other DC clients (message already moved), yet, parallel MUA access and replying is still easily possible without any risk of unintentional browsing or legacy pop setups to make DC messaging unreliable.

**Comment by t-oster** [comment]
well this belongs to #117 so I close this.
