### ISSUE TITLE
New API-names

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-core#189]
@hpk42 and me had the idea to rename the API-functions and to use a different prefix.

The currently used `mr` was chosen before the project got the name "Delta Chat" an is a little bit weired and is often pronounced as "Mister" which was not the initial intension - "mr" should just be an abbreviation of "**m**essenge**r**", however, to be honest, i have not thought much about this ... 

The idea is to use `dc` (for "Delta Chat") as a prefix.
Moreover, maybe it is more readable to separate the prefix from the object name by an underscore.

New API-names would be eg:

```
mrmailbox_t       => dc_mailbox_t      [alternatives: dc_t, deltachat_t, dc_context_t]
mrmailbox_new()   => dc_mailbox_new()  [alternatives: dc_new()]
...
mrchat_t          => dc_chat_t
mrchat_new()      => dc_chat_new()
...
mrchatlist_t      => dc_chatlist_t
mrchatlist_new()  => dc_chatlist_new()
...
mcontact_t        => dc_contact_t
mrcontact_new()   => dc_contact_new()
...
mrmsg_t           => dc_msg_t
mrmsg_new()       => dc_msg_new()
```

Files:

```
mrmailbox.h       => dc_mailbox.h
mrmailbox.c       => dc_mailbox.c
...
```

We could also remove the `mailbox` from the top-level object which would result in very handy names as `dc_new()`, dc_send_msg(), `dc.h`,  `dc_t` then. The last ones are maybe too short and already used [here and there](https://github.com/search?q=dc_t&type=Code), maybe we should use `deltachat.h` and `deltachat_t` instead.

For a transition period, we can make the old and the new names to work.

What do you think?

**Comment by hpk42** [comment]
unsurprisingly, i am +1 :)

**Comment by Ampli-fier** [comment]
What about `mrmr` then? No chance for 'Mister Messenger'? ;-)

New names sound good.

**Comment by r10s** [comment]
> Moreover, maybe it is more readable to separate the prefix from the object name by an underscore.

thinking it over, i would not add an underscore between the prefix and the object name, `dc_msg_get_chat_id(dc_msg_t*)` looks uneven imho. `dcmsg_get_chat_id(dcmsg_t)` is more clear and does not have the risk to clash with the top-level functions (eg. `dc_perform_idle()` is still fine if we would create an _perform_-object with an idle function - this function would read dcperform_idle() then) .

**Comment by t-oster** [comment]
should be done together with https://github.com/deltachat/deltachat-android/issues/305

**Comment by r10s** [comment]
> should be done together with deltachat/deltachat-android#305

well, #305 has more impact as it affects the users, the changes proposed here are only internal.

however, with the pr #197 we have the new prefix already today :)

- the api is also updated at https://deltachat.github.io/api/
- the files still have the old names, so, there is no need to update the makefiles 
- for a transitional period also the old mr-functions are available
