### ISSUE TITLE
Emails deleted/moved from INBOX on server, need also be removed from deltachat

### ISSUE THREAD

**Issue by testbird** [deltachat/deltachat-core#195]
To limit and keep the list of messages that did not approve for a chat tidy, when the messages are moved or deleted on the server (dealt with) by another MUA, they should also get removed from the "(..) Unapproved Emails" ("contact requests") #48 in deltachat.

**Comment by r10s** [comment]
thanks for the hint, i've added this to #52

**Comment by testbird** [comment]
Ok, just thought the clean-up would be good for a single-client as well.

**Comment by r10s** [comment]
for single-client (if delta is the only MUA) this is not needed. if there is any other app with access to the INBOX, this is already multi-client.

**Comment by r10s** [comment]
i agree to all points - therefore it is added to #52 :)

**Comment by testbird** [comment]
I can't tell which point in #52 is not about chat but about email (contact requests).

**Comment by testbird** [comment]
Reopen this?
https://github.com/deltachat/deltachat-core/issues/52 has been marked solved but there are still all old emails under "Emails" (contact requests) long after they were deleted or moved away on the server.

**Comment by testbird** [comment]
Removing those messages from the email view that got deleted on the server allows deltachat to be used by users that are actually cleaning up their INBOX (either in deltachat or on the server).

An additional (FIFO) displaying limit (500?) might be required for deltachat to work with huge INBOXes that are never cleaned up completely. (New issue?)

**Comment by r10s** [comment]
i think, we should open a more general issue wrt syncing. it's not only deleted contact requesets

**Comment by r10s** [comment]
did so: https://github.com/deltachat/deltachat-core/issues/644
