### ISSUE TITLE
Compile SQLite with secure_delete

### ISSUE THREAD

**Issue by link2xt** [deltachat/deltachat-core#196]
Latest Android enables secure_delete by default, but deltachat-core is using its own custom version of SQLite. SQLITE_SECURE_DELETE should be enabled manually during the build: https://sqlite.org/compile.html#secure_delete

Issue #194 is related because SQLCipher enables secure_delete since https://www.zetetic.net/blog/2012/5/24/sqlcipher-coreandroid-205-released.html

**Comment by r10s** [comment]
the compile-time switch defines only the default value.

it would be better and simpler to use the pragma `PRAGMA secure_delete=ON` (see https://sqlite.org/pragma.html#pragma_secure_delete) which would also works in environments where Delta Chat does not using a self-compiled sqlite-library but uses the system library. 

however, i think before enabling this, some more thinking about at-rest-encryption, threatening-models and so on may be needed.

**Comment by labdsf** [comment]
In any case, execuing `PRAGMA secure_delete=1` once for each database connection is better than not doing it.
