### ISSUE TITLE
Feature request: Greeting and Signature configurable, ideally per contact

### ISSUE THREAD

**Issue by 3screens2eyes** [deltachat/deltachat-core#20]
Hi, 

IMHO you do a good job already in extracting the real communication from an email.
To gain traction in the enterprise, though, it would be good to additionally also don the vestments of conventional emails, namely greeting and signature lines on sending a delta chat.
Ideally this could be defined per contact addressed, so as to differentiate professional and private chats.

regards,
-- 3screens2eyes

**Comment by r10s** [comment]
- The signature is editable since the last version.

- for per-contact-signatures, please refer to issue #25

**Comment by 3screens2eyes** [comment]
Actually, #25 seems to be about multiple accounts to send from.
What i meant was to be able to differentiate my .sig by address sent to.

**Comment by r10s** [comment]
Yes, but this still belongs to #25 in some way - if one creates multiple accounts, there will be different footers for them, too. I do not think, we will support different footers (which are called "status" now) for different users _without_ using different accounts.
