### ISSUE TITLE
check what happens if the user changes the configured E-Mail-Address

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-core#203]
check eg. what will happen to the Autocrypt key.

In the long way, changing the e-mail-address should work, however, for now, it would be acceptable not allowing to change it (the user has to re-install delta chat then)

however, what not should happen, is that it looks as if the address is changeable, but in practice, nothing works afterwards :)

**Comment by csb0730** [comment]
- If Autocrypt key is bind to an email address a new key has to be generated.
All other things I agree :+1:

**Comment by r10s** [comment]
see #221 for more details
