### ISSUE TITLE
allow for "+subaddressing"

### ISSUE THREAD

**Issue by testbird** [deltachat/deltachat-core#205]
(Taken from https://github.com/deltachat/deltachat-core/issues/202)

The + subaddresses are supported by many servers https://tools.ietf.org/html/rfc5233.

These single account address additions could probably just be striped by DC for autocrypt operations, or is that somehow insecure?

**Comment by r10s** [comment]
closing this for now here, of course, the discussion can go on in the new support forum at https://support.delta.chat
