### ISSUE TITLE
Messages not moved (from INBOX) when IMAP stream is lost

### ISSUE THREAD

**Issue by Ampli-fier** [deltachat/deltachat-core#213]
**Version info**: 

Delta Chat Core version 0.18.2

**Observation**:

In a situation, where the IMAP stream is lost, the flow to _download -> mark as seen -> send the read receipt -> move to DeltaChat_ folder is not completed.

In [this logcat](https://gist.github.com/Ampli-fier/d88c94c1be1d9d1fa9f9ec3a4967f5f9) the two messages (INBOX/626 & INBOX/628) were not moved to the DeltaChat folder and no Read Receipt was sent for these two messages. 

**Expected behaviour**:

Loosing the IMAP stream shall not interrupt the flow for new messages.

**Comment by r10s** [comment]
i think, we can close this for now as moving to the DeltaChat folder is currently not part of the core and, if re-added, this will probably completely different, see #422
