### ISSUE TITLE
Rework draft handling

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-core#214]
This issue is about making the draft functions more flexible as needed eg. by the signal-ui.

currently, we have three functions for handling draft texts:
[dc_set_text_draft()](https://deltachat.github.io/api/classdc__context__t.html#a2dcb54d63d73b547077ad4f980509ac0), [dc_chat_get_text_draft()](
https://deltachat.github.io/api/classdc__chat__t.html#a08e4bc816bdf6f7ce9aa61dd0a5bc924) and [dc_chat_get_draft_timestamp()](https://deltachat.github.io/api/classdc__chat__t.html#a15e1c501919bd73e6ee6a52a36c9fc0e). internally, the draft texts are saved in the chats table in a special column. there is no possibility to save eg. "image-drafts" or other things that the dc_msg_t object offers.

@karissa @angelo-fuchs i think the signal-codebase, at least for android, works in a way that _any_ message being composed can result in a draft (if the chat is left before the "send-button" is hit).

eg. if an image was selected for sending and the chat is left, this images becomes a "image-draft".
(~~also, signal allows adding text to images which is currently not possible in the core, however, this is another issue~~ EDIT: the core allows this meanwhile)

My suggestion would be to handle the draft by two very simple functions:

```
- void      dc_set_draft(dc_context_t*, int chat_id, dc_msg_t* msg);
- dc_msg_t* dc_get_draft(dc_context_t*, int chat_id);
```

- `dc_set_draft()` would accept any message object that could also be passed to `dc_send_msg()` and save it in the database for later usage
- `dc_get_draft()`  would re-create the message object from the database, the returned value can also be passed directly to `dc_send_msg()`
- set draft must be deleted explicitly by passing NULL as `msg`
- could be easily adapted to handle additional information (eg. the mentioned image description but also a reply-to field that [may be needed in the future](https://github.com/deltachat/deltachat-core/issues/125))
- internally, the draft would not be saved in additional rows of the chat-table but as a normal msg-record in the msg-table, with an `is_draft` flag or sth. like `hidden=draft`

please note that this proposal is not about saving the drafts to the IMAP-drafts-folder on the server, however, to improve multi-device-support, this could be added later and would probably not affect the api.

open questions:

- this proposal still supports only one draft per chat, however, in the normal, typical messenger, ui flow, this seems to be sufficient.

**Comment by angelo-fuchs** [comment]
> - set draft must be deleted explicitly by passing NULL as msg

I would suggest that dc_send_msg() also drops elements from the draft.
