### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by ralphtheninja** [deltachat/deltachat-core#217]
I'd like to be able to pass in my own data when creating the context, which later get called back in the handler, like below:

```c
uintptr_t my_delta_handler(dc_context_t* mailbox, int event, uintptr_t data1, uintptr_t data2, void *data3)
{
  int foo = *(int *)data3;
  return 0;
}

int foo = 3;
dc_context_t* context = dc_context_new(function, NULL, NULL, (void *)&foo); 
```

This is really powerful since it allows the calling library to pass _any_ custom application data which can then be used inside the event callback, without needing to store this globally (e.g. on file scope).

**Comment by r10s** [comment]
i think this is already possible using the 2nd parameter of [dc_context_new()](https://deltachat.github.io/api/classdc__context__t.html#a9d0f77a01382745e59492dda8509cf83). 

```
int foo = 3; // CAVE: should normally be sth. on the heap, not on the stack, see comment below
dc_context_t* context = dc_context_new(function, (void *)&foo, NULL);
```

you get back the data using [dc_get_user_data()](https://deltachat.github.io/api/classdc__context__t.html#a59f7a27ee13e3c8e3016bb56bcbe0d31) then:

```
uintptr_t my_delta_handler(dc_context_t* context, int event, uintptr_t data1, uintptr_t data2, void *data3)
{
  int foo = *(int *)dc_get_user_data(context);
  return 0;
}
```

You can call dc_get_user_data() anytime, not only in the callback function.

Comment: If you want to pass a pointer as user-data here, you have to make sure it is valid all the time dc_get_user_data() is called by your code. Any int on the stack usually isn't.
