### ISSUE TITLE
add a #define for switching between sequoia and netpgp

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-core#222]
either USE_SEQUOIA or USE_NETPGP can be defined in meson or somewhere else; the code will check for 
```
#if defined(USE_SEQUOIA)
  // call into the netpgp lib
#elif defined(USE_NETPGP)
  // call into the sequoia lib
#endif
```

only one of both must be defined, the unused parts must be undefined (_not_ defined to `0`)

**Comment by r10s** [comment]
a basic implementation is in https://github.com/teythoon/deltachat-core/tree/sequoia

**Comment by r10s** [comment]
before we can add a #define, we need to get **sequoia running** so that we can also test.

https://gitlab.com/sequoia-pgp/sequoia/blob/master/README.md gives some instrutions, basically i did:

- install packets as shown in README.md, purged `rustc` and `cargo` as they had the wrong version on my Ubuntu 16.04:
`$ sudo apt install git rustc cargo clang make pkg-config nettle-dev libssl-dev capnproto libsqlite3-dev`
`$ sudo apt purge rustc cargo nettle-dev`  # the system versions of these packets are too old for sequoia

- unpack the most recent nettle version from https://www.lysator.liu.se/~nisse/nettle/ to ~/libs/nettle-3.4 and execute the typical :
`$ ./configure`
`$ make`
`$ sudo make install`
after that, `pkg-config nettle --libs` shows `-L/usr/local/lib -lnettle` and `pkg-config nettle --cflags` shows `-I/usr/local/include`

- get the most recent rust version using
`$ curl https://sh.rustup.rs -sSf | sh` # command from rust-lang.org

- get sequoia from https://gitlab.com/sequoia-pgp/sequoia to ~/libs/sequoia and start the building of the library with just
`$ make`

this takes some time and then **fails on linking** with lots of undefined references to nettle, eg. nettle_dsa_signature_clear or nettle_get_secp_256r1 or nettle_des3_encrypt (just picked some random ones)

any hints how to fix this or how to get more information about the error are very welcome :)

**Comment by ralphtheninja** [comment]
> this takes some time and then fails on linking with lots of undefined references to nettle, eg. nettle_dsa_signature_clear or nettle_get_secp_256r1 or nettle_des3_encrypt (just picked some random ones)

Is there any way to see _which_ `nettle` that `sequoia` is trying to link with in that build step?

**Comment by r10s** [comment]
linker output: https://share.riseup.net/#57jzoFadVf9CdvNcH50NXA

**Comment by r10s** [comment]
output of `ldconfig -p | grep nettle`:
```
	libnettle.so.6 (libc6,x86-64) => /usr/local/lib/libnettle.so.6
	libnettle.so.6 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libnettle.so.6
	libnettle.so (libc6,x86-64) => /usr/local/lib/libnettle.so
```

**Comment by r10s** [comment]
background for linking nettle: https://www.lysator.liu.se/%7Enisse/nettle/nettle.html#Linking (thanks, @ralphtheninja)

**Comment by ralphtheninja** [comment]
@r10s I grabbed the first cc command from the log (and removed all .o and .rlib)

```
"cc"
"-Wl,--as-needed" "-Wl,-z,noexecstack" "-m64"
"-L" "/home/bpetersen/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib"
"-Wl,-z,relro,-z,now"
"-nodefaultlibs"
"-L" "/home/bpetersen/libs/sequoia/target/debug/deps"
"-L" "/home/bpetersen/libs/sequoia/target/debug/build/backtrace-sys-938b4f4f16f01df5/out"
"-L" "/home/bpetersen/libs/sequoia/target/debug/build/bzip2-sys-2265bd72802fb0c7/out"
"-L" "/home/bpetersen/libs/sequoia/target/debug/build/miniz-sys-0c1bdcb5eda41071/out"
"-L" "/usr/local/lib"
"-L" "/usr/local/lib"
"-L" "/home/bpetersen/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib"
"-Wl,--end-group" "/home/bpetersen/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcompiler_builtins-874d313336916306.rlib"
"-Wl,-Bdynamic"
"-l" "nettle"
"-l" "hogweed"
"-l" "gmp"
"-l" "util"
"-l" "util"
"-l" "dl"
"-l" "rt"
"-l" "pthread"
"-l" "pthread"
"-l" "gcc_s"
"-l" "c"
"-l" "m"
"-l" "rt"
"-l" "pthread"
"-l" "util"
"-l" "util"
```

It looks ok to me.

@r10s Can you do `nm` on the `libnettle.so` files you got from `ldconfig` and grep for the unresolved externals?

**Comment by r10s** [comment]
@ralphtheninja the output of `ldconfig -p | grep nettle` is
```
libnettle.so.6 (libc6,x86-64) => /usr/local/lib/libnettle.so.6
libnettle.so.6 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libnettle.so.6
libnettle.so (libc6,x86-64) => /usr/local/lib/libnettle.so
```

and the output of `nm /usr/local/lib/libnettle.so` is in https://gist.github.com/r10s/9b2aafadd425859a89c6c3b9941e4f25

i tries to search for a random missing unresoved external, `nettle_get_secp_384r1` - this seems not to be present in libnettle - but in libhogweed:

`ldconfig -p | grep hogweed` says:
```
libhogweed.so.4 (libc6,x86-64) => /usr/local/lib/libhogweed.so.4
libhogweed.so.4 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libhogweed.so.4
libhogweed.so (libc6,x86-64) => /usr/local/lib/libhogweed.so
```
and `nm /usr/local/lib/libhogweed.a` returns https://gist.github.com/r10s/4d9a38f50df8f1b7cca17e7e9bed2112

oto, compiling sequoia also complains about a missing `nettle_aes192_decrypt` which _is_ present in libnettle - when trusting the dump above.

i am confused.

**Comment by r10s** [comment]
okay, switch to ubutu 18.04 and, in general, building sequoia works now :)

**Comment by r10s** [comment]
building https://github.com/teythoon/deltachat-core/tree/sequoia finally also works by adding the static library from `sequoia/target/debug/ ` and `-Wl,--no-as-needed -ldl -lnettle -lhogweed -lgmp` as linker flags.

@ralphtheninja, all: thanks for help :)

**Comment by r10s** [comment]
in between, some other options wrt pgp library came up, eg. https://github.com/riboseinc/rnp/; closing this for now.
