### ISSUE TITLE
Consider building libsasl2 ourselves

### ISSUE THREAD

**Issue by ralphtheninja** [deltachat/deltachat-core#224]
Linking against the system version of `libsasl2` can sometimes be problematic. My current use case is simply trying to build `deltachat-core` on Travis, which we need in order to test `deltachat-node` properly. Apparently `libsasl2-dev` doesn't have a `.pc` file for Ubuntu 14.04 (which is what Travis uses) so resulting in problems when running `meson`:

![screenshot from 2018-07-25 14-14-20](https://user-images.githubusercontent.com/308049/43200224-1e5802a2-9015-11e8-806f-3816f04f24bf.png)

Full log here: https://travis-ci.org/ralphtheninja/deltachat-node/builds/408001419

A solution would be to pull in `libsasl2` into our source tree via e.g. a git submodule.

**Comment by r10s** [comment]
cc @flub @hpk42  :)

**Comment by flub** [comment]
heh, no worries.  i like being cc'd on github as otherwise i'm completely bankrupt on github notifications...

**Comment by r10s** [comment]
i've moved the source code of cyrussasl, libiconv, openssl from deltachat-android to deltachat-core, currently, they are referenced only by the android projects, but, it is a first step.

**Comment by ralphtheninja** [comment]
This is done.
