### ISSUE TITLE
Documentation links persistent?

### ISSUE THREAD

**Issue by ralphtheninja** [deltachat/deltachat-core#229]
Are urls to specific functions intact or will they change as the docs are updated?

Example: A link to `int dc_add_address_book()` https://deltachat.github.io/api/classdc__context__t.html#a4b5e52c5d45ee04923d61c37b9cb6498 

Will this persist or will the hash after `#` change?

If it will change, is it possible to configure `doxygen` to generate urls that are always the same? My use case is building docs for the node bindings where I want to link to the corresponding function in the core library.

**Comment by r10s** [comment]
not sure - and i did not find an option for this in the doxygen "Makefile" which is located here: https://github.com/deltachat/deltachat-core/blob/master/docs/Doxyfile

**Comment by r10s** [comment]
had a closer look at this:
- when i changed the function name, i got a different link
- when i changed the parameter names, i also got a different link
- adding whitespace did not change the link
- reverting all names resulted in the original link

so, the link seems to be a hash at least over function name and parameters which is probably okay for the given purpose - in fact, [the links are all there already](https://github.com/deltachat/deltachat-node#class-deltachat) :) - so i close this issue for now, feel free to re-open :)

**Comment by ralphtheninja** [comment]
> so, the link seems to be a hash at least over function name and parameters which is probably okay for the given purpose

Perfect!
