### ISSUE TITLE
FR: Proxy support

### ISSUE THREAD

**Issue by gerroon** [deltachat/deltachat-core#23]
Hi

It would be great if the app supports socks5/http proxy for connections.

thanks

**Comment by r10s** [comment]
I'll vote for this. 
But isn't this possible by a system setting?

**Comment by gerroon** [comment]
@r10s

Well you can put proxy in wireless settings but that is a system wide setting and also not all apps properly respect those settings so it not easy to figure out if the apps use the proxy or not. Also one might not want all apps to go through the same proxy.

**Comment by gerroon** [comment]
@r10s

Well you can put proxy in wireless settings but that is a system wide setting and also not all apps properly respect those settings so it not easy to figure out if the apps use the proxy or not. Also one might not want all apps to go through the same proxy.

**Comment by r10s** [comment]
Unless there are some volunteers working on this issue, for now, this is out of scope IMHO. However,  the idea stays available via https://github.com/deltachat/deltachat-android/wiki .
