### ISSUE TITLE
Possible to remove symlinks from deltachat-core/libs/libetpan/include/libetpan ?

### ISSUE THREAD

**Issue by ralphtheninja** [deltachat/deltachat-core#232]
We noticed something when trying to install `deltachat-node` from npm. Apparently, `npm` removes symlinks when generating a package tarball (during `npm publish`) so when you install `deltachat-node` you'll get the `deltachat-core` code but _without_ any symlinks.

This means that the _local_ `libetpan` will not be used, which in turn means you _must_ have `libetpan` installed on your system.

My question is if we can somehow solve this without using symlinks, since they aren't cross platform.

See https://github.com/deltachat/deltachat-node/issues/66 for some background.

**Comment by ralphtheninja** [comment]
cc @Jikstra

**Comment by ralphtheninja** [comment]
We should probably fix this to make it work on e.g. windows.

**Comment by r10s** [comment]
@ralphtheninja @Jikstra i think we can fix this as described in https://github.com/deltachat/deltachat-cli/issues/35#issuecomment-412787469

if there is nothing against from your side, i will do this change.

**Comment by r10s** [comment]
done with https://github.com/deltachat/deltachat-core/commit/e70475f34e06a3d871a57b96da95e3f28212d8af
