### ISSUE TITLE
Messages are not threaded for Gmail users. Missing In-Reply-To header.

### ISSUE THREAD

**Issue by valeriopaladino** [deltachat/deltachat-core#234]
Hello,

I noticed a strange behaviour when using Delta Chat with Gmail users: all messages sent by the Delta Chat client would create a new thread in the Gmail web interface, instead of being shown in the same thread as the message they were replying to.

During investigation, I noticed that messages sent by Delta Chat were missing the In-Reply-To header, and their References header only referenced the original message, while Gmail-sent messages had a References header containing all the messages in the thread:

Their messages:

    References: <Rf.1COkJJCcNkd@mr.thread> <Gr.LVxlmpkvGBp.HNu-vm71QOJ@mymailserver.com>
    In-Reply-To: <Gr.LVxlmpkvGBp.HNu-vm71QOJ@mymailserver.com>

My message, which replied to a previous one:

    Message-ID: <Gr.LVxlmpkvGBp.HNu-vm71QOJ@mymailserver.com>
    References: <Rf.1COkJJCcNkd@mr.thread>
    X-Mailer: Delta Chat 0.19.0 for Android
    Chat-Version: 1.0
    Chat-Predecessor: CACxaVBR_8w0B-+0ZM6P8gdFFNp2TdgfX5mgCegyhcAUArQLg=g@mail.gmail.com
    

Is this the desired behaviour? Note that the Evolution client shows my messages as replies to the first message, rather than new threads.

**Comment by valeriopaladino** [comment]
cc @r10s

**Comment by r10s** [comment]
hi @valeriopaladino thank you  for your post. currently, this is the "normal" behaviour, but it will probably be changed.
this issue might be a duplicate/extension of #72

**Comment by r10s** [comment]
also related: #131
