### ISSUE TITLE
proper "message shown" receipt info in groups 

### ISSUE THREAD

**Issue by testbird** [deltachat/deltachat-core#238]
Instead of just showing the second checkmark icon in outgoing messages after some unknown threshold of received receipts in groups, please prepend the second checkmark with the actual number of already received receipts.

After the message was shown to all (receipts have reached the number of group members as shown in the chat header) the complete presentation could be visualized with just the two checkmarks, just as in a one-to-one chat.

If straight forward, the contacts that already responded with a "message shown" receipt could be listed in the detailed message info page.

**Comment by r10s** [comment]
i think, for now, we'll just leave the second checkmark. 
feel free to continue discussion in the forum :)
