### ISSUE TITLE
Provide a Signature to let people know what DC is

### ISSUE THREAD

**Issue by t-oster** [deltachat/deltachat-core#242]
Sometimes I start writing my E-Mail Contacts in DeltaChat, just because the conversation gets more IM like than Mail like (shorer, without formal greetings etc).
It would be nice if DC adds something like `sent with <link>DeltaChat</link>` at the bottom of the E-Mail (probably configurable), which would show up in traditional MUAs, but gets removed from DC if the other party already uses DC.

This was I would not need to explain why my mails start looking different and some people may become curious and this way DC may become wider known faster.

**Comment by r10s** [comment]
how would this differ from the current "footer"?

- by default, we add a text as `Sent with my Delta Chat Messenger: https://delta.chat` as the footer of outgoing mails (divided by `-- ` from the text).

- the footer is editable on android (see _Settings > Name and status_)

- the footer is shown in normal MUAs but not shown in Delta Chat (however, there is a [rough idea](https://github.com/deltachat/deltachat-android/issues/97#issuecomment-315355069) to use the text as a kind of "status" text and display it in the profile in the future).

@ralphtheninja internally, the footer can be configured by `dc_set_config(context, "selfstatus", "<text to use>")`

**Comment by testbird** [comment]
I guess it was the usual problem: Not naming somthing (the footer) by its descriptive name.

Instead by something else, like the status, which is just a detail that my be placed in the email footer.

(Ha, this reminded me of https://github.com/deltachat/deltachat-android/issues/175)

**Comment by r10s** [comment]
not sure, that people who are using messengers and never used mail before, know what a _footer_ is ...

**Comment by testbird** [comment]
Hm, yes but don't think users are afraid of learning (if they actually go looking into the settings).

So in such cases maybe just use the proper name "email signature" for the setting or field, and in the UI have something like "Name or status added as footer to outgoing email messages."?

**Comment by testbird** [comment]
(@r10s What happened to your name in the email notifications, why is it all lower case now?)

**Comment by testbird** [comment]
Could it be that you might have initially been trying to hide "email things" away, a little too much.
To much may be when things are not directly recognizable by regular email users.
I believe it should be very well possible to support both, email as well as messenger users.

**Comment by t-oster** [comment]
I just overlooked it, nevermind
