### ISSUE TITLE
unified QR mode to "scan and show" (two-way)

### ISSUE THREAD

**Issue by testbird** [deltachat/deltachat-core#243]
Why did nobody of us think of turning on the camera, and displaying the QR at the same time?
(Display the QR code icon in the the camera view.)

That could actually be all that's needed to allow an easy and intuitive two-way check.
Even without any need for the user to explicitly set the device to displaying or scanning.

And then, only optionally start sending background messages, i.e. only if the user closes the "show and scan mode" and selects something like "Send contact setup message to [scanned address]. (Useful if scanning a print and the other side could not scan your QR in return.)"

**Comment by r10s** [comment]
holding two phones face-to-face?
iirc, we thought about this some time ago but the handling is not that great as you cannot really see if the camera gets an sharp image of the QR code (the other phone who wants to scan is in the view).
moreover, this won't work well eg. with desktop (desktop apps can always display a QR code but cannot always scan one).

**Comment by testbird** [comment]
Not face-to-face.

The idea is not to replace the background messaging, it is just to

 1) Display the QR code in the scannig screen, for testing it may be possible to just place the QR in the title bar of the camera scanner view (if the title bar gets larger with a larger image). 
```
 ----------
| <-       |
|    QR    |
|          |
|----------|
|          |
|   video  |
|          |
|          |
 ----------
```
  2) Allow to scan in both ways by waiting after a successful scan.

One would then scan the devices in the same way as now, but should be able to do it in both ways without having to decide in which direction, or who scans first, beforehand.

After successfully scanning a QR, the screen should only change, e.g. the camera screen closes, and the device continues to show the QR (to continue to allow scanning by the other party in return) and informs the user --replacing the lower display part with the camera (video ) view-- with some text and a button:

```
                      Scanned: <name and address>
                   Now let the contact scan your QR.
                              Or press:
                    [Send contact request message]

```

So in case it is not possible to scan in both ways (one after the other), as in your example if it is not possible to hold the phone in front of the desktop cam, it would still be possible to press the button and send a contact request instead.

But the two-way process would even work without relying on any network connection.

**Comment by r10s** [comment]
ah, i see, showing QR-Code and Scanner on the same activity.
I think signal does this (more or less, at least it is very simple to switch).

**Comment by testbird** [comment]
Ok it's actually a pretty obvious way for two-way OOB scanning. Showing both at the same time even makes any switching obsolete.

(Edited the success message above.)

**Comment by testbird** [comment]
With some optimizations there could even be a nice way to support exchanging contact data in a group.

Maybe by not turning of the scanner, and for example taking turns to go around and let one's QR getting scanned in a circle (1-to-n until n-to-n is reached).

**Comment by r10s** [comment]
to keep things open to a broader audience, in future, we should move such discussions to the new forum at https://support.delta.chat which is better for higher-level discussions
