### ISSUE TITLE
Yandex SMTP login fails

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-core#245]
reported at https://github.com/deltachat/deltachat-android/issues/377 be is better located here in deltachat-core

**Comment by r10s** [comment]
i have not re-checked this, on by last checks, some months ago, yandex was fine, see also https://github.com/deltachat/deltachat-core/wiki/Provider-overview

**Comment by saddy001** [comment]
May there be a difference between yandex.com and yandex.ru?

**Comment by r10s** [comment]
good point. have you test both?

**Comment by saddy001** [comment]
I only tested .com

**Comment by saddy001** [comment]
Every setting is set to automatic. I also tested every possible combination of STARTTLS and SSL in both security options, neither works.

**Comment by r10s** [comment]
hm, just tried a gain with a fresh https://yandex.com/ account and a fresh Delta Chat 0.20.0 installation from F-Droid (was using the CLI-program above) - no problems, neither sending nor receiving. i also know from others using yandex.
can you try to create another https://yandex.com/ account and try over? might be there is a problem with a special account. another thing that may help is to re-install delta chat.

**Comment by saddy001** [comment]
I did a reinstall, same error. I disabled and re-enabled IMAP in yandex settings, same error. I put in all settings manually equal to Thunderbird, same error. Actually I'm too lazy to create another account.

**Comment by ralphtheninja** [comment]
@saddy001 This seems to be just a test account? Mind sharing the authentication details so we can try and reproduce?

**Comment by r10s** [comment]
we cannot progress on this without further information or test accounts. would also be interesting, if desktop or android-dev works, however, testing yandex again, seems to work, also there are no other reports so i think we should close this for now.
