### ISSUE TITLE
keep config parameters in sync if dc_configure() fails

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-core#246]
a typical configuration process is

```
dc_set_config(context, "addr", "alice@example.org"); // use some real test credentials here
dc_set_config(context, "mail_pw", "***");
dc_configure(context);
```

what `dc_configure()` does is the following:
- reads `addr`, `mail_pw` etc. from the database
- fills gaps in the setup (missing ports, user names, etc.) using eg. autoconfigure, autodiscover, defaults and testing
- if a working configuration was found, this is saved completely as WORKING, so that subsequent connects can use the correct parameters right away

this is fine on the first configuration, however, if a subsequent configuration _fails_, eg. `mail_server` may not match the WORKING one - this is no problem internally, however, typically UI implementation may want to show a dialog with the current parameters and there is no way to get them after dc_configure() failed one time (again the lib as such is still working)

solutions for this would be:
1. tell the UI just not to _read_ the `addr` etc.
2. pass all parameters directly to dc_configure()
3. reset  `addr` etc. to WORKING if dc_configure() fails and document this

=> 1. would have the disadvantage that there is no way to get the configuration from the lib, the UI would need to track the values on its own; 2. seems to be the clearest approach, however, it will make bindings etc. more complicated. also there will be functions as get_whole_config() needed which would make the whole interface more complex.

@ralphtheninja so, i would fo for 3. which does not require large changes and keeps things simple and the get/set straight-forward from the view of the UI.

**Comment by ralphtheninja** [comment]
I'm a bit slow, I don't understand the problem we are trying to solve. Correct me if I'm wrong.

1. User (and application) inputs `addr` and `mail_pw` (and maybe extra parameters, e.g. `mail_server`)
2. `dc_configure()` is called and configures correctly, saves that working state as `WORKING`
3. Some other time _something_ in 1. has changed
4. `dc_configure()` fails for _some reason_ (invalid password, invalid user, invalid server, whatever)
5. What to do now?

**Comment by r10s** [comment]
what, if after 4. the UI wants to show a dialog with the current configuration - eg. to let the user edit some things. typically, the UI will init the fields with the values from dc_get_config() - but as failed in 4. this will just return the last non-working values set by the UI. after the failure in 4. there is currently no way to get the WORKING configuration back from the database.

imaging a typical dialog:

```
class ConfigureDialog {
  onDialogCreate() {
   initTextField(TEXT_INPUT1, dc_get_config(context, "addr"))
   initTextField(TEXT_INPUT2, dc_get_config(context, "mail_pw"))
  }

  onConfigureClicked() {
    dc_set_config(context, "addr", getTextFieldValue(TEXT_INPUT1));
    dc_set_config(context, "mail_pw", getTextFieldValue(TEXT_INPUT2));
    dc_configure()
  }

  onCancelClicked() {
    // nothing to do, if dc_configure() fails, the old configuration is used
  }
}
```

if dc_configure() fails here, the next time (maybe the next day or so) the dialog is opened, the wrong values are shown the in text field - maybe just because of a typo or a user playing around.

resetting the values on failure will make such dialogs work as expected.

**Comment by r10s** [comment]
@ralphtheninja i am sure you are not slow, but i have to try harder to explain things :)

**Comment by ralphtheninja** [comment]
Ok, I understand better now. What if `dc_configure()` fails for a reason that's _not_ related to the actual configuration? Maybe the imap server was down (just thinking out loud here, don't know if it's possible or not) or something else happened that made `dc_configure()` fail.

**Comment by r10s** [comment]
would be the same then - things set with dc_set_config() would be reset to WORKING (but really only on `dc_configure()` - on subsequent connections this is no issue).

i think we should see things given to dc_set_config() before calling dc_configure() as parameters for dc_configure() - you have to set the parameters just be fore calling dc_configure().

**Comment by hpk42** [comment]
Isn't there some distinction already between "entered" config data and "in-use" config data? I think it's good to keep track of what was actually set via "set_config".

**Comment by r10s** [comment]
> I think it's good to keep track of what was actually set via "set_config".

yes, but this is not the problem.

- assume, bob has configured `bob@example.org` successfully.
- some day later, he plays around in the settings and enters `bobby@example.org` and clicks "OK" which fails as dc_configure() fails because of the wrong email address.
- he then leaves the configuration dialog.

now, while everything works still fine and `bob@example.org` is still used as the existing successful configuration, when bob enters the settings dialog again, this will show `bobby@example.org` as this was set but not successfully configured.

solution for a way out of this are described above as 1. to 3. 
the simplest solution would be 3. - reset to configured values if dc_configure() fails. for a ui, this would typically be just fine as the entry fields etc. "on screen" have their own settings that are just passed to dc_set_config() befire dc_configure() is called.

maybe it's clearer, if we regard dc_set_config(addr/mail_pw/mail_server/etc.) as _parameters_ to dc_configure().

**Comment by Ampli-fier** [comment]
> now, while everything works still fine and bob@example.org is still used as the existing successful configuration

This sounds unlogic. Delta Chat should stop using old values, as soon as the user typed in new settings and pressed "the dc_configure-button".

**Comment by r10s** [comment]
> Delta Chat should stop using old values, as soon as the user typed in new settings and pressed "the dc_configure-button".

even if the new configuration is not working? not sure about this.

**Comment by Ampli-fier** [comment]
Not even then :)

As it is currently, `(is_)configured` would **always** be 1 after the first successful connect.
Give the flag a chance and set it to 0 after a subsequent dc_configure that fails. 

This would be the case also, with a very first failed dc_configure attempt.

Keep the not working values in the DB. They might be wrong, or as Ralph pointed out it can be just a temporary problem with connection, ... Or one used a wrong password and need to look it up later. Then it would make sense to keep the typed/selected values and give the user a quick possibility to eg. correct or try again.

**Comment by hpk42** [comment]
On Mon, Oct 08, 2018 at 21:15 +0000, Ampli-fier wrote:
> Not even then :)
> 
> As it is currently, `(is_)configured` would **always** be 1 after the first successful connect.
> Give the flag a chance and set it to 0 after a subsequent dc_configure that fails. 
> 
> This would be the case also, with a very first failed dc_configure attempt.
> 
> Keep the not working values in the DB. They might be wrong, or as Ralph pointed out it can be just a temporary problem with connection, ... Or one used a wrong password and need to look it up later. Then it would make sense to keep the typed/selected values and give the user a quick possibility to eg. correct or try again.

mostly agree.  why would one ever go to the "config-edit" screen after
one has successfully connected once?  For example because there was a password
reset -- or maybe some SSL change from the provider. If i am fiddling with
the config-settings i surely want to have the shown values be the one that
delta currently uses, kind of always.

**Comment by r10s** [comment]
>  why would one ever go to the "config-edit" screen after one has successfully connected once?

people do this :)

but, yes, setting configured=0 if dc_configure() fails may solve the initial problem.

however: what if one goes to the config-edit, maybe just to look sth. up, not doing any changes but hitting OK which starts the configuration. if there is a _temporary problem with connection_ then, the user is lost a bit. he has to hit the OK button again when there is network again, delta won't catch this up automatically.

i think this is a rather real scenario: people go through dialogs all the time, imho, eg if they have nothing to do in the train ... one OK hit without having network (we're in a train ...) and the connection will be lost.

**Comment by r10s** [comment]
finally, i think, maybe it is also fine to solve this on ui-side.
if a configuration change is not working, the ui can rather easily re-set the `addr`, `mail_pw` etc. to the values used before the user typed sth. in that does not work.

if would suggest to add a line to the documentation for dc_configure() and close this issue without code changes then.
