### ISSUE TITLE
show QR-Code and Scanner on same activity (enable scanning in both-ways)

### ISSUE THREAD

**Issue by testbird** [deltachat/deltachat-core#247]
The current QR scanning lab feature introduces multiple UI elements and requires to decide who shows and who scans the QR-Code, beforehand, and it requires a network provider, network protocol, and enabling silent background messaging functions. It is therefore a lab feature that can and should not be released to users by default before completely scrutinized.

However, two small modifications to the current scanning process could already **also** allow exchanging contact data and fingerprints in both ways, one after the other, without needing to expose any secret challenges or background messaging channels on the network:

* Show the own QR-Code during QR scanning.
* Keep the scanner running after a successful scan, to allow further scans (by the other side or in a group).

This activity mode is the most straight-forward approach for an out-of-band contact setup that is based on the established method of exchanging public fingerprints. As it does not involve any new protocols, this method to scan new contacts may readily be released to the users.

**Comment by testbird** [comment]
There were issues about contact verification before, but not kept open with references to discussing the experimental and controversial one-way and cross-channel, contact setup lab feature that can be enabled in advanced settings.

https://github.com/deltachat/deltachat-core/issues/75
https://github.com/deltachat/deltachat-core/issues/168
https://github.com/deltachat/deltachat-core/issues/243
https://github.com/deltachat/deltachat-android/issues/348

The experimental method can and should continue to strive to proof its validity, compared to the two-way (person-to-person) OOB contact setup, for setting up contacts based on print-outs (e.g. business cards). However, it does not provide any established contact setup mechanism to regular users.

Nevertheless, the already implemented scanning activity can be improved with the two modifications above, and readily released to users. They do not require to wait for further review results about the lab experiments, or adding anything to deltachats default network attack surface.

**Comment by testbird** [comment]
(exemplification from #243:)

The idea here is not scanning face-to-face.

The idea is not to replace the background messaging, it is just display the QR code within the scannig screen. For testing it may be possible to just place the QR in the title bar of the camera scanner view (if the title bar gets larger with a larger image).  And to keep scanning after a successful scan.
```
 ----------
| <-       |
|    QR    |
|          |
|----------|
|          |
|   video  |
|          |
|          |
 ----------
```

One would then scan the devices in the same way as now, but should be able to do it in both ways without having to decide in which direction, or who scans first, beforehand.

The experimental one-way, cross-channel contact setup method could be integrated by an option.

After a successful scan a QR, the screen could additionally show:

```
                      Scanned: <name and address>
                   Now let that contact scan your QR.
                        If that's impossible:
                    [Send a contact request message]

                           [Done scanning]
```

So in case it is not possible to scan in both ways (one after the other), as in your example if it is not possible to hold the phone in front of the desktop cam, it would still be possible to press the button and send a contact request instead.

**Comment by r10s** [comment]
to keep things open to a broader audience, in future, we should move such discussions to the new forum at https://support.delta.chat which is better for higher-level discussions.

this will also keep the issue tracker free for bugs and concrete things to do :)

**Comment by r10s** [comment]
cmp #243

**Comment by r10s** [comment]
you can log in there with your  github account :)

**Comment by testbird** [comment]
There seems to be a problem with the forum, I still did not get an activation email since yesterday, even after a re-send and checking the spam of course.

**Comment by ralphtheninja** [comment]
@testbird Did you activate using your github account or did you register with your email?

**Comment by testbird** [comment]
It was with github as r10s suggested, an OAuth application notice from github did arrive but nothing from the forum.

**Comment by r10s** [comment]
@testbird i activated you account manually, it should work now.
did you created the account via github or via mail?

**Comment by lefherz** [comment]
weird - I didn't think that a confirmation email was even necessary for login with github. the login is already confirmed by clicking "authorize" in github, isn't it? the only reason for e-mail confirmation is to ensure that the user has access to the e-mail address. If you click "authorize" in github, this should already be confirmed. the rest of the oauth flow does not require user interaction...

**Comment by testbird** [comment]
Indeed, it worked now, but I don't know if it would have worked without manual activation. (After the first login I saw the notification page about the activation email, and just waited for it without trying anything further with the forum.)

**Comment by r10s** [comment]
discussion can be continued at https://support.delta.chat/t/release-basic-qr-code-contact-scanning-feature/44 , thanks @testbird  - moving higher level discussions away from github also has the advantage that it will be easier to switch the provider one day in the future :)

**Comment by r10s** [comment]
@lefherz wrt email confirmation: i just tested it to create a new account for somebody@b44t.com and got the confirmation mail

**Comment by lefherz** [comment]
perfect :)

**Comment by r10s** [comment]
:)
