### ISSUE TITLE
FR: Multiple accounts/mailboxes

### ISSUE THREAD

**Issue by gerroon** [deltachat/deltachat-core#25]
Hi

It looks like DC can set set only one mailbox at the moment. It would be nice if we could set more than one mailbox/account to be able to utilize mutliple email adresses.

thanks

**Comment by kollokollo** [comment]
Yes, that would be great. My friends are totally confused that they now have to use a different email address for the chats than they used to (the used one of my other mail addresses).

**Comment by r10s** [comment]
see also https://github.com/deltachat/deltachat-android/issues/18

**Comment by mbeko** [comment]
I frequently use two mail accounts and would have the same problem as kollokollo if I chatted with all of my contacts from the one account I chose for Delta Chat.

So this blocks my usage of Delta Chat with a large part of my friends. @r10s, you mentioned this feature is already planned. If it is supposed to be availabe only further in the future, can I help to speed up its development?

**Comment by testbird** [comment]
> can I help to speed up its development?

By working on pull requests, you might sure be able to speed up development.

**Comment by r10s** [comment]
> the core already supports multiple accounts

for this reason, i close this issue and re-use the android one, see https://github.com/deltachat/deltachat-android/issues/18

**Comment by mbeko** [comment]
Thank you for the explanation! So I'll look into the other issues and try to handle those which seem most important for a 1.0 release. Are they highlighted somehow or should I go by my own judgement?

**Comment by r10s** [comment]
we have a android-1.0-playstore-milestone here:
https://github.com/deltachat/deltachat-android/milestones/1

and a core-1.0-milestone here:
https://github.com/deltachat/deltachat-core/milestone/1

i think the most "important" issues are in the core currently eg. auth problems with some servers, background fetch and so on.

feel also free to contact me directly on r10s at b44t.com or on IRC #deltachat

**Comment by mbeko** [comment]
I'll do, thanks a lot!

**Comment by testbird** [comment]
There are also two wiki pages that reference relevant issues.

One is about very basic fundamental IMAP operations, which unfortunately currently make deltachat only usable for a very limited set of users (depends on their server implementation).

And the other wiki page is about making deltachat usable for multiple different identified use-cases.

https://github.com/deltachat/deltachat-core/wiki/IMAP-strategy
https://github.com/deltachat/deltachat-core/wiki/Use-Cases
