### ISSUE TITLE
not identifyable incoming emails

### ISSUE THREAD

**Issue by testbird** [deltachat/deltachat-core#251]
Neither the message nor in the message info contains the full email address of the sender.

That makes it quite impossible to be sure about the sender, and when the user supplied (name) part that is shown is generic, the message can't be associated to anybody really.

The simplest thing to solve the problem for the incoming emails ( old "contact requests") seems to be to just show the complete `Sender Name <email@address>` in the messages.

**Comment by r10s** [comment]
clicking on the round "user avatar" beside the message bubble shows information about the user - including the e-mail-address.

we may think about improving the message info, however, i think for now the issue, that emails are "not identifyable" is solved.

**Comment by testbird** [comment]
Ah yes, thanks that is actually is a workaround.

But I guess new users will likely have the same problem. This could be another of those cases where fixing for once is easier and faster than dealing with issues and user's problems.

(And if the message is formatted in the -core, that small change would actually benefit all frontends.)

**Comment by r10s** [comment]
yes, you're right. i've added the sender unconditionally (in fact it was always added when _no_ avatar was displayed)

**Comment by testbird** [comment]
Great. :)

(Ha ha, and I was scratching my head who could have send me that wrongly encrypted email (other issue you just fixed) ... only to find out with this issue, it was my fault accidentally :)
