### ISSUE TITLE
copy outgoing files to blob directory

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-core#256]
currently, files (images/audio/videos etc.) attached to _outgoing_ messages are _not_ copied automatically to the internal blob-directory.

while this saves some mb of space and was the simples approach to get things running, this has some disadvantages:
- the user may delete the original file - after that, Delta can no longer display eg. a sent image
- the file may be replaced by _another_ file - for images, Delta would display the _wrong_ file then
- the user cannot forward messages where the original data was deleted

so, the idea is to let the core copy the file before sending.

this won't affect bindings, the core can just do so. but i would suggest an additional event that is emmited after the file is copied - just in case the UI want to delete the file (eg. shrinked or edited images or so). the event could be DC_EVENT_FILE_COPIED(data1=path). the event would be just a hint and it will be okay just to ignore it.

all this only affects _outgoing_ files - _incoming_ files are already placed in the blob directory.

**Comment by ralphtheninja** [comment]
This is also true for chat profile images. Just fyi.
