### ISSUE TITLE
Suddenly, other emails addresses are added to the chat (without my assistance)

### ISSUE THREAD

**Issue by mario98** [deltachat/deltachat-core#26]
Hi,

I have a "t-online" email account which I use for Delta Chat. Over night, I received an email from a "gmail" account. I have not added this gmail account to Delta Chat before. However, I still got a Delta Chat notification and this address was suddenly added to the chat list, along with two other random email addresses which were present in my inbox (but not in Delta Chat).

Android L, Delta Chat 0.1.36 from F-Droid

**Comment by kskarthik** [comment]
Chat list or Mailbox? Please clarify. Screenshot would also be helpful...

**Comment by mario98** [comment]
Email addresses from emails which were present in my inbox (not chat list) were suddenly added to my chat lis. Is it clear now?

**Comment by mario98** [comment]
It happened multiple times again, with different email hosters. What I observed is that it mostly happens when I send someone an email (via. my PC). Then, once DeltaChat seems to think I automatically want this address to be added as chat. But that's not what I want.

**Comment by r10s** [comment]
Is it the following scenario?

- `You` send a message to `Person A`
- `Person A` answers to you and `Person C`
- Delta Chat now assumes, messages from `Person C` are wanted are are no spam and shows them up automatically.

We think, this is true in most cases. If not, you can block `Person C` and won't get messages again.

**Comment by r10s** [comment]
And: If you contacted a person on another device (PC), messages from this contact are assumed to be wanted.

If not, block the contact in Delta Chat or use a different e-mail-address for Delta.

**Comment by mario98** [comment]
The scenario is the following:

`I` send a message to `Person A` (who ist not listed in the chat)
`Person A` answers `me`
Delta Chat now adds `Person A` to the chat list automatically.

In my case, I use a shared email account for both Delta Chat and my regular private emails. Adding everyone whom I send a message is not what I want. Maybe you can add an option to disable this behavior.

**Comment by r10s** [comment]
Okay, this behavior is by design, messages from contacts you contacted _on any device_ will appear in Delta Chat. Same for messages from contacts contacted by a contact of you.

If you do not want to pop up these messages in Delta Chat, you can block them or use a separate account.

An option, to allow only messages from manually added contacts may be useful in some cases; any commits targeting this issue are welcome.

**Comment by r10s** [comment]
I've added this issue to the FAQs: http://deltachat.local/en/help#which-messages-do-appear-in-delta-chat

**Comment by Ampli-fier** [comment]
I received several Mails from known addresses (Contacts in my phone book), but they all appeared in Contact requests, not in a chat. I opened issue #32.
