### ISSUE TITLE
"lost messages" due to user deleting annoying "email notifications"

### ISSUE THREAD

**Issue by testbird** [deltachat/deltachat-core#263]
Found out about another way how messages can get lost.

The user was thinking to just delete email notifications about new deltachat messages in the INBOX, and was not aware to delete the actual deltachat messages before they were picked up by deltachat.

Switching to "AltMarkMove" scheme by default (and thus silencing annoying chat notifications in classic MUAs) should also help here (the scheme is needed anyway for multi-client syncing without support for two parallel IMAP-push connections). AltMarkMove is the slightly altered scheme of immediately marking chat messages as "seen" in the the INBOX by deltachat-core (and optionally additional server rules) and instead move the messages to the email chat folder when shown to the user . See https://github.com/deltachat/deltachat-core/wiki/IMAP-strategy#principles

PS: I have no idea were to insert the github wiki page under support.delta.chat, could someone please move a WIKI page as an example or give an example how it's done?

**Comment by r10s** [comment]
> PS: I have no idea were to insert the github wiki page under support.delta.chat, could someone please move a WIKI page as an example or give an example how it's done?

just add a normal post to the forum. any moderator or admin can make it a wiki then (if you want you post be edited by others - you can also leave it as a normal post that can be discussed as usual then).
more about discourse wiki-posts: https://meta.discourse.org/t/what-is-a-wiki-post/30801.
however, this is not urgent. we just do not want to encourage the github-wiki to be used even more.

**Comment by r10s** [comment]
on topic: i do not really get what this issue is about.

if another mua cannot decrypt mails, there is always a risk that the user will delete the wrong mails.
however, currently, read receipts are not encrypted at all.

**Comment by testbird** [comment]
The user had the notion that the deltachat messenger worked independently and she was getting two messages, one in deltachat and one as email, like the notifications of an online forum. So she just deleted emails as they popped up in the email app.

That's why I thought avoiding to let all chat messages pop up in email clients by default (like with AltMarkMove) could be one part of the solution, the other part could be to foster awareness that deltachat is just a email chat client. https://github.com/deltachat/deltachat-android/issues/368

**Comment by r10s** [comment]
> The user had the notion that the deltachat messenger worked independently 

okay, such misunderstanding are handled better by the single-folder approach in the future; esp. with dedicated accounts.

closing this for now as the context is different in between.

**Comment by testbird** [comment]
Impelling users to create new accounts, instead of touting the email compatibility and silencing current chat messages in the INBOX as "seen" for classic email clients, actually seems more likely to me to further complicate things by transfering the problem to your contacts...

What address? Can't find that file, can you send it to my email again? But I just wrote you an email.
