### ISSUE TITLE
Messages sending may fail on poor network connection

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-core#265]
@MMurzik reported at https://github.com/deltachat/deltachat-android/issues/386

> Before version 0.20.0 if a message was sent and connection to the mail server broke due to poor internet connectivity, Delta Chat would be sending this message over and over again, so it would definitely be delivered sooner or later, when connectivity improves.
Now, with the new "function" in version 0.20.0 to give up sending after a number of retries, reliable delivery of messages on poor connection is no more possible. When the mail server is inaccessible for some time (e.g. on a subway, or at the countryside, or even in flight mode), Delta Chat simply gives up sending these messages. That makes me constantly re-check if all messages were sent, and if not re-send it manually. It is inconvinient. And before version 0.20.0 I can simply send a message, forget about it, and to be sure that it will be delivered 100%
Please add option in settings to restore old behavior of Delta Chat to try sending unsent messages indefinite number of times. Thank you.

i moved this here as it is related to deltachat-core, not android.

the reason for not just "endless trying over and over" was avoiding excessive data consumption. in general, Delta Chat _should_ retry if it fails and the network is in "disconnected" state. however, of course there may be bugs and this may need some more research :)

related: [Size limit ends in endless upload #102](https://github.com/deltachat/deltachat-android/issues/102#issuecomment-404325534)

**Comment by r10s** [comment]
in general, Delta Chat should not _simply_ give up sending. On performing jobs as eg. sending a message roughly the following is done:

1. TRY-TO-SEND
2. if this fails, RECONNECT at once and TRY-TO-SEND again. This catches eg. disconnections on server-side.
3. if this also fails, increase DC_PARAM_TIMES by one _if_ we're online (else the try is not counted)
4. if DC_PARAM_TIMES < 3 then wait a moment and try over with 1.
5. else ABORT-JOB

the logic that should achieve this is here: https://github.com/deltachat/deltachat-core/blob/master/src/dc_job.c#L623 - maybe there are errors in it - any help and suggestions for improving are welcome :)

**Comment by csb0730** [comment]
1. If a msg is not too big to send dc should try sending a msg until its send in a bigger interval .
2. Give user a possibility to start sending process again.
3. Maybe we would have in future a possibility to go offline manually, dc could try again all failed ones after going online again.

**Comment by testbird** [comment]
The trick seems to be to only abort after permanent errors (https://www.iana.org/assignments/smtp-enhanced-status-codes/smtp-enhanced-status-codes.xhtml).

In any case (permanent or transient errrors) it should be possible to manually delete the message showing the failure, and to manually trigger a retry.

**Comment by csb0730** [comment]
See here too:
#https://github.com/deltachat/deltachat-android/issues/393
