### ISSUE TITLE
expose is_smtp_connected|is_imap_connected

### ISSUE THREAD

**Issue by hpk42** [deltachat/deltachat-core#268]
While hacking on the python bindings i noticed that i'd like to call ``is_smtp|imap_connected`` but this is not exposed in deltachat.h and it uses ``dc_smtp|imap_t`` structs which are also not exposed if i see it correctly.  Could we get a top-level API that just takes a ``dc_context_t*``?  I think there is a 1:1 reference relation between context and smtp|imap structs so it doesn't semantically change much.

If changing the signature of the two is_*_connected functions is not workable, i am also fine with new functions ("dc_get_smtp_status" -> 0: no connection, 1: connection, 2: auth/fully-operable) and the respective imap parts.  

grateful for a PR either way as i want to continue writing a "setup two live accounts, send and receive messages between them" functional test.

**Comment by r10s** [comment]
i would leave the `dc_smtp_is_connected(dc_smtp_t*)` and `dc_imap_is_connected(dc_imap_t*)` as they are now - `dc_imap_t` and `dc_smtp_t` are independent from `dc_context_t` (there are only dependencies for logging), so, these function have their purpose.

but we can easily add `dc_is_smtp_connected(dc_context_t*)` and a  `dc_is_imap_connected(dc_context_t*)` functions. however, the suggested tri-state is not easily doable - if a connection did not get auth/fully-operable state, it is not treated as being connected. if the connection is lost, everything is lost and a complete reconnect is done.

so, i would just forward the values from `dc_smtp_is_connected(dc_smtp_t*)` and `dc_imap_is_connected(dc_imap_t*)`.

@hpk42 doing this now.

**Comment by hpk42** [comment]
Hum, after reading your PR's docstrings i am wondering if it's a good idea to have these top level funcitons.
Going to try rather figuring things out from events, i think.  But I'd like to have clearer events like "DC_EVENT_IMAP_CONNECTED" "DC_EVENT_IMAP_DISCONNECTED" (and the same for smtp). with NULL DATA1/DATA2 for now.  Is that as easily possible as was #PR269 ?

**Comment by r10s** [comment]
i can easily send DC_EVENT_IMAP_CONNECTED and DC_EVENT_SMTP_CONNECTED, however, for sending DC_EVENT_IMAP_DISCONNECTED, there is no nice logic.

however, in practice, a DISCONNECT is always followed directly by the attempt to reconnect.

maybe we can send the state of a connect/reconnect attempt just by an event.
sth. like DC_EVENT_IMAP_STATE_UPDATE data1=connected(1)/failed(0).
this would also rather simple.

wrt the docstrings: i would write the same to the DC_EVENT_IMAP_STATE_UPDATE events: they are no guarantee something will work :)

**Comment by hpk42** [comment]
I do think UIs could use these events to help their users debug problems or understanding what's happening wrt to e-mail server connectivity.  If there are no disconnects, though, it's less interesting.  But if it's not too much effort, please add the two connect events (replacing the current INFO ones, so feel free to set data2 with the current info string, maybe is nice).  then we close this issue and open a new one for the disconnect ones.

**Comment by r10s** [comment]
-> https://github.com/deltachat/deltachat-core/pull/270

**Comment by flub** [comment]
To some extend you never know if you are connected, it's networking after all.  You know the connection got established but that's about it.  So while using events is probably the right thing trying to encode conected/disconnected into the events might be stretching the truth somewhat

**Comment by r10s** [comment]
@flub thanks, i see. also found pr #270 not that elegant :)

also @hpk42 so sending just aC_EVENT_IMAP_CONNECTED and DC_EVENT_SMTP_CONNECTED would be sufficient for now?

**Comment by r10s** [comment]
> please add the two connect events (replacing the current INFO ones, so feel free to set data2 with the current info string, maybe is nice).

@hpk42 @flub okay, pr #271 adds the two events, data1=0, data2=0. the INFO ones, however, are not replaces but stay as they are. i think for a simple logging (eg. on android DC_EVENT_INFO is written to logcat) this is easier.

**Comment by testbird** [comment]
> So while using events is probably the right thing trying to encode conected/disconnected into the events might be stretching the truth somewhat

Yeah, monitoring might work like heartbeat monitoring. A connection is working normal with regular successful keep-alive or reconnect intervals.

**Comment by testbird** [comment]
https://github.com/deltachat/deltachat-core/pull/270#issuecomment-419629556
> i think we should [...] go for a more simple DC_EVENT_IMAP_CONNECTED / DC_EVENT_IMAP_DISCONNECTED

Another possibility might be to make the last reconnection intervals available. changes in min. max. average and median reconnectoin intervals could be a measure for connection quality (and further log inspection).

**Comment by hpk42** [comment]
i don't need this event exposed currently.  there are other more interesting changes to make in terms of structuring events ... but more on this in a separate issue.  closing this one.
