### ISSUE TITLE
publish python bindings docs

### ISSUE THREAD

**Issue by hpk42** [deltachat/deltachat-core#274]
Once the python API for the bindings stabilizes, provide docstrings and generate sphinx docs to be published on rtfd.org.  The docstrings should be clear on the types (cffi or higher level).

**Comment by r10s** [comment]
@hpk42 i cannot. but probably @lefherz can. send you both a mail.

**Comment by lefherz** [comment]
py.delta.chat
3600
A
78.47.150.134 

:)

**Comment by r10s** [comment]
@lefherz perfect, thank you. the dns is configurable via netlify then?

**Comment by lefherz** [comment]
Yes. for the record, it is available via this link, when you are logged
in: https://app.netlify.com/account/dns/delta.chat

**Comment by hpk42** [comment]
On Sat, Sep 15, 2018 at 15:05 -0700, Emil Lefherz wrote:
> Yes. for the record, it is available via this link, when you are logged
> in: https://app.netlify.com/account/dns/delta.chat

could someone add me (github @hpk42) to be able to see/edit that
netlify page?

**Comment by r10s** [comment]
@hpk42 added you, you should receive an invitation mail from netlify

**Comment by r10s** [comment]
\o/ great :)
