### ISSUE TITLE
Contribution Guidelines ask unrealistic things from Contributers

### ISSUE THREAD

**Issue by SebastianApel** [deltachat/deltachat-core#287]
Hi Team,

I have been playing around with DC for a bit. There's something I'd like to give as Feedback.

But your contribution guidelines effectively ask me to search the repo for a long time (that I do not want to invest) for "known bugs". How am I supposed to do that? The people who know the buglist intimately are the developers.  As an outsider it takes a loooong time to find out if that bug (or a nuance) is already there.

So, please, let me know if you invite contributions (then someone of the core team should sort through new bugs/defects). 

Kind regards,
Sebastian

PS: Thanks for the great work, I like most of what I have seen so far.

**Comment by angelo-fuchs** [comment]
When you write your contribution, just paste the title in the search bar and see if something comes up.
Yes: Look if its relevant and save the time to write the post.
No: Write the post.

No one expects you to spend hours to look through all the issues, but please value our time as well.

**Comment by r10s** [comment]
i agree with @angelo-fuchs - just a five-minute quick search saves a lot of time to the developers :)

closing this issue now as it is more a discussion than an issue that is related to the app.
