### ISSUE TITLE
Don't download all my attachments to the DC device (as seen on Android today)

### ISSUE THREAD

**Issue by SebastianApel** [deltachat/deltachat-core#288]
Hi Team,

I was quite astonished to see that a messenger with "end-to-end encryption" downloads all my attachments and stores them locally on the device. 

This happens even for emails/attachments of people that I am not actively "chatting" with...

Granted, a lot of providers have seen the unencrypted emails before.  But I do not see a need to contribute to the data leakage by creating additional copies (and potentially replicating them to Google via Cloud Backup etc.)

Looking forward to hearing from you,
Sebastian

**Comment by testbird** [comment]
Yes, astonishing. Very unfortunately, possibly another issue that may show a delta, between what makes sense (implied, named or claimed) and what is actually implemented so far.

This worsens several issues with storage usage problems.

**Comment by r10s** [comment]
hi @SebastianApel, thank you for your post.

however, there are already some thoughts about this at #46, so i think we can close this as a duplicate.
