### ISSUE TITLE
Public keys of contacts

### ISSUE THREAD

**Issue by luisfsr** [deltachat/deltachat-core#29]
Is it possible to get the public keys of contacts? By doing so would it be possible to send them encrypted messages such as through Thunderbird with the enigmail feature? If so, it'd be a good feature! 👌

**Comment by r10s** [comment]
Currently, there is no way to export the public keys out of Delta Chat, and I'm not sure there will ever be such an option.

Delta Chat uses the new Autocrypt standard for PGP key exchange - as Enigmail, K9 and others will do sooner or later. In fact, many people around encryption and MUAs just met the last weekend to define a new standard.  I've been also there.

See https://autocrypt.org/ for details about Autocrypt.
