### ISSUE TITLE
Should "Can't read file." be warning/error instead of info?

### ISSUE THREAD

**Issue by ralphtheninja** [deltachat/deltachat-core#291]
I assume that not giving back any data in response to a `DC_EVENT_HTTP_GET` event causes `Can't read file.` to be emitted as `DC_EVENT_INFO`. Maybe this should be a `DC_EVENT_WARNING` instead and maybe we could tweak the message somewhat? Which file is the message referring to? Just a thought.

![screenshot from 2018-09-18 21-53-43](https://user-images.githubusercontent.com/308049/45712870-ba965f80-bb8d-11e8-8e4a-80f6b9bd13b3.png)

**Comment by r10s** [comment]
the "Can't read file" "message refers to the line above, "Testing ...". might be better to repeat the filename explicitly, would make the log less readable, maybe. however, i have no real precedence to this and we can change this.

wrt warning vs. info: i  think an info is okay here. we're just probing and i do not even exect that any of the up to 4 tests will succeed. in fact, this is quite normal. 
in deltachat-core, a warning is rather close to an error - the main difference is that errors should be reported to the user while warning warnings will only be logged.

**Comment by ralphtheninja** [comment]
Ah ok. No biggie then :)
