### ISSUE TITLE
deltachat-core Readme references dead bzip page

### ISSUE THREAD

**Issue by angelo-fuchs** [deltachat/deltachat-core#296]
The domain http://bzip.org/ is no longer what it should be ("You can buy this domain...") and the link in the readme should be replaced by something better.

**Comment by r10s** [comment]
interesting. according to archive org, the domain changed between Aug 1-8, https://web.archive.org/web/20180801004107/http://www.bzip.org/ , the next snapshots show errors and different register.com pages - maybe the domains was accidentally forgotten to renew or so.

i did not found "something" better, wikipedia links partly to archive.org. we can also do so or just omit the link for now.

**Comment by angelo-fuchs** [comment]
I think linking to the archive.org page is better until something shows up. Maybe ask on the bzip mailinglist/irc channel?

**Comment by r10s** [comment]
meanwhile, there is again a page, however, i'm not sure if it is serious or there are people who want to trick users. 

added a screenshot as these things seem to change daily:

![screenshot_2018-09-22 bzip2](https://user-images.githubusercontent.com/9800740/45921482-cac47c80-beb6-11e8-9e9a-2f148277657c.png)

the black border reminds me to a death notice in a newspaper.

**Comment by angelo-fuchs** [comment]
Does not look legit.
