### ISSUE TITLE
Integrate doc pushing for py.delta.chat (and c.delta.chat) 

### ISSUE THREAD

**Issue by hpk42** [deltachat/deltachat-core#297]
Discussed with @azul to help us with setting up travis secret management. Plan: 

make travis builds upload branches and master docs of "py" docs and maybe also "c" docs. 

- py docs are currently pushed with "cd python/doc ; make install" which syncs it to delta@codespeak.net:build/* and nginx on that codespeak server handles the ssl and serving the docs. 

- C docs ("cd docs ; doxygen") are currently served via github.io -- we can easily let "https://c.delta.chat" point to a directory under the delta account. 

azul, i added your ssh key so you can login and add a new (travis-push) key to authorized keys.

**Comment by r10s** [comment]
> C docs ("cd docs ; doxygen") are currently served via github.io -- we can easily let "https://c.delta.chat" point to a directory under the delta account.

currently, i update the c-api documentation by hand from time to time.
if it is possible automatically as for python, this would be cool, no need to stay on github.io :)

**Comment by azul** [comment]
Looks like i am missing an dependency...
```
~/code/deltachat-core/python/doc$ make install
sphinx-build -b html -d _build/doctrees   . _build/html
Traceback (most recent call last):
  File "/home/azul/.local/bin/sphinx-build", line 7, in <module>
    from sphinx.cmd.build import main
ImportError: No module named sphinx.cmd.build
Makefile:86: recipe for target 'html' failed
make: *** [html] Error 1
```

**Comment by hpk42** [comment]
On Tue, Sep 25, 2018 at 05:04 -0700, azul wrote:
> Looks like i am missing an dependency...
> ```
> ~/code/deltachat-core/python/doc$ make install
> sphinx-build -b html -d _build/doctrees   . _build/html
> Traceback (most recent call last):
>   File "/home/azul/.local/bin/sphinx-build", line 7, in <module>
>     from sphinx.cmd.build import main
> ImportError: No module named sphinx.cmd.build
> Makefile:86: recipe for target 'html' failed
> make: *** [html] Error 1
> ```

this looks odd -- could you reinstall sphinx,
e.g. "pip install --force-reinstall --user sphinx"?
(not quite sure about your setup -- you seem to 
be using "--user" directories -- i usually use
virtualenv's)

**Comment by azul** [comment]
I got the build to work on the CI now. Will focus on the rsync part for now. No need to build the docs locally in the end.

**Comment by hpk42** [comment]
for the record, the proper way to build the docs is through "tox -e doc".
