### ISSUE TITLE
Stickers

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-core#3]
Well, not really needed by me but by some teenager I know.

We should implement a sticker system similar to telegram, of course without a central server as the rest of LibreChat.

Sticker File Format: If we expect stickers to be squares, we can use simple image files (png, jpg) with several stickers beside or below each other - the height resp. the width defines the size of the squares then, the other side divided by the size the number of available stickers. 
More complicated sticker information must be save somewhere else, however, they're not needed urgently.

If we use a sticker system without a central sever, we could implement a functionality to download the complete sticker set from a friend - on request (pull) or if we get the first sticker of a set, all stickers are send silently in the mail (push). Not sure, what to use at the moment. 
This system would also make censoring stickers as impossible as the mail itself.

@ Artists: Even if the sticker system is not ready, we would be glad for stickers that can be used by LibreChat.

**Comment by kskarthik** [comment]
This can be considered as low priority as we have have some important features like e2e encryption,  mails as replies instead of multiple mails per chat etc...

**Comment by r10s** [comment]
> This can be considered as low priority [...]

Not if you ask my daughter ;-)

**Comment by kskarthik** [comment]
Hahah ;-)

**Comment by luisfsr** [comment]
Hahaha... funny, but true.
I think it is something that could be very appealing for young users. Indeed, I believe the success of any app relies on young users adopting the use of it.
Being open source perhaps could offer some liberties to users which is not given by other messengers.
Perhaps developing some add-on that offers the possibility to users create their own stickers could be something appealing to deltachat.
Would it be possible?

**Comment by r10s** [comment]
Yes, of course, this would be possible. And it's true, with an open source program without centralized servers you have definitely more freedom on the content.

**Comment by r10s** [comment]
Maybe it would be sufficiet to support the keyboards that try to send an image in someway (I've seen this on Apple iOS and on a Moto G test device, not sure which API this is.

**Comment by r10s** [comment]
[Moved to the Android part](https://github.com/deltachat/deltachat-android/issues/226), at least for now this is no core issue.
