### ISSUE TITLE
check if stress.c can be used for testing in python, too

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-core#324]
[cmdline/stress.c](https://github.com/deltachat/deltachat-core/blob/master/cmdline/stress.c) tests some low-level functions with some hand-written tests. 

the exposes function `stress_functions(dc_context_t*)` is currently only called in the cmdline utility on startup, however, maybe it makes sense to call them also in the python testing context.

**Comment by ralphtheninja** [comment]
@r10s Possible to expose the test via cli, like `delta --stress-test`? Then we could just spawn a process from py and js.

**Comment by r10s** [comment]
closed by https://github.com/deltachat/deltachat-core/pull/568
