### ISSUE TITLE
create python wheels containing libdeltachat.so 

### ISSUE THREAD

**Issue by hpk42** [deltachat/deltachat-core#328]
For the ``deltachat`` python package, we want to have ``pip install deltachat`` work without requiring going through all the build instructions.  There are two variants we can go for:

- ``libdeltachat-X.so`` is contained but some/all dependencies (openssl, libetpan, ...) need to 
  be installed at system level.  

- ``libdeltachat-X.so`` is contained and has all the dependencies with it (except for OpenSSL at least) 

Possibly the linux/mac wheels could be different from the windows one.  Having working wheels for just one platform first is also helpful. 

@flub please edit/modify this issue in case you have a different suggestion on how top describe the task. I'll review.

**Comment by flub** [comment]
The plan is to use the manylinux1 docker image on travis to build a wheel which will include the python extension module and also use the auditwheel tool to include the libraries, deltachat.so and it's dependencies, used to build the extension.  To do this the following steps should be taken at build time:

- install zlib from source
- Install a good version of openssl.  I believe deta-core uses 1.0 currently so probably the latest 1.0 version is suitable here.  This can re-use some tooling used to build the manylinux1 image itself.
- Install libsasl from source
- Install libetpan from source
- Install delta-core, which should now only use sqlite and netpgp from bundled dependecies.
- Build the python wheel for supported python versions, this will copy and adjust the libraries are required.

**Comment by flub** [comment]
I believe this is now possible using the wheelbuilder container.  They're not automatically built though.

**Comment by hpk42** [comment]
thanks a lot @flub ... it's now all integrated ;)
