### ISSUE TITLE
More easily parseable output from dc_get_info()

### ISSUE THREAD

**Issue by ralphtheninja** [deltachat/deltachat-core#348]
I'd like it very much if the version information in `dc_get_info()` can be written in a more easily parseable format. While doing this maybe also start the beginning of the info with `<key>=<value>` format for everything and introducing sections:

Going from:

```
Chats: 0
Chat messages: 0
Messages in contact requests: 0
Contacts: 0
Database=/tmp/172095d8e3264d990107b1a4806dbafe/db.sqlite, dbversion=41, Blobdir=/tmp/172095d8e3264d990107b1a4806dbafe/db.sqlite-blobs

displayname=Delta One
configured=1
config0=delta1@delta.localhost delta1:***:127.0.0.1:3143 delta1:***:127.0.0.1:3025 IMAP_PLAIN SMTP_PLAIN
config1=delta1@delta.localhost delta1:***:127.0.0.1:3143 delta1:***:127.0.0.1:3025 AUTH_NORMAL IMAP_PLAIN SMTP_PLAIN
mdns_enabled=1
e2ee_enabled=1
E2EE_DEFAULT_ENABLED=1
Private keys=1, public keys=0, fingerprint=
406C C0F3 1D88 E7C7 3FDD
1DAB 3F15 F8A1 7B3A 7DB9

Using Delta Chat Core v0.20.0, SQLite 3.22.0-ts1, libEtPan 1.8, OpenSSL 1.0.2n. Compiled Oct  5 2018, 21:23:10 for 64 bit usage.

Log excerpt:

21:27:10 First time init: creating tables in "/tmp/172095d8e3264d990107b1a4806dbafe/db.sqlite".
21:27:15 Opened "/tmp/172095d8e3264d990107b1a4806dbafe/db.sqlite".
21:27:15 IMAP-jobs started...
21:27:15 IMAP-jobs ended.
21:27:15 Not configured, cannot connect.
21:27:15 Not configured, cannot connect.
21:27:15 IMAP-IDLE started...
21:27:15 IMAP-fake-IDLEing...
21:27:15 SMTP-jobs started...
21:27:15 SMTP-jobs ended.
```

to (note normalized names of keys with underscore and lower case):

```
# key/value data
core_version=v0.20.0
sqlite=3.22.0-ts1
libetpan=1.8
openssl=1.0.2n
compiled_date=Oct  5 2018, 21:23:10
arch=64
number_of_chats=0
number_of_chat_messages=0
messages_in_contact_requests=0
number_of_contacts=0
database_dir=/tmp/172095d8e3264d990107b1a4806dbafe/db.sqlite
database_version=41
blobdir=/tmp/172095d8e3264d990107b1a4806dbafe/db.sqlite-blobs
displayname=Delta One
configured=1
config0=delta1@delta.localhost delta1:***:127.0.0.1:3143 delta1:***:127.0.0.1:3025 IMAP_PLAIN SMTP_PLAIN
config1=delta1@delta.localhost delta1:***:127.0.0.1:3143 delta1:***:127.0.0.1:3025 AUTH_NORMAL IMAP_PLAIN SMTP_PLAIN
mdns_enabled=1
e2ee_enabled=1
E2EE_DEFAULT_ENABLED=1
private_keys=1
public_keys=0
fingerprint=406C C0F3 1D88 E7C7 3FDD 1DAB 3F15 F8A1 7B3A 7DB9

# Log excerpt:
21:27:10 First time init: creating tables in "/tmp/172095d8e3264d990107b1a4806dbafe/db.sqlite".
21:27:15 Opened "/tmp/172095d8e3264d990107b1a4806dbafe/db.sqlite".
21:27:15 IMAP-jobs started...
21:27:15 IMAP-jobs ended.
21:27:15 Not configured, cannot connect.
21:27:15 Not configured, cannot connect.
21:27:15 IMAP-IDLE started...
21:27:15 IMAP-fake-IDLEing...
21:27:15 SMTP-jobs started...
21:27:15 SMTP-jobs ended.
```

**Comment by ralphtheninja** [comment]
I could hack up a PR for this if it's interesting to others.

**Comment by ralphtheninja** [comment]
It would make life easier for bindings and specifically for https://github.com/deltachat/deltachat-desktop/issues/103

**Comment by r10s** [comment]
the general idea of dc_get_info() - was to display some information to the user that may be of some use for debugging.

my long-term idea was to give the information back as structured data, however, maybe your idea is simpler and nicer.

however, i am wondering it it is currently really required to show the information in a nicely formatted way - wrt #103 i would currently just show name+version+logo plus a button "more details" which just shown the output of dc_msg_get_info() :)

at least, this is what we're doing on android :)

however, otoh i think some more structure in the data won't be bad - independently of parsing.

**Comment by hpk42** [comment]
On Fri, Oct 05, 2018 at 13:32 -0700, björn petersen wrote:
> the general idea of dc_get_info() - was to display some information to the user that may be of some use for debugging.

IMO the c-core shouldn't be concerned with providing multi-line strings that are directly displayed. 
very important will be btw the dependency-version information (libetpan) for debugging issues in the future ...

> my long-term idea was to give the information back as structured data, however, maybe your idea is simpler and nicer.
> however, i am wondering it it is currently really required to show the information in a nicely formatted way - wrt #103 i would currently just show name+version+logo plus a button "more details" which just shown the output of dc_msg_get_info() :)
> at least, this is what we're doing on android :)
> however, otoh i think some more structure in the data won't be bad - independently of parsing.

I agree it's good if the C-core provides machine-parseable info and the UI/bindings care for
rendering/presenting them in some nice manner.

**Comment by r10s** [comment]
so, i think, for now, @ralphtheninja proposal is reasonable.
putting some more structure seems to be easy and does not harm the existing usage (Android just displays the text as is and can continue in doing so).

@ralphtheninja do you want to do this change? may be easier as you will also parse the output.
but if you have problems with the c-string-and-formatting-thingies, please let me know; i can do the changes as well then.

btw. maybe we can give `config0` and `config1` more meaningful names :) maybe `entered_credentials` and `configured_credentials`.
btw2. the value shows the condensed credentials as `<addr> <imap-user>:<pw>:<server>:<port> <smtp-user>:<pw>:<server>:<port> <flags>` - i just wanted sth. that fits well into one log line :)

**Comment by ralphtheninja** [comment]
> @ralphtheninja do you want to do this change? may be easier as you will also parse the output.
> but if you have problems with the c-string-and-formatting-thingies, please let me know; i can do the changes as well then.

I can give it a go and bother you with questions if I run into problems :smile:

**Comment by r10s** [comment]
great :)

**Comment by Ampli-fier** [comment]
> btw. maybe we can give `config0` and `config1` more meaningful names :) maybe `entered_credentials` and `configured_credentials`.

I vote for a change :) and have another proposal:

`config0` -> `entered_account_settings`
`config1` -> `used_account_settings`
`configured` -> `is_configured`.
