### ISSUE TITLE
strike dc_send_image|audio|... in favor of just "dc_send_file"?

### ISSUE THREAD

**Issue by hpk42** [deltachat/deltachat-core#352]
I am wondering why there are all the different send_X_msg functions. 

A quick test showed that when i do a ``dc_send_file("some.png")`` the other side will still see the incoming message as a "image/png" mimetype and a DC_MSG_IMAGE type.  So why would i practically need to call the specific function instead of just the generic ``dc_send_file``? 

I'd think that the callers (Android, ios, Desktop, Python Bots) have a better way to deal with different content types -- there are all kinds of image/video/audio types etc. -- i wouldn't bother the core with tracking this specifically and just let the clients deal with it (showing an "unrecognized content type" if it can't render it). 

We could still define what a reasonable client should be able to show ... i.e. certain mime-types (which anyway can also come in via regular mails).

**Comment by r10s** [comment]
`dc_send_file_msg()` as well as all other `dc_send_X_msg()` functions are just wrappers around the `dc_send_msg()` functions.

i would be glad to strike most of them, i would just leave `dc_send_text_msg()` for convenience, simple testing and shorter examples.

imo, the main reason to get rid of these wrapper functions is that we will probably need some additions to message sending in the near future (and it would be a pain to maintain this for a bunch of sending functions):

- there may be the flags "force-encrypted" and "force-unencrypted"
- messages may be a reply to another message which msg_id is tracked then in some way
- text may be also added to images or other files - the ui of android-dev already supports this and i think this is a very useful addition
- more to come, i am sure :)

also, this would make complex draft handling (currently not existent) more straight-forward as `dc_set_draft()` can have the same signature as `dc_send_msg()`.

the idea of using dc_send_msg() is that a message object is created by the caller as follows:

```
msg = dc_msg_new(context);
dc_msg_set_type(msg, DC_MSG_IMAGE);
dc_msg_set_text(msg, foo);
dc_msg_set_file(msg, "/foo/bar.dat");
dc_send_msg(context, msg); // or dc_safe_draft(context, msg);
```

wrt type: i agree that it is a bit redundant, as often the file implies the type. however, in the flow of the ui, there are some times differences: eg. a mp3 file may be an attached smash-hit or a voice message - which are shown differently eg. on android. 
same for gif that may be an image or an video.

also, the type implies in a way what the ui is expected to show: images, music, voice types, thumbnails of videos, if possible. for all other types, the ui just checks if the system can handle the type - eg. showing a pdf.
from the view of the ui, this is simple, i think. and easier than to handle mime/types.

so, i would not tough the type of the message, also as it is used everywhere in the core.

but maybe we can remove the need to set the mime/type when sending a message.

**Comment by hpk42** [comment]
agreed -- maybe go for ``dc_msg_new(context, view_type)`` because all messages need to have a type? also don't see the need to allow ``dc_msg_set_type``.

**Comment by ralphtheninja** [comment]
> for me, this API reduction change can come soon and without a deprecation phase -- can update the python bindings quickly.

Ditto for node bindings.

**Comment by r10s** [comment]
-> https://github.com/deltachat/deltachat-core/pull/355

**Comment by r10s** [comment]
i think we can close this issue, feel free to re-open if sth. is missing :)
