### ISSUE TITLE
Remove DC_MSG_UNDEFINED

### ISSUE THREAD

**Issue by ralphtheninja** [deltachat/deltachat-core#359]
Since `dc_msg_new()` now accepts `viewtype` as second parameter, it doesn't really make any sense to keep the `DC_MSG_UNDEFINED` as message type, since we now can force the caller to pick a type.

**Comment by r10s** [comment]
i think we can do so, esp. as dc_get_msg() and related functions return NULL on errors (added some comments to this in #360)

**Comment by hpk42** [comment]
i am fine with that, no problem for the python bindings and api.
