### ISSUE TITLE
enigmail key export format is incompatible to import in delta chat

### ISSUE THREAD

**Issue by haeckser** [deltachat/deltachat-core#36]
I had a crash on upgrade to 0.92 and the program started from scratch (as if the DB was initialized with a new one). I would like to reimport my keys which I had imported into Thunderbird with enigmail.
The key management (in thunderbird) offers the option to export public and private key, but this format cannot be used for import in Delta Chat
-> additional import format (in general for existing keys) to allow transfer from enigmail
->documentation improvement to give a clear statement that keys generated in Delta Chat should be exported AND stored somewhere. 
I disabled encryption in the first shot in 0.9.2m because I planned to reimport the keys.
But I could only import the public key back from Thunderbird. And so I enabled encryption again with the intention to generate a new key and the hope that it will be published automatically and will overwrite the old public key at contacts automatically. But it seems that the missing imported  private key  (info about tells me 1 public and 0 private keys) blocks encryption. No clear message or signal for the user to understand this behaviour.

**Comment by haeckser** [comment]
I see in code, that the import function is searching for the start target, localize the corresponding end target, delete it and import the whole block. Enigmail is exporting BOTH key in one file and so block is the first key + start. second key and end mark of second key -> garbage
should search for the end tag and import block between and retry search from end tag of first key

**Comment by r10s** [comment]
can you confirm that this is still true for the current version?
and does it only affect enigmail or just gpg? a concrete advice how to generate a key that cannot be imported in delta would also be helpful.

Thanks in advance :)

**Comment by r10s** [comment]
> I see in code, that the import function is searching for the start target, localize the corresponding end target, delete it and import the whole block. Enigmail is exporting BOTH key in one file and so block is the first key + start. second key and end mark of second key -> garbage
should search for the end tag and import block between and retry search from end tag of first key

Thank you fro the very detailed information, this issue should be fixed by the new armored parser now which is also used for key importing:
https://github.com/deltachat/deltachat-core/commit/0758641ef7b2c61d501251d21a96ca9037880e0f

The commit mentioned above checks that the second block/key/whatever is really ignored.

I think this issue can be closed now, if the problem still exists, please reopen.
