### ISSUE TITLE
helper function to obtain valid configuration keys

### ISSUE THREAD

**Issue by hpk42** [deltachat/deltachat-core#366]
Is there a simple `dc_get_config_keys(dc_context*)` function which returns an array or a space-separated string containing the valid config keys?  It's probably a small-overhead to maintain this list but right now i wouldn't easily know what config keys are available apart from "addr" or "mail_pw" or "e2ee_enabled". Once i have the list i can easily search the docs or source for the meaning.

**Comment by r10s** [comment]
there is no function, but the list of _gettable+settable_ values is here:

https://c.delta.chat/classdc__context__t.html#aff3b894f6cfca46cab5248fdffdf083d

**Comment by hpk42** [comment]
very nice  -- could you return this with `dc_get_config_info` similar to `dc_get_info()`? It seems machine-parseable enough.  Did i mention that programmatic introspection is cool? :)

**Comment by r10s** [comment]
hm, i do not know of a an easy way to access the doxygen comment from c.
or the other way round would be probably nicer: having a c-ish array with the names and let this appear in doxygen. however, same here: i do not know how and if this is possible.

of course, we could maintaining two lists in c, however, i am sure they will be out of sync soon :)

**Comment by hpk42** [comment]
i guess it's not worth trying to automate this -- is maintaining two lists that much of a burden? I'd thionk that adding new config keys happens rarely and the effort of adding it in two places is manageable for now.

**Comment by r10s** [comment]
> is maintaining two lists that much of a burden?

it's not perfect, no, we can go for that. i think any other parsing or automation solution is more complicated.

**Comment by r10s** [comment]
i think this can be closed, feel free to re-open otherwise :)
