### ISSUE TITLE
remove default value from dc_get_config()

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-core#367]
i think, we should get rid of the default value of the [dc_get_config()
](https://c.delta.chat/classdc__context__t.html#ada7a19d3c814ed5f776a24006259395d)

the ui typically does not know the defaults eg. for e2ee_enabled which results in tracking a set of defaults eg. for android. i think for js there may be the same problems.
but the core knows, eg. we have a DC_E2EE_DEFAULT_ENABLED in the core.

i also think there is no real need for the ui to know if a value is a default value or not (even with the `def` parameter you cannot - once set, `def` is never returned.

background: the `def` parameter was handy some time ago for getting things done fast, however, meanwhile it seems.

@ralphtheninja @hpk42 what do you think? shall i remove the `def` parameter?

**Comment by hpk42** [comment]
yes, makes sense.  For me this also ties to #366 btw -- because i want to make the high-level API throw an error if set/get_config is tried with a non-existent key.

**Comment by ralphtheninja** [comment]
Kill it with :fire:

**Comment by r10s** [comment]
burn, defaults, burn :)
