### ISSUE TITLE
Add email alias support

### ISSUE THREAD

**Issue by hubgit1000** [deltachat/deltachat-core#37]
I use different email aliases with my account but I can only use the main email address to login via IMAP.
It would be cool to be able to use the other aliases to send and receive messages.

BTW - Great project!

**Comment by STPKITT** [comment]
I think this can be closed since you can already set a separate IMAP-loginname in Delta Chat's account-settings by clicking on the "+"-symbol to show manual settings. I also tested that feature and it worked.
BTW I think that part of the UI could be much improved.

**Comment by hubgit1000** [comment]
It works indeed. Thank you!
