### ISSUE TITLE
don't move messages to DeltaChat folder 

### ISSUE THREAD

**Issue by hpk42** [deltachat/deltachat-core#371]
The logic for moving messages from INBOX to DeltaChat is buggy and somewhat complex.  It's also unclear how multi-device (Desktop and Android or iOS) can easily remain synchronized.  We have a single IMAP thread and this can only watch exactly one IMAP folder through IMAP/Idle. It's therefore useful to try out not doing any such moves.  Probably a good idea to first implement better threading (#72).

**Comment by csb0730** [comment]
Is "IMAP thread" the correct wording for watching several folders?
Isn't it true that for every folder covered by IMAP IDLE a separate connection has to be opened and watched? This not really demands for an additional thread?!

**Comment by r10s** [comment]
> Is "IMAP thread" the correct wording for watching several folders?

Don't really get the question: 
The [IMAP thread](https://c.delta.chat/) watches _one_ folder; this is also written above.

> Isn't it true that for every folder covered by IMAP IDLE a separate connection has to be opened and watched? 

yes, if several folders shall be watched in a reliable way, one would need one thread, one connection and one IMAP IDLE for every folder being watched.

however, this is complicated, hard to maintain and also quite some overhead (eg. re-connects consume mobile data, re-connects may prevent messages from being sent in flaky networks, more battery consumption as more threads are running etc.)  
there are some extensions to IMAP IDLE that handle this more gracefully, however, these extensions are not always available and would make things even more complicated as the same as described above is still needed as a fallback.

finally, all this brought is to the single-folder approach.

**Comment by csb0730** [comment]
Yes, I understand that. Maybe I used a misunderstanding wording in my comment.
My intension was, that basically it's not really a must to use an extra thread for every connection (see select() function).
:)

**Comment by hpk42** [comment]
On Thu, Oct 18, 2018 at 15:04 -0700, Christian Schneider wrote:
> Yes, I understand that. Maybe I used a misunderstanding wording in my comment.
> My intension was, that basically it's not really a must to use an extra thread for every connection (see select() function).
> :)

yes but we are defering the actual network operations to libetpan so
probably can't fiddle with the particular select-techniques etpan employs.
It'd be interesting to find out if libetpan allows to route multiple
IMAP idle calls (to different imap accounts for example) through one select.
I doubt it does.
