### ISSUE TITLE
Make "INBOX" configurable

### ISSUE THREAD

**Issue by hpk42** [deltachat/deltachat-core#372]
Allow to configure which "INBOX" is watched by DeltaChat.  Users may then add server-side filters to put all messages they want to have in DeltaChat (maybe to a particular alias) into a configured folder -- keeping a clean non-chat INBOX for other MUA.

**Comment by flub** [comment]
is there a delta-specific header or so to use for sorting?

(If this is the wrong place to discuss that please redirect)

**Comment by hpk42** [comment]
On Wed, Oct 17, 2018 at 07:53 -0700, Floris Bruynooghe wrote:
> is there a delta-specific header or so to use for sorting?

not really. Currently there is i think a "Chat-Version" header.

One question is whether we want to make it easy to distinguish
delta chat messages from non-delta ones when they are in transit. 
It would allow providers to block them more easily. 

then again, i see the point in being able to have simple server
side filtering to move delta messages elsewhere.  Such filter rules
couldn't easily pick up incoming non-delta messages 
when these messages are part of a chat.
