### ISSUE TITLE
openssl slowness

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-core#376]
key-generation and sending messages is sometime _very_ slow. key-generation takes eg. some minutes and sending messages up to 10 seconds.

this affects only the build-in openssl-library, using the system-library, the speed seems to be normal.

i've investigated a bit, first on sending messages. results:
- the time is consumed on pgp-signing
- trace: pgp_write_sig() -> rsa_sign() -> pgp_rsa_private_encrypt() -> RSA_private_encrypt() -> RSA_eay_private_encrypt() -> [BN_mod_exp_mont() -> BN_mod_exp_mont_consttime()](https://github.com/deltachat/deltachat-core/blob/master/libs/openssl/crypto/bn/bn_exp.c#L391)

so, at the end, it seems to have sth. to do with the BIGNUM-thingie.
BN_mod_exp_mont() is btw. called several times, most times much faster.

so i thought it sth. with the parameters, it's `a^p % m`, as we're signing, the parameters are probably related to the own private key. however, the old-telegram-apk has no problem with exactly the same data.

if anyone has an idae, this is very welcome :)
i've looked for #defines or so, but did not find anything related. 

my next steps would be:
- to see where the key generation slowness ends (this is also exitant in the old-telegram-apk, but not that extreme).
- it's also worth trying boringssl or a newer openssl version out, however, this has it's own issues and i am not sure if this will fix the problem.

EDIT: the time is spent in [this loop](https://github.com/deltachat/deltachat-core/blob/master/libs/openssl/crypto/bn/bn_exp.c#L880) then, with bits=3065, window=6. interesting, however, i think we shoud try boringssl instead of trying to understand this ....

**Comment by r10s** [comment]
> sending messages up to 10 seconds.

found out the reason for this on android: it was the debug mode enabled in Application.mk.
unfortunately, one of the things i checked out rather lately, did not assumed that it make such a difference  - 10-15 seconds vs. "nearly instant" (in fact, 0.8 seconds)

however, this seems _not_ to be the reason for the slow key generation; this really might be the PRNG. good that i know which placed i have to check for this now.

also, this does not solve the openssl build and update issue (btw. have we thought about using libressl?)

**Comment by ralphtheninja** [comment]
>  (btw. have we thought about using libressl?)

Trying out libressl might be a good move for mac

**Comment by hpk42** [comment]
On Wed, Oct 10, 2018 at 14:14 -0700, björn petersen wrote:
> > sending messages up to 10 seconds.
> 
> found out the reason for this on android: it was the debug mode enabled in Application.mk.
> unfortunately, one of the things i checked out rather lately, did not assumed that it make such a difference  - 10-15 seconds vs. "nearly instant" (in fact, 0.8 seconds)

woah -- good you found this now!  Are the 0.8 seconds mostly encryption? 
 
> however, this seems _not_ to be the reason for the slow key generation; this really might be the PRNG. good that i know which placed i have to check for this now.

Pretty sure PRNG is considered to be a no.1 issue with key generation slowness ...
eg installing havegd (IIRC) on debian dramatically sped up gpg key generation
on my laptop. 

> also, this does not solve the openssl build and update issue (btw. have we thought about using libressl?)

don't know libressl -- maybe @flub or @the-compiler does? 

i think we could also enter a conversation with the OTF red-team lab about
this and other issues ... but that's likely a bit more of a medium-term
perspective.

**Comment by r10s** [comment]
> Are the 0.8 seconds mostly encryption?

it's all _crypto_, most of this, however, _signing_. see #382.
all the times are a bit confusing, however, the 0.8 s are _remaining_ time spent before smtp gets involved. the 0.5 s that are saved by #382 are already subtracted iirc.

**Comment by hpk42** [comment]
On Thu, Oct 11, 2018 at 18:45 +0000, björn petersen wrote:
> > Are the 0.8 seconds mostly encryption?
> 
> it's all _crypto_, most of this, however, _signing_. see #382.
> all the times are a bit confusing, however, the 0.8 s are _remaining_ time spent before smtp gets involved. the 0.5 s that are saved by #382 are already subtracted iirc.

this probably is already sufficient -- with delta/android 0.20 it takes
like 1-2 seconds currently (subjectively measured) so it's already an improvement. 
and your phone where you tested this was not super-fast, right?

**Comment by r10s** [comment]
> and your phone where you tested this was not super-fast, right?

yes, my testing phone is slooooow :)

**Comment by hpk42** [comment]
if i see it correctly, we can close this generic issue.  If anything, there are remaining platform-specific issues.
