### ISSUE TITLE
Change the fixed temporary signature to make clear that Delta Chat isn't in stores, yet

### ISSUE THREAD

**Issue by STPKITT** [deltachat/deltachat-core#38]
Currently every message sent from Delta Chat contains the signature "Mit meinem Delta Chat Messenger gesendet" (german text, don't know what it says in other languages).
This leads some people to visit the Play Store or the Appstore corresponding to their used operating system searching for Delta Chat but of course the search won't find it.
So I think the appropiate signature must contain the information that Delta Chat is still in beta status and therefor currently only available from F-Droid/direct download/compiling yourself. The way it is now the signature may be more detrimental than having the desired effect.

**Comment by kskarthik** [comment]
A hyper link in signature 

 sent from my [delta chat messenger](https://delta.chat) will be user friendly :)

**Comment by r10s** [comment]
Well a hyper link can only be used by entering the plain text url (we do not send HTML messages), this would result in a footer as 

```
--
Sent with my Delta Chat messenger - https://delta.chat - please excuse my brevity.
```

I'm not sure if I really like it.

NB: Meanwhile the signature is also editable, see https://github.com/deltachat/deltachat-android/issues/97

And: I've just changed made a little change in the internal default handling: I do not init the user setting with the default string - this allows us to change the default strings anytime for all users who did not made their own setting. So there is no need for a quick decision :-)

**Comment by r10s** [comment]
Since 0.9.4 we add a link to https://delta.chat to the footer so that the user can inform himself about Delta Chat. Moreover, the new footer is editable.

**Comment by STPKITT** [comment]
It still just says "Mit meinem Delta Chat Messenger gesendet" in my 0.9.4 installation!?!

**Comment by r10s** [comment]
It should reads "Mit meinem Delta Chat Messenger gesendet: https://delta.chat" on new installations; for existing ones there may be other defaults.
