### ISSUE TITLE
log excerpt needed in dc_get_info()?

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-core#386]
wondering if the log excerpt is needed in dc_get_info().

currently, i am adapting the debug-log-view on android, and the new code offers a much better approach by using the system log-lines (that include the delta ones).

as i would like to prepend the info from dc_get_info() to the debug-view, i would need a flag or so that removes the log lines.

however, i am not sure that the 200 last log lines are needed at all in dc_get_info(), esp as they exclude all log stuff that is not done in the core.
might be that also for node, there are better methods. for cli-bots, i think it is also not needed as the log is just always printed and available as the normal shell-buffer.

the code to collect them is not that complex, however, includes some locking and so on, so if it is not really needed, maybe we should get rid of it.

@ralphtheninja @hpk42 what do you think?

**Comment by ralphtheninja** [comment]
I think we can remove it. Maybe instead have a specific function call for getting the log, e.g. `dc_get_log_excerpt()`

**Comment by r10s** [comment]
> Maybe instead have a specific function call for getting the log, e.g. dc_get_log_excerpt()

that's probably a good idea.

**Comment by ralphtheninja** [comment]
> and if it turns out that the function is not used, we can remove it at all - or remove it from core and add it to a helper/tool-file as we've done for eventqueue.c. just to keep the core clean.

:+1:

**Comment by hpk42** [comment]
agreed, the raw log excerpt in dc_get_info() is not really useful. 
fine to remove it from my side.
