### ISSUE TITLE
sync changelog and so-version with tag

### ISSUE THREAD

**Issue by hpk42** [deltachat/deltachat-core#398]
there is a "v0.23.0" tag with core but changelog contains no entry for it and building libdeltachatcore yields an so-name of "0.21...." -- i think tagging should involve full synchronization of these places :)

**Comment by r10s** [comment]
at least the core-changelog has an entry: https://github.com/deltachat/deltachat-core/blob/master/CHANGELOG.md#v0230

i think the high-level changelog is more about released user-versions and "visible" features, so i think this is okay.

wrt tag: there is a tag, however, maybe it is created in the wrong way? i've created it using `git tag -a TAG` - but also github shows it differently in the ui, so it seems these tags are not picked up by the build system - but the "manual create version" tags are :/

**Comment by flub** [comment]
I just made the build pick up the existing tags, so whatever you did before...

But as discussed the soversion following the tag version might not be correct anyway depending on how careful you are.  And maybe having bad soversions is worse than having no soversions.  Who knows.

**Comment by r10s** [comment]
during delta-ix, a "checklist" about how new releases should be tagged, signed and created was written down with @drebs and others at [docs/release-checklist.md](https://github.com/deltachat/deltachat-core/blob/master/docs/release-checklist.md); in  https://github.com/deltachat/deltachat-core/commit/ab85dd2954e666d475e1a90c200a8bd4bd231a99 i've added a comment about not to forget to check the CHANGELOG.

together with @flub let the build picking the existing tags, i think, at least for now, this issue can be closed.

feel free to re-open if i've missed something :)
