### ISSUE TITLE
Have meson find LibreSSL on Mac

### ISSUE THREAD

**Issue by ralphtheninja** [deltachat/deltachat-core#424]
See https://github.com/deltachat/deltachat-core/issues/419#issuecomment-436574712

**Comment by steils** [comment]
Hi Lars-Magnus, could you post your `meson-log.txt`?
Unfortunately I won't be able to test it on Mac (since I haven't one), but maybe the error is clear from the logs.

**Comment by ralphtheninja** [comment]
@steils I'm not running mac either, so a Travis log have to do :)

https://travis-ci.org/deltachat/deltachat-desktop/jobs/451685904#L6503-L6612

**Comment by ralphtheninja** [comment]
Might be related to `pkgconfig` not on mac or something like that. I'm hoping @flub has some more input on this, or someone else.

**Comment by ralphtheninja** [comment]
Updated the title to be more specific.

@r10s Maybe we can try to build desktop on your mac some day to get our hands on the `meson-log.txt`?

**Comment by steils** [comment]
Maybe you can try this: https://docs.travis-ci.com/user/running-build-in-debug-mode/ ?

> To enable debug for your public repositories, please email us at support@travis-ci.com and let us know which repositories you want activated

**Comment by r10s** [comment]
@ralphtheninja sure. if it helps, i can also give you a remote access, shared screen or so. maybe this is even easier.

**Comment by ralphtheninja** [comment]
> Maybe you can try this: https://docs.travis-ci.com/user/running-build-in-debug-mode/ ?

Aah thanks for the hint. I had no idea about this. Will mail them straight away.

**Comment by ralphtheninja** [comment]
Mailed the Travis support and asked them to enable debug mode for desktop, node bindings and core as well.

**Comment by ralphtheninja** [comment]
The only thing `meson-log.txt` says about `openssl` is:

```
Determining dependency 'openssl' with pkg-config executable '/usr/local/bin/pkg-config'
Called `/usr/local/bin/pkg-config --modversion openssl` -> 1

Dependency openssl found: NO (tried pkgconfig and framework)
Looking for a fallback subproject for the dependency openssl
```

**Comment by ralphtheninja** [comment]
Some more info. It seems if I do:

```sh
brew install libressl
export PKG_CONFIG_PATH=/usr/local/opt/libressl/lib/pkgconfig:/usr/local/lib/pkgconfig:/usr/local/lib
```

Then `meson` spits out the following:

```
Determining dependency 'openssl' with pkg-config executable '/usr/local/bin/pkg-config'
Called `/usr/local/bin/pkg-config --modversion openssl` -> 0
2.8.2
Called `/usr/local/bin/pkg-config --cflags openssl` -> 0
-I/usr/local/Cellar/libressl/2.8.2/include
Called `/usr/local/bin/pkg-config openssl --libs` -> 0
-L/usr/local/Cellar/libressl/2.8.2/lib -lssl -lcrypto
Called `/usr/local/bin/pkg-config openssl --libs` -> 0
-L/usr/local/Cellar/libressl/2.8.2/lib -lssl -lcrypto
Dependency openssl found: YES 2.8.2
```

What's pretty interesting is that the compile works out of the box, and this is with a version of core that doesn't have the `LibreSSL < 2.7.0` fix in it.

**Comment by ralphtheninja** [comment]
Anyway, it seems `meson` indeed can find `LibreSSL` with `pkg-config` on Mac, so closing this.

**Comment by ralphtheninja** [comment]
Trying it out here https://github.com/deltachat/deltachat-desktop/pull/295
