### ISSUE TITLE
for what exact reason is SASL needed?

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-core#430]
this issue is to collect why SASL is needed and if we can get rid of it.

@steils did already some research at https://github.com/deltachat/deltachat-core/pull/429#issuecomment-437577076:

> @r10s The exact reason is using mailsmtp_auth() in dc_smtp.c.
> Then the internal funtion in libetpan mailesmtp_auth_sasl() is used, an if USE_SASL is not defined, I get > "Not implemented" error message on SMTP-login.

**Comment by steils** [comment]
Why do you want to get rid of SASL? (just curious)
I'm not an expert in SMTP, but it seems that all public email services require SMTP authentication (with SMTP `AUTH` command), and therefore SASL which is required my standard https://tools.ietf.org/html/rfc4954
Also: https://developers.google.com/gmail/imap/imap-smtp
and https://en.wikipedia.org/wiki/SMTP_Authentication

**Comment by r10s** [comment]
> Why do you want to get rid of SASL? (just curious)

just to simplify the build process, esp. on systems as mac, ios, windows, android.
might be that we need only very few lines of this lib - not sure, however - and then it might be easier to re-implement them.

this issue is not about removing functionality from SMTP/AUTH or so - it's fine to keep Cyrus SASL if its really needed :)

@jankass iirc also the licence of Cyrus SASL was at least not "simple"?

**Comment by steils** [comment]
Didn't you think about switching to libcurl from libetpan then? It doesn't depend on Cyrus SASL, implementing SASL based authentication itself.

**Comment by hpk42** [comment]
On Sun, Nov 11, 2018 at 15:35 -0800, Stefan Strogin wrote:
> Didn't you think about switching to libcurl from libetpan then? It doesn't depend on Cyrus SASL, implementing SASL based authentication itself.

libetpan is used for imap/smtp communication -- 
how can libcurl help?

**Comment by steils** [comment]
On 12/11/2018 10:04, holger krekel wrote:
> 
> libetpan is used for imap/smtp communication --
> how can libcurl help?
> 

Like the same: https://curl.haxx.se/libcurl/c/smtp-ssl.html
Or do I misunderstand something?

**Comment by r10s** [comment]
did not know libcurl can do smtp, even imap is supported, at least in some way. @steils thank you very much for the info :)

not sure about mime, however, this could be done by gmime probably.
however, i think switching _these days_ is maybe not a good idea, there are already so many open ends ...

also, the most pressing issue is OpenSSL, not even SASL as the title of this issue may suggest (this issue is just about the question why it is needed ... and if it can be replaced by a "few lines" in core, just having one dependency less)

**Comment by flub** [comment]
thanks for this info!

**Comment by r10s** [comment]
okay, we can summarize that SASL is needed for some authentication :)
