### ISSUE TITLE
(traffic saving) allow delayed downloading of attachments

### ISSUE THREAD

**Issue by testbird** [deltachat/deltachat-core#436]
IMAP has no native support for downloading the messages text (body) without also downloading all attachments (https://stackoverflow.com/questions/15731920/is-it-possible-to-only-download-imap-messages-without-attachments).

However, saving (possibly expensive or slow) download traffic on reception is possible by having Email-chat clients always send attachments in separate emails, and mark them for the receipient to know that they only contain a single attachment without any further text in the body.

Then the corresponding message bodies may only be downloaded on request, if in traffic saving mode.

**Comment by r10s** [comment]
related to #437; in general, this might become interesting some time in the future, however, also here i would sugggest to start the discussion about new features in the forum at https://support.delta.chat
