### ISSUE TITLE
(traffic saving) minimize requirement to up/download a message body

### ISSUE THREAD

**Issue by testbird** [deltachat/deltachat-core#437]
As long as the entire text of a short chat message fits into the subject, there is no need to upload the text a second time in the message body, and no need for the receiver to download the entire message body.

To skip downloading the body, "subject only" messeges would need to be marked in a distinguishable way.
Possibly, by ending the subject with a special character and using a subject-only optimized format like
 `-[] Hi, short text. |`, or  `-[groupname] some text. |` for group messages, so that classic MUA users can also see the character and know that there is no text to look for in the body.

(The example used subject formatting ideas from https://github.com/deltachat/deltachat-core/issues/136#issuecomment-402391991 and https://github.com/deltachat/deltachat-core/issues/128#issuecomment-423628159)

Not having to download the message body for regular text messages, will allow to only make (delayed) downloads of the message body, if it contains attachments. -> #436

**Comment by r10s** [comment]
how can this work together with encryption?

**Comment by testbird** [comment]
Hm, right only `Autocrypt:` is a header. And I guess the encrypted subject feature uses information in the body to let compatible clients override the subject, right?

But traffic could still be reduced for encrypted messages by breaking PGP compatibility?:

* moving the keys from the `Autocrypt:` headers into the body (only needs to be downloaded if a known key is not working)
* moving the encrypted part (subject and possibly a longer remaining body text) into a header
