### ISSUE TITLE
Voice / Video calls support 

### ISSUE THREAD

**Issue by kskarthik** [deltachat/deltachat-core#44]
Recently Riot messenger guys are collaborating with https://jitsi.org web based p2p VoIP team to improve their voice/video calls. How about delta chat also embracing this idea? 

Source: https://medium.com/@RiotChat/riot-im-web-0-12-7c4ea84b180a

**Comment by r10s** [comment]
Yes, this would be definitely a great improvement. I would vote for this. +1

**Comment by 3screens2eyes** [comment]
Recordings if Voice/Video(-Mail) could conceivably fit into DeltaChat's scope, since this is a type of email program and as such *not* real-time oriented, but asynchronous.
-- 
regards,
-- 3screens2eyes

**Comment by r10s** [comment]
Voice/Videomails are already supported by Delta Chat.

Realtime Voicecalls (or even Videocalls) could barely be done via SMTP/IMAP. Out idea is to use a mail for "ringing" and do the call then peer-to-peer. The "ringing" mail could contain all needed information, as the IP-address of the calling peer.

**Comment by kskarthik** [comment]
@r10s could we use webRTC via android webkit ? If so, that could the job easy with jitsi

**Comment by r10s** [comment]
> could we use webRTC via android webkit ? If so, that could the job easy with jitsi

At a first glance, this should work some way.

**Comment by 3screens2eyes** [comment]
You're still wanting an email client to do real-time communications, i.e. a horse to fly.

**Comment by luisfsr** [comment]
That'd be super! P2p video/voice calls without any annoying noise :)

**Comment by Hocceruser** [comment]
@3screens2eyes: Yes it is possible, for example like this:
To start a video chat, the DC client sends a message with a link. If the other user doesn't use DC he can click on the link to join the video chat. If he does use DC, it recognises the link and shows it as an incoming call.

This is already possible with help of an app named Jitsi Meet but it would be nice to do this without an extra app.

Of course it is adding wings to a horse but Pegasuses are quite useful :-)

**Comment by r10s** [comment]
> Of course it is adding wings to a horse but Pegasuses are quite useful :-)

:)

**Comment by 3screens2eyes** [comment]
@Hocceruser: (slightly OT) once the necessary coding/gene splicing gets started, the implementor will doublessly come to see the massive adaptions needed for this to fly. Think muscle size for wing flapping in birds...
<silly>
A rib wing glider like https://en.wikipedia.org/wiki/Draco_(genus) could be achievable though - now if only that horse could climb trees...
</silly>

regards,
-- 3screens2eyes

**Comment by r10s** [comment]
Unless there are some volunteers working on this issue, for now, this is out of scope IMHO. However,  the idea stays available via https://github.com/deltachat/deltachat-android/wiki .

**Comment by whippedcream-log** [comment]
Why not use meet.jit.si yourself providing room name and password via Delta.chat ?

**Comment by kskarthik** [comment]
Please elaborate @whippedcream-log

**Comment by testbird** [comment]
LibRingClient (LRC) https://git.ring.cx/savoirfairelinux/ring-client-android/issues/510#note_8190 provides models for p2p voice/video calls on the Ring network https://ring.cx/en/about/technical (p2p messaging as well) similar to deltachat-core providing models for Email-chat.

**Comment by kskarthik** [comment]
Android webview supports webrtc. So, It's not that hard implementing !

**Comment by testbird** [comment]
Had another look. It seems implementing the interaction in the basic libs (rather than on the frontend side) would be best, to avoid dependencies on specific clients (e.g. QT) and OSes (e.g. android) and have it work equally on all platforms and frontends.

Thus,
=> deltachat-core using libring (not LibRingClient) to set up calls, and
=> libring using deltachat-core for offline messaging and initiating calls to contacts that are not available through the p2p openDHT network  (imap-push wake-up messages).

**Comment by r10s** [comment]
i think we can close this here and discuss things further with a broader audience in the new forum at https://support.delta.chat
