### ISSUE TITLE
Add method to get a range of chat messages

### ISSUE THREAD

**Issue by Jikstra** [deltachat/deltachat-core#447]
A core method which allows us to get a range of messages would likely improve the speed. SQLite is good at getting a range of entries, doing it step by step isn't really performant. At the desktop we currently face the problem that loading more than 30 messages is too slow. We could improve that by doing it directly in the c bindings, but we're still wasting cycles. I don't know how hard this would be to implment, but likely also android would benefit from it, even if only loads 5-10 messages.

**Comment by r10s** [comment]
i just profiled dc_get_msg() a bit: on my machine, ~ 18000 messages per second can be loaded (teseted loading a larger chat with 417 messages in 23 ms).

of course, other computers may be slower, but even 100 times slower seems to be fast enough.

so, i am not sure that adding a function to speed this up will solve the initial problem.

**Comment by Jikstra** [comment]
@r10s nice that you actually tested it, i'm going to test the js bindings. Possible that js is the bottleneck and not c, as i falsely accused.

**Comment by r10s** [comment]
i think this can be closed. currently, there is no actionable item.
