### ISSUE TITLE
Optionally delete messages on the server after receiving

### ISSUE THREAD

**Issue by roth-a** [deltachat/deltachat-core#45]
I noticed that the (possibly encrypted ) messages appear also in my normal email clients inbox (provider gmx).
It would be a good default if the messages are deleted of the server after receiving.
And if someone wants to have the messages also on other email clients he could disable the auto-delete.

**Comment by kollokollo** [comment]
This would mean, that there is not even a need for an extra folter "Chats" on the sever, in that case.

**Comment by r10s** [comment]
Yes, but it would also make Multi-Client hard or even impossible.

**Comment by r10s** [comment]
If I should decide between this feature-request and multi-client, I would vote for multi-client. I think many people would do so.

But maybe this feature could be an option?

However, unless there are some additional volunteers working on this issue, for now, this is out of scope IMHO. However,  the idea stays available via https://github.com/deltachat/deltachat-core/wiki .
