### ISSUE TITLE
Connecting via ssl on mac os x fails

### ISSUE THREAD

**Issue by Jikstra** [deltachat/deltachat-core#451]
Using deltachat-desktop and the deltachat-core cmdline tool, with bot i get the following error:
`[DC_EVENT_ERROR_NETWORK] first=1, msg=Could not connect to IMAP-server disroot.org:993 using SSL. (Error #43)`

```
$ otool -L delta
delta:
        @rpath/libdeltachat.0.dylib (compatibility version 0.0.0, current version 0.0.0)
        /usr/local/opt/libetpan/lib/libetpan.20.dylib (compatibility version 23.0.0, current version 23.0.0)
        /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1226.10.1)
```

**Comment by Jikstra** [comment]
I just notice that this is already reported. https://github.com/deltachat/deltachat-desktop/issues/109

**Comment by ralphtheninja** [comment]
@Jikstra We should try to get more information on _why_ it fails. I.e. more debugging and printf'ing in core, to see where things go wrong.

**Comment by Jikstra** [comment]
> @Jikstra We should try to get more information on why it fails. I.e. more debugging and printf'ing in core, to see where things go wrong.

Don't have the macbook around anymore :( So i currently can't really help on this. But i think @karissa has one, maybe she's interested in helping out?

**Comment by r10s** [comment]
i think, this was fixed in the 35c3 nighlty sessions (or day? there is no huge difference in the assembly hall)  by @dignifiedquire and others.
