### ISSUE TITLE
Autmated wheel releases

### ISSUE THREAD

**Issue by flub** [deltachat/deltachat-core#458]
@hpk42: I thought about a https://m.devpi.net/deltachat/dev index.  One thing to get right
then is to get automatic versioning correct -- i guess setuptools_scm is the latest
way to do this?

**Comment by hpk42** [comment]
i also guess setuptools_scm is the one to try. Last time i tried was 2 years ago or so, ran into some issues. I guess it's ok that each new commit to the repo (which often goes outside python) would cause a new wheel.  one problem might be that we use "py-VERSION" tags and "vVERSION" tags from core in the repo.  So i guess setuptools_scm would pick up either of the two whichever is latest.  This is not quite what we want -- the automatic version should be build solely on the py-* version tag.

**Comment by hpk42** [comment]
we now have automated wheel releases at least for linux, but not automated versioning. Still closing this issue as it's done enough for now (tm).
