### ISSUE TITLE
Bandwidth and space usage

### ISSUE THREAD

**Issue by Ampli-fier** [deltachat/deltachat-core#46]
**Version:** Delta Chat 0.9.4

**My setup:** The account I use in Delta Chat is the same I use with K9.

I sent a file from my phone with K9 to a recipient and attached a large file (3,5 Mb image).
I did not have a chat started with this recipient.

In the background, DC performed a full download of the mail (~5 Mb due to MIME overhead) and this is not noticeable in the DC GUI. Only when I started a chat with this recipient, I saw the message/image.

So, for this scenario the bandwidth usage is doubled, as well as the amount of used spaced on the phone - without noticing it.

**Comment by r10s** [comment]
Another point: Stop trying to send messages continuesly if they cannot be send eg. due to size limits, mailbox full etc. (would eat all mobile data otherwise)

And: sometimes Delta seems to try download old messages on setup

**Comment by r10s** [comment]
Regarding the opener's issue: DC should simply not download full mails for non-chat-contacts.

**Comment by csb0730** [comment]
And maybe there should be a configurable size where messages with large attachments shouldn't get downloaded (see K9). Do only an indication that this has been happen. With that indication user can manually pull the rest from server if desired.

**Comment by r10s** [comment]
Something like that would be definitely cool.

**Comment by testbird** [comment]
Related, and containing more ideas:

* message size and data plans https://github.com/deltachat/deltachat-android/issues/162
* Excessive data consumption in the background https://github.com/deltachat/deltachat-android/issues/185

**Comment by r10s** [comment]
related: https://github.com/deltachat/deltachat-core/issues/156

**Comment by testbird** [comment]
also: https://github.com/deltachat/deltachat-android/issues/102

**Comment by r10s** [comment]
Resending messages as described above is also not optimal when sending a messages fails because of network problems. 

Currently, delta just tries again a little time later (and so on, with larger intervals then).

It would be better to get the exact time the device is connected again and try to send the message out then.

**Comment by r10s** [comment]
i removed this issue from the 1.0 milestone as the _original_ issue just requests to try to download attachments only as needed.
- This is reasonable, but not needed for an 1.0 version.
- more problematic issues as https://github.com/deltachat/deltachat-android/issues/102 are still in the 1.0 milestone.

**Comment by csb0730** [comment]
Shall we open a new issue for "do not download messages automatically with big attachments and show only the subject and a hint about their existance and the size" ?

**Comment by r10s** [comment]
> Shall we open a new issue for "do not download messages automatically with big attachments and show only the subject and a hint about their existance and the size" ?

i think, this subject is sufficient.

also the advice "do not download messages automatically with big attachments and show only the subject and a hint about their existance and the size" is complicated to implement (new flows in the lib and in the ui) and uncomfortable to the user (what, if he is offline when he sees the message).
Also, through encryption, the subject may only be available if the message is downloaded completely. This is true at least for mails from Enigmail, K-9 and Delta (they support memoryhole).
There may be even more cornercases to handle, so, in general, this approach seems not to help in keeping things simple and reliable.

however, nevertheless, there is room for optimization, i could imagine the following:
- **skip the extra imap-upload** and add SELF as a recipient in the SMTP-upload  
(this way, we get the mails just sent from the INBOX-IMAP-IDLE - we also got them before every ~ 30 minutes when Delta does a full-sync)
- avoid downloading these messages again: **check if the Message-ID is already known** (the Message-ID is typically in the unencrypted part)

this method would not alter the ui or the api flow - and would cut the upload bandwidth in half.

**Comment by csb0730** [comment]
I think that these are good proposals.

But isnt't it possible to determine an email's size before downloading?

I mean, maybe it isn't possible to decide what details are into a mail
without downloading it but I think it is possible to see if a mail is
only some simple text or a big attachment is there. Only with rough size
(size is some KB or some MB).

Here I speak about the "some MB" emails :-)


Am 11.07.2018 um 11:24 schrieb Björn Petersen:

**Comment by r10s** [comment]
>  But isnt't it possible to determine an email's size before downloading?

yes, this is possible. the proposal was about the "low hanging fruits" :)

**Comment by r10s** [comment]
the opening issue is targeted by https://github.com/deltachat/deltachat-core/milestone/2 in general and https://github.com/deltachat/deltachat-core/issues/370 in special.

closing this here here, of course, the discussion of related topics can go on in the new support forum at https://support.delta.chat
