### ISSUE TITLE
Bundled libetpan: Cannot convert 6 bytes from "us-ascii" to "utf-8"; errorcode is 1

### ISSUE THREAD

**Issue by steils** [deltachat/deltachat-core#468]
If I build deltachat-core with bundled libetpan, I get

```
$ ./delta 
[Warning] Cannot convert 6 bytes from "us-ascii" to "utf-8"; errorcode is 1.
delta: ../cmdline/stress.c:505: stress_functions: Assertion `strcmp(buf1, "testäöü.txt")==0' failed.
Aborted
```

If I use system libetpan it doesn't happen.
[strace.log.txt](https://github.com/deltachat/deltachat-core/files/2661410/strace.log.txt)

I also receive such messages in `deltachat-desktop`, I'm not sure if it's related or it's a different issue.
```
main.js:36 100 0 "Receiving message INBOX/175088..."
main.js:36 300 0 "Cannot convert 6632 bytes from "us-ascii" to "utf-8"; errorcode is 1."
main.js:36 WARNING Cannot convert 6632 bytes from "us-ascii" to "utf-8"; errorcode is 1.
```

**Comment by flub** [comment]
I'll take a look at iconv sometime

**Comment by r10s** [comment]
@r10s cool :) and greetings from 35c3 :)

**Comment by r10s** [comment]
i think iconv is added to the meson build script in between and this should be fixed - if not, feel free to re-open.
