### ISSUE TITLE
Please Help Me.

### ISSUE THREAD

**Issue by atashin** [deltachat/deltachat-core#472]
Hi , i get this Error :

D:\Morse\MessengerProj\jni>ndk-build
[armeabi] Compile arm    : messenger.1 <= mrjnimain.c
In file included from D:/Morse/MessengerProj/jni/./mrjnimain.c:30:0:
D:/Morse/MessengerProj/jni/openssl/include/openssl/aes.h:1:1: error: expected id
entifier or '(' before '.' token
 ../../crypto/aes/aes.h
 ^
In file included from c:\android_sdk_studio\android-ndk\platforms\android-14\arc
h-arm\usr\include\sys\time.h:33:0,
                 from c:\android_sdk_studio\android-ndk\platforms\android-14\arc
h-arm\usr\include\sys\select.h:32,
                 from c:\android_sdk_studio\android-ndk\platforms\android-14\arc
h-arm\usr\include\unistd.h:34,
                 from D:/Morse/MessengerProj/jni/./mrjnimain.c:31:
c:\android_sdk_studio\android-ndk\platforms\android-14\arch-arm\usr\include\linu
x\time.h:48:18: error: field 'it_interval' has incomplete type
  struct timespec it_interval;
                  ^
c:\android_sdk_studio\android-ndk\platforms\android-14\arch-arm\usr\include\linu
x\time.h:49:18: error: field 'it_value' has incomplete type
  struct timespec it_value;
                  ^
make: *** [D:/Morse/MessengerProj/obj/local/armeabi/objs/messenger.1/./mrjnimain
.o] Error 1

What Should We Doo ?
Plese Help Me.

**Comment by ralphtheninja** [comment]
Hi. Can you please tell us what you're trying to do?

**Comment by atashin** [comment]
when i try to compiling Project in android studio  , i get same error !

**Comment by atashin** [comment]
Any Body Can Help , By Video tutorial for compiling?

**Comment by ralphtheninja** [comment]
@atashin Maybe have a look at how our android app is doing this https://github.com/deltachat/deltachat-android-ii

**Comment by r10s** [comment]
@atashin the log seems to come from the telegram-android-app which is outdated and will be replaced by the one linked by @ralphtheninja 

so, if you want to try to compile the android-app, you should use the new one.

there is a readme with instructions, however, not sure if they are helpful for windows :)

**Comment by r10s** [comment]
closing this issue as it is not really core but more windows/android related.
