### ISSUE TITLE
DeltaChat and encryption

### ISSUE THREAD

**Issue by adbenitez** [deltachat/deltachat-core#474]
Delta Chat comes with the encryption option enabled by default and hidden in the advanced submenu in the app settings, in some countries the use of encryption is illegal, also encrypted emails seems to be much more big in size. shouldn't this be disabled by default??

- Delta Chat Core Version: 0.20.0

**Comment by violoncelloch** [comment]
Delta chat is a chat application with a focus on privacy, so I don't think it would make sense to disable it by default. Delta chat wants people to use encryption. As the right to privacy is a key human right (see UN's "Universal Declaration of Human Rights" and "Right to Privacy") a nation prohibiting encryption is actually violating human rights and therefore acting illegally.

**Comment by ralphtheninja** [comment]
There's a forum for discussing these things over at https://support.delta.chat/. Since this is not an actionable item I'm closing this.

**Comment by karissa** [comment]
Even if there was an option for this, my understanding is having an app on your phone that can possibly *do encryption at all* could be grounds for your investigation in countries that have these laws.

**Comment by karissa** [comment]
So in those cases, as I understand, they use plain-text email with ephemeral accounts and other such hacks to get around surveillance.

**Comment by adbenitez** [comment]
@violoncelloch you are right, perhaps I should scream that while I am dragged to a cell and the few remaining human rights are taken away from me ;-)
But you are right those countries are simply wrong.

**Comment by STPKITT** [comment]
You can always pretend to know nothing about encryption as most non-tech people do anyway while using automatically encrypted messaging systems.
