### ISSUE TITLE
when to move messages from INBOX to DeltaChat folder?

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-core#475]
pr #473 we prepare a second  thread that allows to watch a second folder which is needed esp. in a multi-client setup. the twp thread already work as desired (which, btw is compicated enough due to a lot of corner cases ...)

the next step would be to really move chat-messages from the INBOX to the DeltaChat-folder (called MVBOX internally).

the question, that popped up here is _when_ to move messages?

1. before `dc_receive_imf()`
   -  messages will take more time until it pop ups in delta (MVBOX-idle has to wake up)
   - when moved, there is a good chance,
      all clients can download the message without further disturbance
2. after `dc_receive_imf()`
    - messages will pop up as fast as possible in delta
    - other clients may get problems as they may be still downloading 
      while the first one is ready and moves the message away
    - this could be mitigated by a timeout, eg. messages could be
      moved 10 seconds after arrival
      this might also be nicer when other MUAs are open while
      delta-chatting: instead of a fast flickering,
       there is a chance for the user to read eg. the subject
3. when `dc_markseen_msgs()` is called - this is what the old f-droid version did
    - i think this is confusing for the user when using a MUA and not delta as the inbox may be flooded during this time. i think this is part of the whole problem, maybe even larger than the question _which_ messages to move.

i have a slight preference for 2. also as this makes it a little easier just not to just the MVBOX and go for a dedicated account. 

cc @hpk42

**Comment by testbird** [comment]
As explained https://github.com/deltachat/deltachat-core/issues/422#issuecomment-443468645 I expect the second option to work the best. With the first, the races and timeouts of the clients would affect the user experience.

**Comment by testbird** [comment]
However, the alternative marking+moving (AltMarkMove) scheme may be beneficial, to make chat messages not show up in classic MUAs (in the due-list of emails the user still **has** to read).

Then all chat messages may be flagged "seen" in step 1. above (as a fallback for optional server filter rules that can even make messages "seen" before they appear) and avoid notifications in classic MUAs). Moving may than happen when message was shown (3.), which also indicates to other deltachat clients that the message was shown.

**Comment by testbird** [comment]
This was the report about another benefit of marking chat messages as read ASAP: https://github.com/deltachat/deltachat-core/issues/263

Is there really a need for the second MVBOX imap-idle thread when chat messages are immediately marked as "seen" and the moving indicates the "shown in deltachat" state to other clients? Can you provide an example, because I currently don't see why it would be needed.

**Comment by happyreacer** [comment]
in my case work 3 but 2 would be okay too

**Comment by testbird** [comment]
> I'd maybe first do things without a delay and see how this plays out.

Random clients that are late will fail, require a second idle connection, and only notify the user noticeable later (after the move) in comparison to other devices (e.g. in a room). The contrary to working reliable.

**Comment by testbird** [comment]
The Problem of flags with multiple clients pointed me to https://tools.ietf.org/html/rfc7162#page-4

If that is not supported by the server or deltachat, the alternative making and moving (when displayed) could maybe be a backwards compatible alternative based only on basic message presence changes.

**Comment by adbenitez** [comment]
typo in the title: "when to move **messags** from INBOX to DeltaChat folder?"
