### ISSUE TITLE
understanding "groups" (p2p recipient group vs. mailing list server)

### ISSUE THREAD

**Issue by testbird** [deltachat/deltachat-core#49]
Closed services try to control the groups, and users become to believe there is something they would need to join, instead of define for themselves.

Now, with delta.chat, are the groups "distribution lists" managed by each user individually, picked up by other persons delta.chat?

The reason for questioning the "groups" term: It may support a wrong idea about delta chat, especially for users used to central services.

Maybe finding another word like "distribution list" helps people better to understand email chat programs. To see how email chat can also be very nice to work with email lists or forums with email integration (like the github issues).

"address lists"?

**Comment by r10s** [comment]
I'm not sure if I really got your question, but I try :)

Yes, in Delta Chat, groups are created by any member for some other members. There is no central place that even knows a group exist. All members of a group have the same right in the group.

But I think the name "Group" is just fine, they work in the same way as in other messengers, if the user uses the name "Group" there is few to explain.

**Comment by testbird** [comment]
Note that, setting up central email list and forum servers is a hard problem for simple end users, and surely a reason for the success of IRC and other messengers.

Forums increased interaction and simplified access compared to email list archives, but still hard to set up.

But note the importance of public messaging archive/lists/boards, that is still missing in email chatting.
I noticed you started blog posting to freiendi.ca, may such things be the way to handle groups interaction?
I.e. one adds the address of the friendica? timeline (like chosing the list/forum) to post messages to a browsable and searchable forum?

**Comment by testbird** [comment]
Ok thanks, how do you intend to make clear (name) the difference between a centrally or collaboratively managed group, i.e. one would "subscribe" to (like email list, forum) and also gets the past conversation, and local address lists.

Is the implementation something maybe better known and explained as "circular letter", addressed to others as well as yourself?

I think "circulation groups" is what I'd understand nicely.

**Comment by testbird** [comment]
IMHO even better: "ciruclation lists"

**Comment by testbird** [comment]
`*testbird* added *r10s* to the recipient group issue49`

From my search results "distribution lists" seems to be the technical term for client based sending of email, and thus the chat messages.

But practically, I think "recipient groups" convey the correct (decentral) meaning. And using that should make a notice to a reply like the above self-understandable

**Comment by haeckser** [comment]
I don't know why we should not name it a group if it is a group ...
The idea is to make it simple and intuitive and a group in a messenger is a communication with a group of contacts with one post - like Delta chat is doing.
How it is named in WhatApp or all other Messengers - I assume Group ...
We are not talking about a forum or a mailing list. The user is using a messenger (that is based on email, yes, but that is not the users main idea). 
And again - names are nothing, but using the same as others will make orientation for new users easier. Important is that we describe it exactly in help / documentation to allow a user to understand in detail what is the behavior he can expect

**Comment by testbird** [comment]
Words carry meaning and allow to explain well. The question was what kind of group, it is just an important feature of delta chat that it can talk to regular email users.

My conclusion above was "recipient group" which should convey a proper meaning for both worlds. (decentral list of recipients, not a mailing list/relay)
