### ISSUE TITLE
dc_perform_*() crash on ios

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-core#496]
the `dc_perform_*()` functions crash from time to time in ios.

the crash as such is an EXC_BAD_ACCESS (invalid pointer) deep in libEtPan eg. at `mailstream_low_read() -> mailstream_low_cfstream_read() -> wait_runloop()` triggered eg. by `dc_perform_imap_jobs()`. 

the crash seems not to be related to the new MVBOX/SENDBOX threads.

as i've not seen _this_ error on android/cli/desktop, it may be related to the slightly different usage of the  `dc_perform_*()` functions - that are currently [_not_ thread-safe](https://c.delta.chat/classdc__context__t.html#a4213ea33d3422c7764a897961ba896fe):

- in android/cli/desktop `dc_perform_*()` are _only_ called inside a loop from a separate thread
- in ios, `dc_perform_*()` are called _additionally_ from a timer

my assumption is that it may happen that the thread is stopped and _while_ stopping, the timer may occur. or we're in the timer-perform-jobs and the app goes to foreground and starts a thread with the perform-loop.

@dignifiedquire @hpk42 makes sense? if so, i would add a protection against calls from different threads to the `dc_perform_*()` functions - i think it makes more sense to add this protection to the core than to the ui.

**Comment by hpk42** [comment]
sounds like a workable hypothesis and suggestion to guard dc_perform against MT

**Comment by r10s** [comment]
iirc @dignifiedquire reported that this problem is no longer valid in ios due to re-ordered calls of the dc_perform_*() functions.

as the doc already states that the dc_perform_*() functions each have to be called from within the same thread, i think we can close this issue for now.

wrt crashes in android: they were probably related to a different problem that came over my way yesterday and that is fixed here: https://github.com/deltachat/deltachat-android-ii/commit/3e79719ac4f8c5ec23088ad41de7a62694e91f14#diff-2321e962cf09c311842f0eb44a3edbdbR65
