### ISSUE TITLE
Allow generating qr codes for normal groups

### ISSUE THREAD

**Issue by Jikstra** [deltachat/deltachat-core#499]
Should also allow to scan them and join the group.

**Comment by r10s** [comment]
i think setup-contact is already fine as it does not enforce encryption and is not related to group.

imo from the view of the core, its basically [`dc_get_securejoin_qr()`](https://c.delta.chat/classdc__context__t.html#aeec58fc8a478229925ec8b7d48cf18bf) that should accept also normal-group-ids as the second parameter, and of course, on the otherside `dc_check_qr()` and `dc_join_securejoin()` must accept such qr-codes
