### ISSUE TITLE
could not start from backup

### ISSUE THREAD

**Issue by haeckser** [deltachat/deltachat-core#50]
To sync my phone with the tablet, I uninstalled delta on tablet, made a backup on phone and sent it via bluetooth to the tablet. Filename is delta-chat-2017-10-24.bak.
Moved it from bluetooth folder to Download folder and started delta chat after reinstallation.
Got message that no backup to import was found and that I should copy the backup file to /storage/emulated/0/Download folder where it is in fact located :-(

Permissions of Download folder is drwxrwx--x
Permission of backup file in Download folder is -rw-rw---- (same as all the other files in download folder have)
Owner is 00000 - 'root' and group 01015 - 'sdcard-rw'.

What is wrong ?
File exists and permissions looks OK
Checks in code must be fulfilled (patter delta-chat-*.bak)

**Comment by Ampli-fier** [comment]
Might be that Android sometimes has problems with "mounting". A restart of the tablet should help in this case.

**Comment by haeckser** [comment]
Wow - the second restart did it :-)
Thanks for prompt reply - I will close the issue now

**Comment by r10s** [comment]
perfect :)

**Comment by streaps** [comment]
Restarting the phone did indeed work, but maybe it has nothing to do with rebooting Android and why should it. I can access the bak file just fine from the file browser, the adb shell and over USB.

I tried it again:

1. uninstalled Deltachat
2. restarted the phone
3. installed Deltachat
4. ran Deltachat
-> backup not found
5. killed the running Deltachat app
6. started Deltachat again
-> backup found

It looks like Deltachat just doesn't find the bak file on the first run after installation.

Should this issue reopened until we have figured out the exact problem?

**Comment by r10s** [comment]
> Should this issue reopened until we have figured out the exact problem?

I agree, however, I have this feeling that this more an android issue. 

The code for scanning for backups seems to be rather straight-forward https://github.com/deltachat/deltachat-core/blob/master/src/mrmailbox_imex.c#L1341 - and works at least on all my testing devices.
(otoh i had similar issues when trying to get files from the smartphone via usb, independent of delta chat, files created on the smartphone were just not visible, but i cannot remember exactly; maybe this is releated)

But maybe there are some workarounds; this would require some research; I am not free for

**Comment by r10s** [comment]
> I have this feeling that this more an android issue.

yes, this is an android-issus (that i cannot reproduce here).

just cleaning up things, if this issue exist, we should re-open it at https://github.com/deltachat/deltachat-android/ or https://github.com/deltachat/deltachat-android-ii/
