### ISSUE TITLE
Messages starting with a '>' are cropped

### ISSUE THREAD

**Issue by ralphtheninja** [deltachat/deltachat-core#517]
If you start a message with `>` that text will be cropped or abbreviated:

![screenshot from 2019-01-11 13-52-31](https://user-images.githubusercontent.com/308049/51034833-4c483380-15a8-11e9-8af6-5402533b33b9.png)

It needs to stop doing this if we want to implement markdown support in desktop.

**Comment by Jikstra** [comment]
This is also annoying for forwarded/quoted messages. Only the notice about the quote from the sender is readable, everything else is cropped.

**Comment by ralphtheninja** [comment]
> however, otoh, there is no need to do this from delta-to-delta.

Maybe we can pass a flag when reading messages?

**Comment by adbenitez** [comment]
perhaps making possible to expand the hidden content on click would be useful...

**Comment by r10s** [comment]
for sure, however, this is out of scope of this issue :)

**Comment by Jikstra** [comment]
What would be nice if we wouldn't completely replace it with [...] but maybe with [this is the text of the beginning of the quote...] and some way to visualize the quotation. This could already be the first step for threads. But maybe the ui should handle this and the core should only tell at which positions quotes are and if the can get related to another message in this chat? I guess this would be very nice and (without the relating thing) shouldn't be too hard to implement. Especially if a click on the quote would just expand it.

**Comment by r10s** [comment]
might be if the quotes are intentional and meaningful.

however, most quotes _i_ see from other muas are just crap. ppl hit reply-all and the full quote is just added. often this is done after weeks without any relationship to the quoted message. not sure if we should build our own threads upon that.
