### ISSUE TITLE
Improve multi-device support

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-core#52]
Multi-device support is handled rudimentary, but there is many stuff that is not synced. Not sure if everything is really needed and possible, but I think we'll collect these things here:

- [x] Messages send on DeviceA do appear on DeviceB if the chat exists on both devices (after a delay of ~30 minutes)
- [x] check how this delay can be reduced - targeted by https://github.com/deltachat/deltachat-core/milestone/2
- [X] Chats created from external do appear on DeviceA and DeviceB
- [X] MDNs should not be sent multiple times from multiple Devices
- [x] Support Autocrypt Key Transfer 
- [x] Chats created on DeviceA should also be created on DeviceB automatically (via https://github.com/deltachat/deltachat-android/issues/148)
- [ ] Check if messages deleted on DeviceA should/can also be deleted on DeviceB
- [ ] Check if notifications shown on DeviceA should/can disappear if the message is read on DeviceB and the message on DeviceA should be marked as read
- [ ] Check if archived/sticky chats, maybe starred messages should/can be synchronized
- [ ] Check multi-device, oob-verification and verified-groups

This issue is currently _not_ part of the Milestone 1.0.0 as this would delay the whole thing too much.

**Comment by csb0730** [comment]
See my last comment for https://github.com/deltachat/deltachat-android/issues/148

Going on here ...

**Comment by r10s** [comment]
see also https://github.com/deltachat/deltachat-android/issues/143

**Comment by testbird** [comment]
Copied @csb0730's closed comment  https://github.com/deltachat/deltachat-android/issues/148#issuecomment-341862630 and pasted this here to keep the info:

>to keep it simple:
> * Just let the DC show every message which is new for the local client (not existent in local database)
> * If "From:" header contains own configured address show it as outgoing, but show it. If chat for incoming message not exists (at the device X) I would vote for: show it in "contact requests". From there user can start chat if desired.
> * And my special wish (again ;-) ): If "To:" header contains own configured address: show it a) in chat where it comes from or b) in "contact requests" when own configured address is used in "From:". From there chat can be started if desired. This will violate no convention. Even at mail server You see a new message in INBOX in this case!
>
> I think these three points will ease the multi device support.

**Comment by testbird** [comment]
(from #164)

If it can't be avoided, mulit-client support might later require deltachat to have a special status message in the email chat folder on the server, e.g. for better coordination of such maintenance work.

**Comment by r10s** [comment]
closing this for now, the most important things are targeted by https://github.com/deltachat/deltachat-core/pull/407 we'll see how this works out and can created smaller issues for things that can be really worked on realistically.

for discussion in general, the forum at https://support.delta.chat should be used.
