### ISSUE TITLE
sentboxThread kills Android app

### ISSUE THREAD

**Issue by Ampli-fier** [deltachat/deltachat-core#527]
- Delta Chat Core Version: 0.39.0 / Android-II 0.98.2 (Device with Android 9)
- Expected behavior:
- Actual behavior: DC for Android is crashing
- Steps to reproduce the problem:
- Screenshots:
- Logs:

Android app gets killed by:

`Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0xb in tid 29834 (sentboxThread)`

Full Log: [gist](https://gist.github.com/Ampli-fier/cfbf21866c7bf20cdeda0f1ec099981b)

**Comment by r10s** [comment]
might be related to his change https://github.com/deltachat/deltachat-core/commit/c74b9d8102c033f86537ec84bfae93090706d87e
