### ISSUE TITLE
Create recipient group thread when sender gets confirmed

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-core#53]
Messages from unknown senders go to the "contact requests", this is also true for group messages. 

If later, the contact is confirmed, this does not automatically create the group (however, it will be created on the next group message then)

**Comment by testbird** [comment]
Isn't this always relevant if one gets added to a group by someone else and one wants to reply to the group (but  no group thread exists yet)?

**Comment by r10s** [comment]
Yes, if someone is added to a group, in view of the added person, it is a group creation. So, yes, there is also the question if the person who added you must be known in some way or just any of the group members.

**Comment by testbird** [comment]
maybe rename this issue to "create recipient group thread when sender gets confirmed"

**Comment by r10s** [comment]
Thank you, in fact, this is more precise.

**Comment by r10s** [comment]
fixed with the commits in PR #115
