### ISSUE TITLE
remove "Sent from my iPhone" and other not clearly marked footers

### ISSUE THREAD

**Issue by thenktor** [deltachat/deltachat-core#530]
Hi,

messages sent from iOS devices have the following pseudo signatures:

- Sent from my iPhone
- Sent from my iPad
- Von meinem iPhone gesendet (German)
- Von meinem iPad gesendet (German)

Sadly Apple devices don't add a real signature but just add this as last line to the email. I think these can be removed/hidden.

**Comment by r10s** [comment]
i transferred this issue to the core as there is nothing android can do about this.

however, i would also suggest to close it, it's more a misbehavior or samsung/apple/whatever, trying to solve this with some kind of logic might also easily result in some strange side-effects that need maintenance and bug-fixing again then. i do not think that we should enter this area.

**Comment by r10s** [comment]
closing this for now
