### ISSUE TITLE
detect quotes if not clearly marked as such by the sender 

### ISSUE THREAD

**Issue by singpolyma** [deltachat/deltachat-core#531]
Depending on the style of quoting. Screenshot attached.
![30504055-553dd064-9a32-11e7-8c07-1cbc77f23c32-ii](https://user-images.githubusercontent.com/9800740/30505861-9622372e-9a77-11e7-92ae-2bf272eb5565.png)

**Comment by r10s** [comment]
transferred to core as there is nothing android can do about this issue.

similar to #530, i think it is hard to detect things that are not much more as plain text and detection routines might result in false-positives that need additional maintenance then. i would suggest to close this issue.

**Comment by r10s** [comment]
closing this for now, we can re-open as needed. or better create some more concrete instructions about what to do.
