### ISSUE TITLE
Same message downloaded more than once

### ISSUE THREAD

**Issue by csb0730** [deltachat/deltachat-core#532]
- Delta Chat Core Version: v0.20.0

In case of ignoring a message because it belongs to a mailing list, it's fetched again some minutes later.

- Logs:

> © 2017, 2018 Delta Chat contributors
> 
> ...
> 
> Using Delta Chat Core v0.20.0, SQLite 3.23.1-ts1, libEtPan 1.8, OpenSSL 1.0.1t. Compiled Oct  7 2018, 22:52:45 for 32 bit usage.
> 
> Log excerpt:
> 
> 12:34:21 IMAP-IDLE ended.
> 12:34:21 IMAP-jobs started...
> 12:34:21 IMAP-jobs ended.
> 12:34:21 IMAP-fetch started...
> 12:34:23 Receiving message INBOX/18355...                   <=== 1. download
> 12:34:23 Message belongs to a mailing list and is ignored.  <=== Is this a problem?
> 12:34:24 Message has 1 parts and is assigned to chat #3.
> 12:34:24 1 mails read from "INBOX".
> 12:34:24 0 mails read from "INBOX".
> 12:34:24 IMAP-fetch done in 2852 ms.
> 12:34:24 IMAP-IDLE started...
> 
> ...
> 
> 12:46:23 IMAP-IDLE ended.
> 12:46:23 IMAP-jobs started...
> 12:46:23 IMAP-jobs ended.
> 12:46:23 IMAP-fetch started...
> 12:46:23 IMAP stream lost; we'll reconnect soon.
> 12:46:23 Cannot get folder list.
> 12:46:23 IMAP stream lost; we'll reconnect soon.
> 12:46:23 Cannot fetch message list from folder "INBOX".
> 12:46:23 0 mails read from "INBOX".
> 12:46:23 IMAP-fetch aborted, starting over...
> 12:46:23 IMAP disconnected.
> 12:46:27 IMAP-server xxxxxxxxxxxx:993 SSL-connected.
> 12:46:27 IMAP-login as xxxxxxxxxxxxxxxxxx ok.
> 12:46:28 Receiving message INBOX/18357...
> 12:46:29 Message sent by another messenger.
> 12:46:29 Message has 1 parts and is assigned to chat #105.
> 12:46:29 1 mails read from "INBOX".
> 12:46:29 0 mails read from "INBOX".
> 12:46:29 IMAP-fetch done in 5490 ms.
> 
> ...
> 
> 12:50:52 IMAP-jobs ended.
> 12:50:52 IMAP-fetch started...
> 12:50:52 Receiving message INBOX/18355...         <=== 2. download !!!!
> 12:50:52 Message already in DB.
> 12:50:52 1 mails read from "INBOX".
> 12:50:52 0 mails read from "INBOX".
> 12:50:52 IMAP-fetch done in 380 ms.
> 12:50:52 IMAP-IDLE started...
> 

This multiple download seems to be appear with every message too, which has been appended or moved to IMAP/DeltaChat dir !

**Comment by r10s** [comment]
i think the double-download is not related to mailing-list or not. mailing-list-messages are currently not shown or several reasons, see https://github.com/deltachat/deltachat-core/issues/125, however, in general, after downloading, they are stored in the database similar to other messages.

also, delta chat detects that the message on the 2. download is already there - the server gave us the message again for whatever reason, this may happen eg. by race conditions that messages are returned twice.

however, in between, delta chat does not really download the message again but fetches the headers first and downloads only messages that are not yet in the database.

so, we cannot prevent the server returning messages to us we've already seen, but we can avoid downloading these message, which is already done.

closing as there is no actionable item left.
