### ISSUE TITLE
Sometimes messages aren't correctly synchronized on all devices

### ISSUE THREAD

**Issue by Jikstra** [deltachat/deltachat-core#535]
What happens to me is that sometimes messages which i received on my mobile aren't shown on desktop.
Enabling/Disabling watch deltachat folder option fixes it sometimes.

**Comment by hpk42** [comment]
This is to unspecific to remain an active issue i think.  If you encounter it again, please specify versions and scenarios.  It's generally clear and obvious that multidevice-sync needs some love.
