### ISSUE TITLE
DC shows random? mails as chat

### ISSUE THREAD

**Issue by ghoffart** [deltachat/deltachat-core#547]
- Delta Chat Core Version: 0.99.0-PREVIEW (macOS)
- Expected behavior: DC shows only accepted chat initiated messages
- Actual behavior: DC shows some non-DC-related messages from mail inbox as chat; none of the mail recipients are DC users; I never accepted a chat with the senders and other recipients of that email
- Steps to reproduce the problem: ?
- Screenshots: n/a
- Logs:

**Comment by Hocuri** [comment]
Did you grant the contacts permission to Delta Chat? If yes: have a look here: https://delta.chat/en/help#which-messages-do-appear-in-delta-chat

The contacts request feature is mainly intended to avoid showing spam, newsletters, ...

**Comment by violoncelloCH** [comment]
@ghoffart are these "random" mails "(ad-hoc)groups" eg. mails with multiple other recipients?

**Comment by ghoffart** [comment]
I have used DC to write to only 2 (single) email addresses before (both jikstra). The “random” ones have CC:s, but are completely unrelated to DC.

A friend of mine has the same behaviour. He chatted only with me up until now, but now a ”random” email popped up in DC.

**Comment by violoncelloCH** [comment]
If these randomly popping up mails are all ones with multiple recipients (e.g. CC:s), this is actually a feature called ad-hoc-groups, which automatically creates groups to allow you chatting to a mail conversation with multiple participants using an other MUA...
maybe these ad-hoc-groups should only be created if one selects such a message in contact requests and starts a chat manually from there?

**Comment by r10s** [comment]
this is targeted by https://github.com/deltachat/deltachat-core/pull/588 and https://github.com/deltachat/deltachat-android/pull/742
