### ISSUE TITLE
Delta Chat doesn't move messages sent from/to peers using another MUA

### ISSUE THREAD

**Issue by adbenitez** [deltachat/deltachat-core#551]
DC don't move to INBOX/DeltaChat folder messages I sent to peers that don't use DC or messages they send to me, if users are chatting with that contact inside DC they expect they self-bcc copy of the messages moved to the DeltaChat folder as well as  the replies of the users to that chat.
**UPDATE: I started chatting with a friend, he was using a classic MUA, then I managed to bring him to the Delta Chat side ;) and the messages still aren't moved form my INBOX, this is an important bug, I do also recommend to add it to the PLayOne project.**

- Platform (android/blackberry/anbox): Android 6.0
- Device:BLU
- Delta Chat Version: 0.100
- Expected behavior: all chats messages are moved to the DeltaChat folder, doesn't matter if the chat is with a DC user or with a user using another MUA.
- Actual behavior: only chats with DC users are moved, so there are some incompatibility issues, since messages have a cost to me and I can't re-download them again in my inbox with other MUA, also the inbox get cluttered of unwanted messages.
- Steps to reproduce the problem: start chatting with an email address that have never sent an email to you using DC

**Comment by adbenitez** [comment]
@r10s sorry since I am only using the android app sometimes I forget about this repo, I will try to be more careful about putting issues in the right repo...

**Comment by sketet** [comment]
same for me, all the messages are in the inbox, sent and received.
it should be preferable that all the messages go to the DeltaChat folder.

**Comment by violoncelloCH** [comment]
I'd suggest to add this to the Project PlayOne, because it already happens if only one person in a chat  once sends an email from another MUA and it's quite confusing (at least in a shared account setup).

**Comment by adbenitez** [comment]
@violoncelloCH true!!! +1 updated the post

**Comment by r10s** [comment]
i think this is targeted or at least mitigated by https://github.com/deltachat/deltachat-core/pull/588 and https://github.com/deltachat/deltachat-core/pull/580

**Comment by violoncelloCH** [comment]
yep, it works now as I would expect it with v0.200.0 (also chat's from and to users I write and recieve normal email to/from get moved to the DeltaChat folder)
🎉

**Comment by adbenitez** [comment]
yes, still there are a situation where this fails, my connection seems to fail somehow and messages that were in the moving process are never moved, so they stay in the inbox, this happens often to me, I still must keep erasing them manually, but well this is a progress! 🎉
