### ISSUE TITLE
Improve automatic configuration

### ISSUE THREAD

**Issue by adbenitez** [deltachat/deltachat-core#552]
Delta Chat autoconfiguration seems to be smart enough, sadly it is a bit broken.
My server doesn't provide an autoconfig xml but it uses well know addresses and ports, so when I input "myusername@nauta.cu" and my password and leave empty all other fields, Delta Chat automatically try to use my email as user and "imap.nauta.cu"/"smtp.nauta.cu" for the IMAP/SMTP server, also the port is automatically "detected" based on the protocol and security method used, but the only thing that is broken is the IMAP Security setting(and probably SMTP Security also), I have to manually set it to STARTTLS, since Delta Chat only tries SSL and shows a toast with an error of ssl connection failed "imap.nauta.cu:993" instead of trying STARTTLS. This is the only thing preventing users to have an awesome user experience and providing only email and password without having to open advanced settings and filling all field since they never gonna guess that only disabling Security will work.
This have nothing to do with autoconfig xml files which is not provided by this server, that is only needed if the server use not well know ports  imo, and a MUA like thunderbird is able to automatically detect this settings without the autoconfig xml, as shown in the screenshots.

- Platform (android/blackberry/anbox): Android 6.0
- Device: BLU
- Delta Chat Version: 0.100
- Screenshots:

![auto-config](https://user-images.githubusercontent.com/24558636/51931034-e7734280-23c9-11e9-8ff2-7114c6c694eb.png)

![autoconfig-results](https://user-images.githubusercontent.com/24558636/51931054-f2c66e00-23c9-11e9-8b7c-8271707998f3.png)

**Comment by r10s** [comment]
added a pr that also tries STARTTLS on port 993

**Comment by adbenitez** [comment]
well forgetting about plain auth,
afaik STARTTLS's default port is 143, why to try 993 which is for SSL??

**Comment by r10s** [comment]
> why to try 993 which is for SSL

afaik there are severar providers using this combination.

however, i've modified the pr to check STARTTLS/143 as well.

**Comment by adbenitez** [comment]
didn't knew about it, anyway thanks for adding support for 143, and about PLAIN isn't common, I don't even know why Nauta supports plain instead of SSL :/
with this check now Nauta users can setup DC just providing email and password, this is nice!
