### ISSUE TITLE
References-Header gets too long

### ISSUE THREAD

**Issue by Hiboycubano** [deltachat/deltachat-core#555]
In the message header of every remains "references" with a list of ID of every message of the conversation.
I think this is a protocol overload very important to take in count.
Messages start having the normal overload of cypher but after a week a 1 line message takes over 19KB in both directions

**Comment by r10s** [comment]
thanks for pointing this out, we also noticed this already and thinking about a solution.

**Comment by adbenitez** [comment]
I think this is a bit messy, for reference here I post an email which body content is only 1 emoji: "😆"
this is the header for that email!!!:

Return-Path: <A FRIEND@nauta.cu>
Delivered-To: <ME@nauta.cu>
Received: from smtp-gw04.enet.cu ([172.29.8.34])	by mail-backend71.enet.cu (Dovecot) with LMTP id Z9aGCcgDV1xubgAAwYu4aQ	for <ME@nauta.cu>; Sun, 03 Feb 2019 10:26:04 -0500
Received: from amavis5.etecsa.net (unknown [172.29.8.236])	by smtp-gw04.enet.cu (Postfix) with ESMTP id B5B7C180004F;	Sun,  3 Feb 2019 10:25:53 -0500 (CST)
Received: from smtp.nauta.cu ([172.29.8.248])	by amavis5.etecsa.net  with ESMTP id x13FQ4Oi008803-x13FQ4Oj008803;	Sun, 3 Feb 2019 10:26:04 -0500
Received: from localhost (unknown [10.64.197.84])	by smtp.nauta.cu (Postfix) with ESMTPA id 492FF9F187;	Sun,  3 Feb 2019 10:26:04 -0500 (CST)
Date: Sun, 3 Feb 2019 10:25:43 -0500
From: Gerardo <A FRIEND@nauta.cu>
To: adb <ME@nauta.cu>
Message-ID: <Mr.avArwVM_JGI.F0q19hkCuCL@nauta.cu>
In-Reply-To: <Mr.bfz_Y9tZSNP.t2PFPKm85bM@nauta.cu>
References: <Rf.JqKH4jabc1i@mr.thread> <Mr.uGGQAu4jK8M.WWiPoiksNEc@nauta.cu> <Mr.hu-MhktdzAC.CQxkPbjyqYx@nauta.cu> <Mr.NEZUrpOPxNi.5IQn42DoMEv@nauta.cu> <Mr.RaimQXxX69-.T0HNAD3a7y2@nauta.cu> <Mr.C7pr-pL7813.Xgo98_jeZD_@nauta.cu> <Mr.IWPRycqFo7t.gx22i-DFdW9@nauta.cu> <Mr.XPIQAFqZXv9.0hkjQ5Am6xN@nauta.cu> <Mr.-ohlykTcV3-.ZivZovZuZJL@nauta.cu> <Mr.uE1NTjoAEeQ.HqL8X3EBNoF@nauta.cu> <Mr.nIVizxMr90A.7CSS3D_vwDg@nauta.cu> <Mr.OfXLZItvn_f.HaSCD1CCrNb@nauta.cu> <Mr.ZgClRbW7hPS.64gwk0MJpe6@nauta.cu> <Mr.vDfPH4Bi45l.vbN9JAAZCqI@nauta.cu> <Mr.Z1lkCcmh4Cj.ZccILUWWMfh@nauta.cu> <Mr.lpNhTLx3eVX.KtZ2CR_5kG2@nauta.cu> <Mr.10LfkRpPq6x.eiNCt26UoZh@nauta.cu> <Mr.kaNKCsRBn_1.OLik5ePpFyT@nauta.cu> <Mr.pBkG3jhx4qo.rQAIufB78_N@nauta.cu> <Mr.M7ugO4IyLIb.0wQiEMC4yMN@nauta.cu> <Mr.WUkaYfZoXd7.JSI0nNvV1tN@nauta.cu> <Mr.OOMz7M-KQOD.NpcrVBh4mkj@nauta.cu> <Mr.etCsC-gZYIn.IEA6qz1eXLF@nauta.cu> <Mr.w1yruLMm-m0.fNZ9hSXHXlY@nauta.cu> <Mr.nRyt7K7c2Cr.ktaDZ8Zs9sM@nauta.cu> <Mr.nnPz0Mgeebh.j4OctbpNxQY@nauta.cu> <Mr.gfzArpcx-Fo.UIQI2PEPBkP@nauta.cu> <Mr.lMOBKU-Ev_Q.7K_8jm6orDZ@nauta.cu> <Mr.mcXnbO4xLUd.qe-EvwyAcVV@nauta.cu> <Mr.RcjVsQ3BfzM.PBQP0ss2A-p@nauta.cu> <Mr.AnojfFpd5op.X6ZQhdSSU-n@nauta.cu> <Mr.rMVzpqqQBpI.22ii5M-mPMo@nauta.cu> <Mr.TQsjU9rqhOM.KWzX9wGfJfi@nauta.cu> <Mr.nVD03kjfLEz.TCkFiJub6cQ@nauta.cu> <Mr.SQJT46-tOJD.zqUBCZ3uRuY@nauta.cu> <Mr.8Pebw-nir9n.nokdqV5NzTJ@nauta.cu> <Mr.GYzhZeqyQJF.2Q01ZpmRPQD@nauta.cu> <Mr.1BdE1tXgzGI.-HRvnusRh-K@nauta.cu> <Mr.u4ZHAqCXpre.zz5r8DZJgU3@nauta.cu> <Mr.tQeFY-NMZFk.R5yej5U4BnX@nauta.cu> <Mr.fmQmIoH5yO6.tKrcKKhMeKF@nauta.cu> <Mr.cWQDQ2m08ku.Lho6NPFOonR@nauta.cu> <Mr.AbPqWJR3_FJ.wX1AkqgpzbZ@nauta.cu> <Mr.N_dWvQMySX1.hGe05PRayjj@nauta.cu> <Mr.Q9HBK7TayQt.IXJHEkLqw8V@nauta.cu> <Mr.PF2gJcN_umF.eaViT0T4vd3@nauta.cu> <Mr.N_sh2_Gvh5D.zdZFogG1dOM@nauta.cu> <Mr.sPgE8u_cKxX.Rfw4PwIPh1F@nauta.cu> <Mr.XNL6iLu4-P_.X4KNP6Z5BRc@nauta.cu> <Mr.2VwV3aub6Mi.heh2Q1CTU8l@nauta.cu> <Mr.VLyIEc32Rtv.2f1YwVEzNX5@nauta.cu> <Mr.am2zewWJRdu.1K2lhZ4uzmr@nauta.cu> <Mr.ZdLwXFizqCA.UUfbbaQR10_@nauta.cu> <Mr.dKOHcjOQKjA.fJ_sPHkCmut@nauta.cu> <Mr.9cS_p7s84q2._o5P52lx-OG@nauta.cu> <Mr.RJ9HbKjyJJA.waicFxRcykp@nauta.cu> <Mr.GRsGuWyhAvt.aYYeX1dF1Ba@nauta.cu> <Mr.8N6VoM2e5cB.iyNTzvV122N@nauta.cu> <Mr.IOz28VAoQvi.4_cVcffSbZD@nauta.cu> <Mr.2ZbZIi8bnhf.AsykcQQrQgh@nauta.cu> <Mr.2r6AsQOD0oE.4S03euEYjTC@nauta.cu> <Mr.RvsMDCtp0qu.nUrrC_lqkT7@nauta.cu> <Mr.WAAnff-XCzm.rl6I6d_Qm7K@nauta.cu> <Mr.49_gJio3w50.A-iFzT3A9wu@nauta.cu> <Mr.aL732O0wu4e.AEV4GQeD2eP@nauta.cu> <Mr.IN2FGPP2x0g.Ce2iOL9J05_@nauta.cu> <Mr.R_QtyRyArPj.S3JrpSA_hb2@nauta.cu> <Mr.65wda2TqtY-.V_MdQGyHzvp@nauta.cu> <Mr.vxErOUg341T.x9OwAV1BvxB@nauta.cu> <Mr.anx_d8jpER6.3rSSs4ZsaYS@nauta.cu> <Mr.kqKW2IrOz6d.gDKpR8TDMc9@nauta.cu> <Mr.e7DBKhrL1HT.ysK4mMDpfEB@nauta.cu> <Mr.gpxOwOyKv9h.zdCuE7Y73Xd@nauta.cu> <Mr.hMYiR18V8DD.hXLh0N08Ejp@nauta.cu> <Mr.DJvt333JWBA.ndnvRXUJzg8@nauta.cu> <Mr.gEinh2-e2IX.weFF_IKaPZd@nauta.cu> <Mr.r9XWLAL6hnW.kS1gk0g2YyM@nauta.cu> <Mr.7L89mJFSdKb.jLNcUp04_aN@nauta.cu> <Mr.l-OBxivdHWy.ug9CdBPIuXr@nauta.cu> <Mr.zrC_t0bos60.mL3G18oIoJJ@nauta.cu> <Mr.lukQ9JjhNyL.-7r6z56Llzo@nauta.cu> <Mr.36Jcj97pkVD.j6fDhhDjdg3@nauta.cu> <Mr.-mjupprsp7a.YeSmfB2Os1r@nauta.cu> <Mr.CG6bGkm8SFz.6qcJZff5CXV@nauta.cu> <Mr.OkllmUvH7DX.s5g79-Etxof@nauta.cu> <Mr.gMhX3W9DKNW.WUnrqExL1mM@nauta.cu> <Mr.bUEBO8o1oGR.BLG8t26-GtN@nauta.cu> <Mr.SGRwSvHN92G.82_tfFjwp2D@nauta.cu> <Mr.bRS9bxL-7PM.wVtV7aPQOEx@nauta.cu> <Mr.7rXwApBeqWw.jGEZOVyBSm5@nauta.cu> <Mr.TDVbkkIQW9w.1teMKNNlbJE@nauta.cu> <Mr.Ds0y5bUk3wz.2ppTCbPuO59@nauta.cu> <Mr.9lXnUGHzVVX.TUZP-PjcuLf@nauta.cu> <Mr.hqtXB0qqyUK.IVpHjGmuJ0M@nauta.cu> <Mr.3KunHGwdUko.WDMMr-uOSol@nauta.cu> <Mr.3oovxHmq1RP.631w9Gf98mC@nauta.cu> <Mr.x9yw0Xbj8Vu.Z7LUL-ZagsW@nauta.cu> <Mr.a75xFcoao7G.4PjabD3dys0@nauta.cu> <Mr.tmSp52yjs3F.BcyXJ2EKZKu@nauta.cu> <Mr.I3LhsS0ntKp.Tm8ju6tufAv@nauta.cu> <Mr.GHNwNULBm1v.9RqGpprDcVy@nauta.cu> <Mr.I-M03-IDqny.ZXzoUppUu97@nauta.cu> <Mr.9GGgW0JSJN6.TyAE-fKJmv7@nauta.cu> <Mr.RipoEN4eDnE.A1ZPHGUlNvL@nauta.cu> <Mr.hnh1m7M6UKp.qlJOe-Azj7B@nauta.cu> <Mr.bxAuMaHF4zh.QPcwDofyP_x@nauta.cu> <Mr.lZCfspidcUM.tIFAjJW8t7Z@nauta.cu> <Mr.gHGqMB-wd7G.9KfvjxLVDo-@nauta.cu> <Mr.MNOqYYJQUJF.Cwu8UJ4qHth@nauta.cu> <Mr.kf96vuS1G1V.T5HgpAEQGTr@nauta.cu> <Mr.JKOlfBOrbc-._E2bIUTX6-I@nauta.cu> <Mr.Wm3ZOJ2t6lk.5pWgs3H04ND@nauta.cu> <Mr.qT98iRKc1v3.GKqa3po__3h@nauta.cu> <Mr.F_A-sMLeckC.xOOBYDf1z7G@nauta.cu> <Mr.1p8VQn_FG1p.3w-yWNNRshU@nauta.cu> <Mr.jM17kY0Z1TQ._AmRpbRS_tx@nauta.cu> <Mr.D4yFOjiluUk.FDL9dGup-j1@nauta.cu> <Mr.c3nTt6jJx7q.7tjAtvjS2qh@nauta.cu> <Mr.58pjeaqx1ez.E9oQvDcmpFA@nauta.cu> <Mr.VgC4bC7P1cX.wsTU8Y1KIys@nauta.cu> <Mr.coxY6K0NpfS.7mkJMQKCk1M@nauta.cu> <Mr.oj66bMT7-tD.lq-tNe5pSo8@nauta.cu> <Mr.7QTHcJvw1We.orH5kjtnzvA@nauta.cu> <Mr.WHnbpHGyTNP.KBIOyKNSGsT@nauta.cu> <Mr.QFDTRNQAzFT.QVkVlsZQrfT@nauta.cu> <Mr.lYVLCkjpsQW.ZnDZ7au8QYy@nauta.cu> <Mr.wSvP_SaKC2_.5GJzS-_fXVL@nauta.cu> <Mr.dAB2o4vyCKj.7l8deeBqMsg@nauta.cu> <Mr.ipsBtl_mtVK.4aMG8CTtuwH@nauta.cu> <Mr.AW8FuxJevqA.HbbLTFGub5x@nauta.cu> <Mr.QiTj-H-sH7O.6CPdyGwr2Tu@nauta.cu> <Mr.nuuQV-arD39.7jc8M65h0FU@nauta.cu> <Mr.xqK89OmV81h.zKj-VQ61W9J@nauta.cu> <Mr.aHFhVWPmkys.m5aNRQpWJ4Q@nauta.cu> <Mr.pHra1nvkuvC.3983XYOpyRK@nauta.cu> <Mr.zzEBB7bRNMv.fY9eV-zTWYw@nauta.cu> <Mr.GV0gjhZdt4e.iX0oCqCb479@nauta.cu> <Mr.gmHBx08rUnh.f0y8ztOLs9T@nauta.cu> <Mr.Jm_2u2GSwWU.CIaeBHB4xSU@nauta.cu> <Mr.isVN69b3Ns5.UsuT08HLEqR@nauta.cu> <Mr.B9AyLbPsHtq.4mOmfBvpwUA@nauta.cu> <Mr.OfzAYDAJInA.D1BkB8Rz8AI@nauta.cu> <Mr.qRedM-_4CEd.khvlGCXy33x@nauta.cu> <Mr.OPySLsZ7n_M.l_wg0-N72PS@nauta.cu> <Mr.H6Bzj8kzE08.GYAY7Gjx8It@nauta.cu> <Mr.XETJQS5S_Wl.Ubgurlq4GAu@nauta.cu> <Mr.SLmWP_ROyKg.cbSLrgi0hWj@nauta.cu> <Mr.ZfvwXn1QlBc.HNQmbsEbXyD@nauta.cu> <Mr.JX8b2_OqLs_.e8tiSIeetnx@nauta.cu> <Mr.YhQx4mCmp9q.M4ytjuVIgav@nauta.cu> <Mr.neP4HOurv4l.U0yhHsSnL4Y@nauta.cu> <Mr.HV9mFqO7L48.6eQvCRdW5eu@nauta.cu> <Mr.aHm3kw4sNOh._68i-JGrgIa@nauta.cu> <Mr.1P6g9d1zNOl.Yhm6HbAYs2A@nauta.cu> <Mr.A0jk65sM9Pf.6t_AalFoepn@nauta.cu> <Mr.4NnktuZGE0f.BgEo8k7dO1S@nauta.cu> <Mr.CROdA6DWIwg.2JhJ7IMvQ_I@nauta.cu> <Mr.CYGHbdFAt7O.wZcUdRqjXb9@nauta.cu> <Mr.jC7PzDWPJd1.F_9wRmS6ma1@nauta.cu> <Mr.szmDlHqG0gE.XFeeT40MEWz@nauta.cu> <Mr._fboj0gBhwK.9-Ojyamsunj@nauta.cu> <Mr.I5VmR0DKmO4.2z8tgVwcfC5@nauta.cu> <Mr.q0RXpdUg6lo.KQm8ZZv4P6d@nauta.cu> <Mr.Qt8j8_wBlde.SkaPXORNeZr@nauta.cu> <Mr.ZHFybZFMvVF.wsw8-67fST9@nauta.cu> <Mr.JC2qlF8y044.5ATWPBjk0A_@nauta.cu> <Mr.SsOEKi-ywbw.9IJ4vCLa2al@nauta.cu> <Mr.5BalaIC699I.6BZm6TaOOJj@nauta.cu> <Mr.VA-Oj0xjG_P.CEox2_zjiWM@nauta.cu> <Mr.6Hh8gBAoC_R.3-EuioAJ8gz@nauta.cu> <Mr.5Yiozl4qlX9.oQ6oCd9KZhN@nauta.cu> <Mr.JNKCn--mXwH.YzzPjlTAjDH@nauta.cu> <Mr.SsXB_VyX-9F.K-bxyiAc5BD@nauta.cu> <Mr.AReCCJD2TnA._8nhqHeMvkd@nauta.cu> <Mr.KfYjd0vWg70.GGwwCfD9H6r@nauta.cu> <Mr.WF9xfRUdNWy.r_fdXRXqPOu@nauta.cu> <Mr.bfz_Y9tZSNP.t2PFPKm85bM@nauta.cu>
X-Mailer: Delta Chat 0.39.0 for android-dev
Chat-Version: 1.0
Subject: Chat: 😆
Autocrypt: addr=A FRIEND@nauta.cu; keydata= xsDNBElbsCkBDADCDE0m7Vk2ZEWen9ppyh9H8vjYz2++zkdkbG0xb3pybN33B9hh/wlwk/gTXb3SGO Oh1LBiKJUfm5r368l6qxigUSfefWi1bwHg8FH+Fw8xbazM3Hh1voa1OVQL4a7N/anU3cy5vfineJSW PeGv7fphAtILadT6Ru8y2+a2WVhICRWSemfk7LgYV5crI5sHHIWPK/Xqboeh+hmXkn55qjpUuMCvG5 VcD0g2zpgJnuo0hJv7DP792JSsSQm8jmrdWJ+K36aRzV/nObFq3rDWERmr8bN9EKVXSix+vtf7EVL0 7L+kHdgObn8NuubhLxQnyFE+Crun8zwksTk5EAd2RWkMW24KYaRaLdJuRIoqxwEGkCwsHFYcCpoPXY +JbHrAsRbPINYwjhMEoKzjSu5pA3dh+QyttsLqAI66re5Zz84AOpVM86aNXR6WbD+ZclddakCgLwwi SyeFk8L/fEh/mMLrsKxZucl+9wAJOErs/osNiQv8g2TqRJYYFn421HYpquMAEQEAAc0XPGcubXJvZH JpZ3VlekBuYXV0YS5jdT7CwPwEEwEIACYFAklbsC0FCQAAAAACGQECGwMGCwkHAwIBBhUICQoLAgIW AgIeAQAKCRA5V+TY+xnOUyYVDADBaYJ4iIjLQP/eYwBeBwoYoHtAC8nYnE8SCcWpFptwZliDZpzxYo 7/+LM6F20QQRKTsjC7V+4E8mS8zFjgC+OogcRTfgtCVFFDam0jZK9qOiyaf5gRqtzXTvDT5h3Qb0gY q/g+fqzrYGiSC5cDp+8fw5jIOlHi5eyH8SoOpKkTXpFX6/xjeDWbIDcczFN5w+Z7qZoBWhMj0v4mQu JQKMqLPgdy5Hapo1ttdtkz1GiSGLiW031OEmeQR85xELCRgu2ry8qWorl41B/p2Paixm6CJlgqvqWc mzeZ9K8qe/QKuaOedLIDQxv3C5+LY/d09c5ojHZyhQb60jS6DHA81BzMEJTzUgjXaKP8eRO73sx6gW iklR3dR847lrr9I/VcArW0mHNkgv26E8E3fajFWa4Io48JYW3lhv9WFcD4zcZ3YQ+RceUkWdCEa8Sf zzRLCX0iA0GJ/j103hw7FkS6CEcibYWhPE0Msu42H0gj1Q57LQ7VsJHelanB+4UiL6eBdC/OwM0ESV uwLQEMAMOd8SBI799roE5zALVu7SWTl+8k4BB8n1dfdOJNeo0jlsCo5ebZr2cFI7kobdK6d7kD+NDf r7pJGUj0U+Z+XPmyxG4wHXRRKiiBoJ7qsRm5VI/gSREsuoFbqrK0K7n71v+PGaUog961orn9hUl/1J H78DrYAtcrZ+Toa+ZM3KEZd+MUbtj4WPLsaMl8DK7RbbEKHoZgDelFSQXQKTH3BQkAiCWNj3Gar0Cz 8dppIvC+pCbhVV0k4J1Fri/W62ri7QtJd4LcX+G7l/MrEDtDWzU3rFS0Wi2h0AbLyTiZpd80axhx7c 0Om9ARpa9KoR7VWLeTdkyjHjDGkGWr5l9dT0lvopws1yDYWbb1g63Gjpem9QS9KAu5o3Pr3TdPfHk+ QVT0d3F7GUeU9Xdw3Ot5tr2I/qXsKmukA80XGf6ov0LgHSdfUgoFQQUaPOjGLHmxYNNYrfvPsb3Ttv QDPfbWW38frKJrwSq5VCZeK0gydGauzN2xLxVcsxiUKMGCt9hRqwARAQABwsDlBBgBCAAPBQJJW7Au BQkAAAAAAhsMAAoJEDlX5Nj7Gc5TsQAL/2P44/o94bFVMhCFsyY71UjGCKtVXkidYlWEZRTHn7jd4S O3PxRfvv8uXZn5k6Fa9LBTietzenteo23dmz9cyjrUSGR0JDhqVaGhPqcmf3PipzJfIEvRPyFLgmd6 ENnMGLZjS1TG3VYxYU3XIpiprjR9BVTWx9lPCvMccLlrzi8gDsI5uxGEAlM/vDNbE24HojJd/eNbY1 ptqeYCGC6nnz+SzqsZ9kxGbDk/q77fnUrS7hFJQFhv3ypDIRwk1hMZZYE799PjM9JjtnFWD60jTKDD qtcDtBFY/eXKaqdkOsqhBRP9W1flpzSMPMk91pQBcs6LEdQND4BBYHz892Rqk7MbxM7IYk5hpMfelv Ts+RyHO6CvkFWAAK0sgBXCy93pmcR0az/JGdg0kLKmZlm67VuAu44U+EyMiXxfBv0v+jYg+bJVYQMT QgTtfFptTEfDptRx+0IHeRkm1aOVcYQMMKy2dZ8ZRCvjRt3J6rG7yx5uE6qBHiVsvwLRGaW9PqvGcA ==
MIME-Version: 1.0
Content-Type: text/plain; charset="utf-8"
Content-Transfer-Encoding: 8bit
