### ISSUE TITLE
I can't login

### ISSUE THREAD

**Issue by Sebek05** [deltachat/deltachat-core#556]
Since version 0.97 I can't login to my e-mail account.
The data is 100% correct. Other email applications are working.

- Platform (android/blackberry/anbox): Android
- Device: Samsung S7
- Delta Chat Version: 097 - 0.100
![screenshot_20190127-165822](https://user-images.githubusercontent.com/25055220/51869279-61ff7c00-2350-11e9-87ed-1511a32dbc16.jpg)
![screenshot_20190127-165814](https://user-images.githubusercontent.com/25055220/51869280-61ff7c00-2350-11e9-842d-0cd10821ed09.jpg)

**Comment by r10s** [comment]
i think this should be re-checked with the upcoming version (0.100.2 or larger then), we've optimized lot of things in the configure process, with chance, this issue is fixed as well.

**Comment by hpk42** [comment]
there were various fixes with initial connection setup so please re-check with at least Delta/Android 0.200.0 and open a new issue if the problem persists.  Thanks!
