### ISSUE TITLE
add plz this preset for mail.ru, inbox.ru, bk.ru, list.ru

### ISSUE THREAD

**Issue by f242** [deltachat/deltachat-core#558]
### Incoming
**IMAP login**
full e-mail: username@mail.ru, username@bk.ru etc
**IMAP server**
imap.mail.ru - this server for all four mail domains
**IMAP port**
993
**IMAP security**
SSL/TLS

### Outgoing
**SMTP login**
full e-mail: username@mail.ru, username@bk.ru etc
**SMTP password**
e-mail password
**SMTP server**
smtp.mail.ru - this server for all four mail domains
**SMTP port**
587
**SMTP security**
SSL/TLS

**Comment by r10s** [comment]
there is no "preset" area in delta chat, but deltachat uses [autoconfigure](https://developer.mozilla.org/en-US/docs/Mozilla/Thunderbird/Autoconfiguration).

at least for mail.ru, it should work automatically.

moreover, i've added/updated https://support.delta.chat/t/provider-overview/56/2 with the information - feel free to add needed things here.
