### ISSUE TITLE
Group administration

### ISSUE THREAD

**Issue by Hocceruser** [deltachat/deltachat-core#56]
Currently, anybody can remove anybody from and invite anybody to a group. Of course, you can just create another group when somebody removed you but still this seems not to be a very good solution. So, what about these ideas:

- There are group admins, just like on WhatsApp

- You can only remove people you invited or people which were invited by people you invited

- You can only remove people who did not write anything for a month, otherwise they have to leave from themselves

Of course, all of these suggestions are quite difficult to realise, especially the second one...

What do you think?

**Comment by r10s** [comment]
> Well, I just wrote everything coming to my mind down...

Yes, of course, no problem :)

> What do you think: Will implementing this be more or less difficult than mailinglists?

I do not know :)

**Comment by csb0730** [comment]
Well, to support mailing lists (again) would be a very useful feature. So we would have the possibility to follow all these discussions directly with DC :-)
In the moment I'm using K9 for that.

**Comment by testbird** [comment]
Well, this is exactly the kind of confusion meant in #49 that may possibly be avoided by using better fitting words like distribution or  recepient group / list. Don't you think?

> Another idea might be to support standard "mailinglists" in a smart way - for these lists the "group" administration problem is already solved.

Nice idea, buttons to subscribe / unsubscribe according to the mailinglist header.

**Comment by testbird** [comment]
Wouldn't allowing to create threads in DC for mailinglists (from header data) go a long way already.

**Comment by r10s** [comment]
I've opened an issue for Mailing lists, #125, and I _tend_ to close this issue as a _third_ type of group seems to be out of scope for now. Also, this would introduce an imbalance between Delta-Chat-users and Non-Delta-Chat-users.

**Comment by r10s** [comment]
apart from #125, unless there are some volunteers working on this issue, for now, this is out of scope IMHO. However,  the idea stays available via https://github.com/deltachat/deltachat-android/wiki .
