### ISSUE TITLE
Sending emails to yourself using Enigmail and reading them with DC does not work

### ISSUE THREAD

**Issue by Hocuri** [deltachat/deltachat-core#560]
- Delta Chat Core Version: No idea, DC Android is v0.100.0
- Expected behavior: Encrypted mails sent to yourself with Enigmail should be decrypted :wink:
- Actual behavior:
They are shown in the form `<subject> - [...]`

  It works to send an encrypted mail from DC -> Enigmail and decrypt it there.
- What I did: (My friend couldn't reproduce the problem that way)
Install Delta Chat
Send an autocrypt setup message from Enigmail to Delta Chat to transfer the key
Send an encrypted email to yourself using Enigmail and open DC
- Screenshots:
![image](https://user-images.githubusercontent.com/18012815/52176053-f08b5780-27ad-11e9-96b7-4f1ab749eb3d.png)
![image](https://user-images.githubusercontent.com/18012815/52176057-f5e8a200-27ad-11e9-801a-2c07af650f1f.png)
- Logs:
Is there any possibility to get logs without ADB?

**Comment by Hocuri** [comment]
@r10s Actually the key transfer worked. I mean, I can send an encrypted message to myself using Delta Chat and read it with Enigmail now. I can also read my encrypted DC Chats with Enigmail.

 It is just sending _messages_ from Enigmail to DC that does not work.

**Comment by Hocuri** [comment]
It is getting weirder... I sent an email to a friend using Enigmail and could read it within Delta Chat in the chat view. I changed the title accordingly.

**Comment by hpk42** [comment]
On Tue, Feb 12, 2019 at 08:27 -0800, Hocuri wrote:
> It is getting weirder... I sent an email to a friend using Enigmail and could read it within Delta Chat in the chat view. I changed the title accordingly.

This indeed sounds odd. 

Could you check if there maybe are odd keys in the key manager for your e-mail address
that you use for self-sending? 

When you sent the Autocrypt Setup message from Enigmail to Deltachat, then DeltaChat
also keeps the old/previous key.  So i don't know how DeltaChat could fail to decrypt
a message from Enigmail -- unless there are more keys involved for your address. 
Or unless there is a PGP-format/parsing problem (which i guess is unlikely).

**Comment by Hocuri** [comment]
>  Could you check if there maybe are odd keys in the key manager for your e-mail address that you use for self-sending?

I couldn't find any. BTW my friend tried to reproduce this but couldn't.

**Comment by hpk42** [comment]
@hocuri if you don't mind i close this for now. Please feel free to open a new issue (and state precise versions) if the unreadability issue re-appears.  Delta  Chat does not offer much help yet in detecting "mixed encryption" settings and fixing yet so the multi-device issue is going to stay a little messy for a while :/

**Comment by Hocuri** [comment]
Well, the issue persists but I failed to reproduce it on another phone myself and nobody else seems to have it. So it is true that it would not make much sense to keep this issue open.
