### ISSUE TITLE
Warn non-DC users they received a voice message

### ISSUE THREAD

**Issue by luisfsr** [deltachat/deltachat-core#57]
When a voice message is sent, warn non-DC users they've received a voice-mail and advise them to use DC or VLC (or other app) to hear it. Also advise them (non-DC user) to ask the sender to write down the message if they couldn't hear it.

**Comment by r10s** [comment]
Do you mean some explaining text in the mail that is only shown in normal MUAs? I think, this is an good idea. We could also add this for videos.

**Comment by luisfsr** [comment]
Yes. I mean exactly it.

Em 4 de novembro de 2017 07:10:14 BRST, "Björn Petersen" <notifications@github.com> escreveu:
>Do you mean some explaining text in the mail that is only shown in
>normal MUAs? I think, this is an good idea. We could also add this for
>videos. 
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/deltachat/deltachat-core/issues/57#issuecomment-341882678

-- 
Enviado pelo Android com o K-9 Mail. Desculpas pela brevidade.

**Comment by r10s** [comment]
one of the next versions will allow to type some text along with send images or other media, so there is no more real need of this - and also no more place in the mail for this as text + attachment are both user generated and are just shown.

we'll see how this works out, maybe we can adjust the file name to make things clearer, happy to continue the discussion about this in the [forum](https://support.delta.chat/), for now, we close this.
