### ISSUE TITLE
Trying to read from unset Sent-folder may drain battery

### ISSUE THREAD

**Issue by bluditbeginner** [deltachat/deltachat-core#573]
- android 6.0
- Device: Wiko Sunny 2
- Delta Chat Version: 0.100

I want to give some hints about battery usage, what we noticed in our testgroup.
We tested the current Version of Delta.Chat in a group of some person.
We noticed different behaviour on different devices.
My device, android 6.0 - normal battery usage - no entry in akku-statistics
Collegue with android 9 - high battery usage - 25%; and the app can not be closed.
Collegue with android 8.1 - high battery usage too.

I do not have more details, but perhaps it helps.
Greetings.

**Comment by r10s** [comment]
fixed by https://github.com/deltachat/deltachat-core/pull/543 which will be in the upcoming release then.

**Comment by stmllr** [comment]
@r10s thanks. The error messages vanish from logfile after unwatching Sent Folder.

Let's see if this solves the battery drain on my device

**Comment by r10s** [comment]
@stmllr thanks for checking :)

for the upcoming version it is no longer needed to unwatch the Sent-folder manually then.

wrt battery: well, at least one issue less :)

**Comment by stmllr** [comment]
unwatching Sent Folder reduced battery drain a lot. 409mAh within 1d12h, no active delta usage.

**Comment by stmllr** [comment]
Looking forward to test new releases :)
