### ISSUE TITLE
wrong instructions for "perform the actual build"

### ISSUE THREAD

**Issue by csb0730** [deltachat/deltachat-core#577]
current instructions under "Code" -> "perform the actual build"

```
mkdir builddir
cd builddir
meson    <== this needs to be run in the parent dir of builddir !
# Optionally configure some other parameters
# run `meson configure` to see the options, e.g.
#    meson configure --default-library=static
ninja
sudo ninja install
sudo ldconfig
```
correct seems to be

```
mkdir builddir
meson builddir            <== meson needs to be run in parentdir with builddir as first parameter
cd builddir
# Optionally configure some other parameters
# run `meson configure` to see the options, e.g.
#    meson configure --default-library=static
ninja
sudo ninja install
sudo ldconfig
```

**Comment by r10s** [comment]
i think both variants are okay. 
i fact, i always call `meson` from the empty, just created builddir and it works.

**Comment by csb0730** [comment]
if I call meson into empty builddir simly without arguments it
a) complains that it needs a Directory as first parameter
b) if i give builddir as parameter it says: cannot find builddir

my proposal works in any case.

(meson 0.49; Debian 9)

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

Am 15. Februar 2019 01:35:51 MEZ schrieb "björn petersen" <notifications@github.com>:

**Comment by hpk42** [comment]
On Fri, Feb 15, 2019 at 01:40 -0800, Christian Schneider wrote:
> if I call meson into empty builddir simly without arguments it
> a) complains that it needs a Directory as first parameter
> b) if i give builddir as parameter it says: cannot find builddir
> 
> my proposal works in any case.

could you share a copy+paste of the actual terminal session? 
It just doesn't seem to be right that if you are cd'ed into the
builddir that "meson" does not work.   Please also "meson --version" within
the session.

**Comment by r10s** [comment]
meson 0.48.2 here - maybe they have removed this feature.

**Comment by hpk42** [comment]
On Fri, Feb 15, 2019 at 04:23 -0800, björn petersen wrote:
> meson 0.48.2 here - maybe they have removed this feature.

using 0.49.2 it works for me to be in an empty builddir3 and
have "meson" work as intended.

**Comment by csb0730** [comment]
I will check again and paste the session.
Maybe I made a mistake? ...

**Comment by hpk42** [comment]
or maybe the stars simply didn't align ;)

**Comment by csb0730** [comment]
@hpk42 : don't understand last comment!  8-)

**Comment by hpk42** [comment]
suggested stars not aligning as alternative to "you made a mistake" :)

**Comment by csb0730** [comment]
What do You mean with "stars". There are no ones, isn't it?
Still not understand.

Meanwhile I got some results:
- deleted builddir
- started from scratch with original procedure (meson called in builddir)
and that worked!

But now command `sudo ninja install` doesn't work any more! Build stops.

See full log output here:
[build-log-meson-ninja.txt](https://github.com/deltachat/deltachat-core/files/2872883/build-log-meson-ninja.txt)

**Comment by adbenitez** [comment]
I guess building didn't worked for me, I followed the steps but I think only a .so file with number 0.0.0 was installed, I don't see any 0.40.0 lib, also I had compiled and installed an old version time ago that worked, how do I uninstall it???

**Comment by csb0730** [comment]
In spite of the _broken_ build process a `~/builddir/cmdline/delta` and `~/builddir/src/libdeltachat.so` are created!
I think this is done by the first two calls of _meson_ and _ninja_ as standard user.

Regarding the failed `sudo ninja install`:
As far as I can find is: importing meson module by python3 is possible by standard user (which did the install by pip), but not in su mode (sudo)!
Maybe meson needs to be installed for all users by root?!

In any case I tried a `ninja install` as a standard user but this requested su mode then later!

**Comment by csb0730** [comment]
Regarding the failed `sudo ninja install`:

`sudo -E ninja install` does it! - long finding but success :-)

@hpk42 @r10s 
Can You both confirm this?

**Comment by Jikstra** [comment]
> What do You mean with "stars". There are no ones, isn't it?
Still not understand.

It's a joke, maybe a german saying you can't really translate. By stars the weird yellow things we sometimes can see in the sky is meant, and if they don't align, sometimes stuff is not working even if it otherwise would, so even if you're doing everything correctly, maybe the stars are the problem ^^

**Comment by adbenitez** [comment]
I had get the joke from the beginning but didn't knew this is a German joke, actually to me feels quite common... :P

**Comment by r10s** [comment]
seems as if the initial issue and also the joke is solved.

if not, feel free to re-open.

**Comment by csb0730** [comment]
@r10s 
initial issue is not solved!

`sudo -E ninja install` is important. "-E" option is very important and is still missing at build instructions.

Please add it before closing this issue.

**Comment by r10s** [comment]
k - reopening. @csb0730 can you do a pr?

**Comment by csb0730** [comment]
I'll try

**Comment by r10s** [comment]
okay thanks, we can continue discussing this detail at https://github.com/deltachat/deltachat-core/pull/602 then
