### ISSUE TITLE
Sha1 is considered weak.

### ISSUE THREAD

**Issue by gdanezis** [deltachat/deltachat-core#58]
Hello all,

I have been doing a light crypto review of deltachat. I noticed that sha1 is used as part of the signature here:  https://github.com/deltachat/deltachat-core/blob/f8d478a919f45281aac00de9b8a78ce7d4b6c96f/src/mrpgp.c#L480

Sha1 has known weaknesses, and is no more recommended by NIST. It is probably worth using something more modern such as one of the SHA2 family of hash functions (like 'sha256').

Best, and thanks for the great software!

George

**Comment by r10s** [comment]
> I have been doing a light crypto review of deltachat.

Cool :) Very good idea!

I will check this out ASAP :)

Good luck in finding out further glitches :)

**Comment by r10s** [comment]
Hi George,

I can change this easily, however, I am not sure if there are side-effects regarding the other positions where SHA1 is used - eg. for the session key, there is SHA1 also hardcoded, eg. [here](https://github.com/deltachat/deltachat-core/blob/master/libs/netpgp/src/create.c#L379) or [here](https://github.com/deltachat/deltachat-core/blob/master/libs/netpgp/src/create.c#L1372), a grep will show other places. 

Seems not to be a problem at a first glance, however, I would appreciate someone else checking these parts, too.

Björn

**Comment by r10s** [comment]
Okay, i went into some more details. The sha1 -> sha256 change affects the hash of the signature and should not have side effect. In fact, this is also the default value used in netpgp - in the examples resp. in the pEp implementation netpgp_getvar(..., "hash") is used which returns NULL by default; passing NULL to pgp_sign_buf() is safe and results in the usage of PGP_DEFAULT_HASH_ALGORITHM which is equal to PGP_HASH_SHA256.

The change also changes the Enigmail security info as expected from ...

![before](https://user-images.githubusercontent.com/9800740/34576985-11371844-f180-11e7-9e0c-07271e9e4a74.png)


... to ...

![after](https://user-images.githubusercontent.com/9800740/34576999-1c2fffb8-f180-11e7-9ad2-31ba9c7cb018.png)

@gdanezis so, this took a while, however, again, thank you very much for this hint.

**Comment by gdanezis** [comment]
You are most welcome -- thanks for your great work!

**Comment by r10s** [comment]
Thanks :)
