### ISSUE TITLE
Thought you guys might find this project helpful

### ISSUE THREAD

**Issue by jcklpe** [deltachat/deltachat-core#581]
I'm putting together a project to help do open source branding for open source projects. 

Your project sounds cool but it lacks some attention to visual presentation. Feel free to check out the project I've put together here: https://github.com/jcklpe/Open-Source-Branding

**Comment by Hocuri** [comment]
I also think that DC could do with some more branding and I also am generally in favor of "outsourcing" some of the design however I am not a collaborator

**Comment by r10s** [comment]
@jcklpe interesting, thanks for the link :)
