### ISSUE TITLE
rPGP meets deltachat

### ISSUE THREAD

**Issue by dignifiedquire** [deltachat/deltachat-core#592]
Creating this to track the various things that [rPGP](https://github.com/dignifiedquire/rpgp) will provide in the short term for deltachat

## `dc_receive_imf.c`

- [x] hash with sha256

## `dc_key.c`

- [ ] parse key from armor
- [ ] parse key from base64
- [ ] serialize key to armor
- [ ] serialize key to base64

## `dc_pgp.c`

- [x] `dc_pgp_create_keypair`
- [ ] `dc_pgp_split_armored_data`: armor -> headers + base64
- [x] `dc_pgp_is_valid_key`: is_valid_key (public and secret)
- [x] `dc_pgp_calc_fingerprint`: fingerprint
- [x] `dc_pgp_split_key`: get_public_key (already there, needs integration work)
- [x] `dc_pgp_pk_encrypt` - sign + encrypt to n public keys, sign with a private key
- [x] `dc_pgp_pk_decrypt` - decrypt + verify sigs for n private & public keys
- [x] `dc_pgp_symm_encrypt` 
- [x] `dc_pgp_symm_decrypt`

**Comment by Hocuri** [comment]
From https://github.com/dignifiedquire/rpgp:

> WARNING: This library has not been audited, so be careful.

**Comment by hpk42** [comment]
On Fri, Mar 01, 2019 at 05:16 -0800, Hocuri wrote:
> From https://github.com/dignifiedquire/rpgp:
> 
> > WARNING: This library has not been audited, so be careful.

we are aware that there is no audit yet.  This is an experimental
integration.  We just submitted an application to get a first
security review on the new rpgp code.

**Comment by hpk42** [comment]
The default core CI builds here successfully use RPGP now, and it's preliminarily integrated with Delta/Android and Delta/ios -- so the meetup of DC and RPGP was fun and successull, and the dance continues ;)

**Comment by r10s** [comment]
\o/
