### ISSUE TITLE
 Kerberos authentification support

### ISSUE THREAD

**Issue by arthurlogilab** [deltachat/deltachat-core#603]
As discussed on https://github.com/deltachat/deltachat-desktop/issues/716

- Platform (linux/mac/windows): linux
- Delta Chat Desktop Version: 0.101.0-preview
- Expected behavior: Authenticate using kerberos ticket
- Actual behavior: Only password login is available
- Steps to reproduce the problem: 
- Screenshots:
- Logs:

**Comment by r10s** [comment]
@arthurlogilab do you know which providers use this sort of authentification? does it typically require ui parts (as oauth2)? where would one enter a kerberos ticket?

**Comment by arthurlogilab** [comment]
for the providers, it's mainly companies that have internal SSO based on kerberbos.

In the UI you probably need an option to say that you don't need to put the password since the kerberos ticket will be used. Trying to avoid users from entering their kerberos password in the app would be a good thing.

**Comment by flub** [comment]
How would a user supply the kerberos ticket to the application?  (sorry, other than a vague idea of what kerberos does I'm a kerberos newb).  And yes, this would be something which needs support in the sasl lib used.

**Comment by arthurlogilab** [comment]
The idea behind kerberos auth is that the user doesn't supply anything, it's the system that provides a ticket and does the negotiation with the kerberos server (which is also done on the imap server side). The kerberos ticket can be initialised by the user using "kinit", listed using "klist", and in some configurations the ticket initialisation is done while logging in (transparently).

**Comment by hpk42** [comment]
how would this work on android or ios? 
how does "the system" provide a ticket there?

**Comment by arthurlogilab** [comment]
I have no idea how kerberos works for android/ios

**Comment by hpk42** [comment]
are you using Delta/Desktop or what's the context of your interest?

**Comment by hpk42** [comment]
ok, it's not an actionable item them for now so better disucssed at the support forum https://support.delta.chat .  If someone has more info on how this could be done on multiple platforms this can be re-opened.
