### ISSUE TITLE
show only self-locations that were also reported to a given chat?

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-core#617]

**Comment by hpk42** [comment]
Not sure it relates but i was wondering about the following location streaming UX: 

1. location streaming causes outgoing chat messages in those chats where it is activated 
2. mapping locations happens on a per-chat or global basis.  If it's per-chat then all known locations for the people in the chat are mapped, *independently* if they streamed to this particular chat. 

This way, basecamp can have 5 chat groups, all members from all groups stream to basecamp, but it's still possible map each of the 5 chat groups separately and communicate with them -- i think it's natural to expect that you'd like to chat with those you are mapping/looking at.  

If this is already how the current development android  works, then nevermind ;)

**Comment by r10s** [comment]
> _independently_ if they streamed to this particular chat.

we had this initially, but this seems to confuse people at once. example:

- Alice, Bob and Claire are in group ABC
- Bob, Claire and Dave are in group BCD
- Bob streams locations to BCD
- if now Bob meet Alice in person and has a look on group ABC on Alice's handy, Bob may not expect seeing his location in group ABC

this is already the current state (apart from bugs :), however, the _own_ position is not tracked strictly to the groups - instead you see your own track in each group you open a map which may also confuse ppl - "i have _never_ shared my location with that group!".

maybe we can solve this also by other ui elements eg. by showing the positions received through other chats differently, however, maybe we should not start with that from scratch - and, still it would require to track the chat_id together with the position what this issue is about.

**Comment by r10s** [comment]
> i think it's natural to expect that you'd like to chat with those you are mapping/looking at.

this would work currently - the positions shown on a map always match the group members.

wrt. "global map": this will show all locations independently from a chat then - really all location information available on a device - probably with an option to go to the corresponding chat directly.
