### ISSUE TITLE
Gossip

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-core#63]
Spread keys in groups of recipients, see https://autocrypt.org/level1.html#key-gossip

- [x] add Autocrypt-Gossip header to encrypted part
- [x] parse Autocrypt-Gossip header from encrypted part 
- [ ] use the gossipped keys as defined in the Autocrypt spec

**Comment by hpk42** [comment]
yes! :+1:

**Comment by r10s** [comment]
:)

**Comment by r10s** [comment]
yeah, it's done :)
