### ISSUE TITLE
Float decimals are cut off on Mac OSX

### ISSUE THREAD

**Issue by nicodh** [deltachat/deltachat-core#631]
Even on current master (which sets the locale) I get:

`printf("latitude %s", latitude); // 47.980068`
				
`printf("latitude %f", atof(latitude)); // 47,000000`

Very strange. It already worked somehow...??

**Comment by nicodh** [comment]
It seems the setLocale does not work. I debugged:

`lc = localeconv();`
				
`printf("Local decimal_point: %s\n",lc->decimal_point);`

`Local decimal_point: ,`

**Comment by nicodh** [comment]
even if I set 
`setlocale(LC_ALL|~LC_NUMERIC, "C");`
just in the line above it does not work...

**Comment by r10s** [comment]
@nicodh does a `printf("%f", 1.2)` respect the locale? does it return `1.2` or `1,2`?

and: can you try a `setlocale(LC_ALL|~LC_NUMERIC, "");` ("" instead of "C" as the last parameter) (via https://stackoverflow.com/questions/4631310/why-does-osx-document-atoi-atof-as-not-being-threadsafe =

**Comment by nicodh** [comment]
Empty setLocale does not help, 
printf("%f", 1.2) returns 1,200000

I also tried strof  since it seems atof might be deprecated:
https://www.codecogs.com/library/computing/c/stdlib.h/atof.php

But same result...

**Comment by r10s** [comment]
@nicodh  thanks for testing. i will investigate further and/or implement a workaround.

**Comment by r10s** [comment]
@nicodh added a workaround in https://github.com/deltachat/deltachat-core/pull/632
