### ISSUE TITLE
Can't send message: limit of recipients reached

### ISSUE THREAD

**Issue by nicodh** [deltachat/deltachat-core#647]
When trying to send a message I get an error 
` SMTP failed to set data: Transaction failed: 5.7.1 <DATA>: Data command rejected: limit of 400 rcpts per 24 hours for client deltachat@***.me reached`

I use the mail address only for deltachat and it is not published anywhere, so there might be an issue with the SMTP API usage since I definitely have not sent messages to 400 recipients in the last 24 hours...

**Comment by r10s** [comment]
maybe all recipient in a group count for the number of messages for that provider?

**Comment by nicodh** [comment]
So I got feedback now: 

> Zu Ihrer Frage kann ich Ihnen sagen, dass sich das Limit von 400 Mails in 24 Stunden sowohl auf die Anzahl der Mails, als auch auf die Anzahl der Empfänger bezieht.

So it seems having one or more groups with multiple users and location streaming turned on for a couple of hours day you may easily reach the limit...?

**Comment by r10s** [comment]
so, in a group with 40 recipients you can post 10 messages ... or 10 positions. i think the provider should adapt his limits ;)

**Comment by adbenitez** [comment]
@r10s similar issue for Gmail, 50 msgs to 10 people or 1 msg to 500 people, you can send only 500 msg per day and every receipt count as an individual message, 

> i think the provider should adapt his limits ;)

I don't think these providers will change that limit anytime soon just because you ask him kindly ;)
a fact is that we need better providers, or self-hosting if you can, would be awesome to have a community of people self-hosting email servers for their own Delta Chat use, and sharing the servers with peers like Mastodon instances do, people could donate or pay some little amount to help keep they instance up.

**Comment by r10s** [comment]
well, we'll see how things evolve :)
afaik, at least one provider already adapt some things toworks "Chat over E-mail" :)
however, i think we can close this issue, no actionable item, there is not much the core can do about this.
of course, we can continue the discussion in the forum.

**Comment by adbenitez** [comment]
agree,
btw, what provider?? =)

**Comment by adbenitez** [comment]
what core or Delta app could do is provide number of messages you have sent in a day(including read receipts) and show it in they user profile so users know how many messages they had send, and know if they are reaching the limit

**Comment by r10s** [comment]
yip, sth. as "messages sent today" can make some sense. however, to be exact one also has to know if this is "per 24 hours" or "per day", at which time the counter is reset or if it is a "rolling counter" and so on. so, also here, the details might be hard :)

**Comment by devSJR** [comment]
@adbenitez I guess Open-Xchange. https://www.coi-dev.org/
