### ISSUE TITLE
log_ringbuf - internal logging - not existant in dc_context any more?

### ISSUE THREAD

**Issue by csb0730** [deltachat/deltachat-core#658]
In v0.20.0 there was a log_ringbuf existing for internal logging.
I could be used by user by "settings->info->info" button.

In v0.41.0 I can't find this buffer any more.

Is it moved to another file or is a similar feature available by a different approach?

**Comment by r10s** [comment]
it's just no longer there. to keep things simple, it's now totally up to the ui to handle the logging. this also makes sense as the core-log typically go to the system log where it get mixed with non-core-log-info. in general, it is useful to show all these information to the user.

in android you'll find this combined log at settings / advanced / view log

**Comment by csb0730** [comment]
Thanks for the hint, I'll try :-)

**Comment by r10s** [comment]
you're welcome!
