### ISSUE TITLE
Version 0.9.7/8 not found in f-droid

### ISSUE THREAD

**Issue by gitkald** [deltachat/deltachat-core#67]
I'm wondering, that the last version of DC in the f-droid repository is 0.9.6 and 0.9.8 where launched on 2017-11-15:

Now I found this on the f-droid pages:
```
We can't build this version: The build for this version appears to have failed. Check the build log.
Version code: 473
```
[https://f-droid.org/wiki/page/com.b44t.messenger#Description](url)

Is it possible, that something going wrong?

**Comment by Ampli-fier** [comment]
There was an issue reported to Andoid: [#204](https://github.com/deltachat/deltachat-android/issues/204).

In the meantime two builds completed:
* [473](https://f-droid.org/wiki/page/com.b44t.messenger/lastbuild_473) v0.9.8
* [483](https://f-droid.org/wiki/page/com.b44t.messenger/lastbuild_483) v0.9.9

But they do not appear, as you stated ... 

apk for v0.9.9 should get copied or moved [here](https://f-droid.org/repo/com.b44t.messenger_483.apk), but is not.

**Comment by gitkald** [comment]
Ah, ok. Thx for feedback.

**Comment by r10s** [comment]
I am wondering if we should provide downloadable .apk files together with the versions. F-Droid sometimes takes a long time until there is a new version available.

**Comment by r10s** [comment]
- we published 0.9.9 on 2017-11-18 17:10
- F-Droid build it on 2017-11-21 23:35

.. that are 3 days and 6 hours, not _that_ bad. However, up to today, the link on the F-Droid repository and in the app is not updated ... and this is already about 6 days ... and still waiting.

@Ampli-fier where do you always get the build information from?

**Comment by Ampli-fier** [comment]
I used the link that was put to the Android issue and exchanged the build number in the URL.

Do you have an account at F-Droid?
They have issue tracker as well: https://f-droid.org/en/issues/

**Comment by r10s** [comment]
> I used the link that was put to the Android issue and exchanged the build number in the URL.

Okay, this is simple :)

**Comment by Ampli-fier** [comment]
Finally, apk for v0.9.9 is available for [direct download](https://f-droid.org/repo/com.b44t.messenger_483.apk).

**Comment by r10s** [comment]
:)
