### ISSUE TITLE
How to get mails recognized as group chats?

### ISSUE THREAD

**Issue by mario98** [deltachat/deltachat-core#69]
Hi,

here is the scenario. I have **Person A** (as a single person) and a **group containing Person A and Person B** in my chat list. Then I went to my PC and sent an email to both Person A and Person B (both were in the "To:" field).

Actual result:
On my phone in Delta Chat, the message appeared in the chat history of the chat with Person A but not in the chat history of the group.

Expected result:
The message should appear in the chat history of the group, and only there, since it was send to all participant of the group.

In general, can you explain a little more how you implemented the group feature, i.e. how does Delta Chat at the moment recognize messages that came from / were send to a group, and how it is supposed to be used in a mixed client scenario (Person B does not even have Delta Chat at all)?

**Comment by csb0730** [comment]
Hi Mario,
 I did a first documentation of general behaviour of all that. It describes in a drawing/table some existing szenario's, some whishes and even what You describes. I had some discussions at the begining of my delta chat use with Björn about that.
 I will post this here soon, so Björn ( @r10s ) can comment it and I hope this will get useful for everyone here.

**Comment by csb0730** [comment]
coming soon :-)

**Comment by mario98** [comment]
I think an email with multiple recipients should automatically be treated as a group chat, no matter if the group name or id or any other markers are in the subject. Keep in mind that Delta Chat will only succeed if it is maximally compatible to non-Delta Chat clients.

When there is a group which has the exact same recipients, this email should be shown in this group, always.

If such a group (defined my this particular combination of recipients) is not present, but at least one member of the group is already in your chat list, this should be treated as an invitation to a group chat.

**Comment by hpk42** [comment]
On Thu, Jan 04, 2018 at 17:12 +0000, mario98 wrote:
> I think an email with multiple recipients should automatically be treated as a group chat, no matter if the group name or id or any other markers are in the subject. Keep in mind that Delta Chat will only succeed if it is maximally compatible to non-Delta Chat clients.

I agree that nice interactions with existing non-delta
apps is a good goal.
 
> When there is a group which has the exact same recipients, this email should be shown in this group, always.

suppose, with A, B and C all using Delta for creating two groups:

- A opens a group with B and C on one topic

- A opens a group with B and C on another topic

Now A sends, from a non-delta mail app, a mail to B and C.  It would be ambigous
where to put it.  To prevent A from opening a second group seems too harsh
and breaks how other messengers do it (they allow multiple groups with
the same recipients just fine).  But maybe there is another way to get consistent
and useful behaviour?

For the mail from A's mail app, B and C can look at parent mails
("References" header i believe) and see if they already have a
group-ID attached and use that. IIRC Delta already does that.  

If there is no group-ID attached to the references but B and C have one or
more existing A,B,C groups then Delta could offer to put the mail in 
one of these groups context.  If there are no A,B,C groups Delta just 
asks for confirming the invitation and creates a new (canonical) group.

The tricky part is maybe how B and C (and in practise many more recipients) 
can agree on the group-id.  B and C could make different decisions
(B says "treat the message as belonging to this group X"
while C rather creates a new one). It's possible that B and C have
different group associations - one uses "X", the other creates a new one. 

I guess subsequent messages from B or C to the group could resolve this issue.
In any case, a reply from B and C to the respective group properly references
the original mail from A, so A's mail app can thread it properly.  In some
sense, it's not a big problem if B and C have made different decisions
how to treat the mail(s) from A -- as long as they always send the
proper "root" reference.

I haven't fully thought this through -- a lot of devils in details i guess.
Maybe @r10s can point to a description of the current algo (or make up one)?

**Comment by r10s** [comment]
I also have some rough ideas on this issue (sorry, german only as initially meant only for me :)   
https://cryptpad.fr/code/#/1/edit/Sj86X+tDPV4dWqP4HuGpxA/tsv7bhiL0gp1WZ9kyMaxTlaq/ (this is about how it is supposed to work in the future)

The current bahavious is bad: Messages from other MUA send to multiple To: show up as a single chat from the sender, the other To:/Cc: are not even shown (we did this in older versions, but removed this code as it was not always working and ad-hoc groups seems to be the better solution at all)

However, I agree that this all but not simple and requires some more thinking :)

**Comment by mario98** [comment]
> suppose, with A, B and C all using Delta for creating two groups: - A opens a group with B and C on one topic - A opens a group with B and C on another topic 

Oh, I didn't know you can open multiple groups with the same persons. This makes things complicated, indeed.

**Comment by r10s** [comment]
@hpk42 @Ampli-fier @testbird @mario98 @csb0730 and others: The PR #118 introduces the following changes:

1. all messages that have more than one recipient, either in To or Cc, form a group chat now; no matter if the messages was created with Delta Chat or a normal MUA. Group members are the recipients and the sender.
2. if such a group message has no internal [Chat-Group-ID](https://delta.chat/en/spec#groups) (eg. because it is created initially by another MUA), Delta Chat checks if there is another group with the same members, if so, this group is taken. If there are multiple matching groups, the one with the most recent activity is chosen.
3. if no matching groups could be found, Delta Chat creates a new group with the members, the subject of the message is chosen as the group name and the Chat-Group-ID is created as a 64 bit value based on the member list (so that different Delta Chat recipients will chose the same Chat-Group-ID in future).
4. after the creation of these Ad-hoc groups in 3. the groups are treated as normal groups, there is no other special handling

Maybe point 2. can be improved, however, taking the references into account makes things more complicated eg. if the member list is not the same. We mayl run into situations then, where the shown member list is not equal to the reciepients of messages sent by other MUAs. So, I decided to keep things simple :)

**Comment by testbird** [comment]
Looks good as far as I can tell. Only remark I would have (if your not already doing this) is to only compare the formal <...> part of email adresses (Associatad string <formal@email.address>), to avoid problems when some group members use different nick names for addresses.

**Comment by r10s** [comment]
i'm only comparing the formal part case-insensitive, however, there may still be some problems with e-mail-addresses containing eg. german umlauts. Anyway, this also affects other parts of delta, there is also an issue about this somewhere iirc.

**Comment by r10s** [comment]
fixed with #118, please reopen if not
