### ISSUE TITLE
Delta-core to always refer to last message for improved non-Delta mail app threading

### ISSUE THREAD

**Issue by hpk42** [deltachat/deltachat-core#72]
When i write a mail with my non-Delta mail app to Delta/Android and Delta/Android replies, it shows up in a totally different mail thread, i.e. does not reference my mail.  I suggest that Delta always references the last mail in a message chat window -- seen from the non-Delta mail app that feels natural and for Delta/Android it doesn't change anything: the message and its replies will simply appear in chronological order.

**Comment by r10s** [comment]
Would it help if Delta Chat uses the same References header as the mail from the non-Delta-Client?
In fact, Delta Chat generates a random one to keep things for other MUAs together (see [here](https://github.com/deltachat/deltachat-core/blob/master/src/mrmimefactory.c#L182)) - obviously, this does not work for the first reply.

Using the In-Reply-To: does not work well - many MUAs are not prepared for threads nested very deeply which would happen with Delta Chat very easiy, see https://github.com/deltachat/deltachat-android/issues/36#issuecomment-298159178

**Comment by valeriopaladino** [comment]
Maybe this could be made into a configurable option? Apparently the In-Reply-To header could use the same logic used for Chat-Predecessor (https://github.com/deltachat/deltachat-core/blob/0d122fcb814bb07dd1ff049ffa4cb792bc0a56a9/src/dc_mimefactory.c#L562), or maybe use the first message in the tread, to have a single flat thread in Gmail (which is how the mails are displayed in Evolution right now).

**Comment by hpk42** [comment]
It's worth a try IMO to set  "in-reply-to" to the first message in a chat, instead of the last one.  It would avoid threading.  @r10s or was there something that makes this a bad idea?

**Comment by r10s** [comment]
@hpk42 we can try just try it and see how this works.

might cause some problems if the original message is very old and maybe deleted or so. not sure.

**Comment by r10s** [comment]
@hpk42 the commit ec9418a5dee9de015781815c9956f1dcd3ad5185 references the _newest_ messages as this was simpler and more straight forward.

_always_ using the oldest one would be just a change from min() to max() in the select statement from the linked commit, however, as mentioned, if this is sufficent, it will be easy - if we want a new anchor every some days or so, it would get more complicated.

let me know what you're thinking :)

**Comment by testbird** [comment]
> Would it help if Delta Chat uses the same References header as the mail from the non-Delta-Client?

That!
Exept for MUAs not supporting the `References` header, would likely be the better (default) solution. Not depending on a full history, and no deep nesting of messages.

The full threading may still serve as a very good per chat option!

**Comment by testbird** [comment]
If there is no explicit `References` header in the received non-Chat message, the `References` in the reply may be set to the message ID of the received non-Chat message?

**Comment by Spass1966** [comment]
Why is this issue closed? It still exists. MUA users *still* receive seperate emails from me clogging up their inbox.
