### ISSUE TITLE
Please consider using EXISTS() instead of COUNT() where possible.

### ISSUE THREAD

**Issue by textbrowser** [deltachat/deltachat-core#74]
If I understand mrmailbox_delete_contact() correctly, COUNT() is used to determine if something exists. The exists() operator is better suited in such instances.

```
stmt = mrsqlite3_predefine__(mailbox->m_sql, SELECT_COUNT_FROM_chats_contacts_WHERE_contact_id,
			"SELECT EXISTS(SELECT 1 FROM chats_contacts WHERE contact_id=?);");
		sqlite3_bind_int(stmt, 1, contact_id);
		if( sqlite3_step(stmt) != SQLITE_ROW || sqlite3_column_int(stmt, 0) >= 1 ) {
			goto cleanup;
}
```

https://sqlite.org/lang_expr.html

https://books.google.com/books?id=v5OYlkt6uKYC&pg=PA353&lpg=PA353&dq=sqlite+exists+operator&source=bl&ots=hdR1ot_MNG&sig=YCTSBo_PfEcm_fesXD33nNMEYUo&hl=en&sa=X&ved=0ahUKEwjqnK2H75jYAhXCzIMKHSQPDWoQ6AEIZzAK#v=onepage&q=sqlite exists operator&f=false

**Comment by r10s** [comment]
Yes, you are right, EXISTS should be faster than COUNT, we will consider using it in the future or in time-critical situations.

However, in this example, or generally, if the result is typically only one row (or very few), there should be very no measurable speedup - at the cost as additional testing requirements and potentially new bug :)
