### ISSUE TITLE
distinguish between verified and unverified contacts

### ISSUE THREAD

**Issue by testbird** [deltachat/deltachat-core#75]
The UI can then, for example, list all unverfied contacts and chats with unverfied contacts above all others, with a red backgound and a button that shows the fingerprint to compare manually through another way of (non-chat) communication.

**Comment by testbird** [comment]
Well, maybe make this "eventual verification" support part of the autocrypt spec anyway.

**Comment by r10s** [comment]
with verified/unverified you mean whether you have compared a fingerprint or not with a user?

iiuc, this would required at first a button "fingerprints do match", a qr code comparison or sth. like that.

**Comment by testbird** [comment]
With the new fingerprint verification, will DC inform the user if a message is signed by an unverified key instead of a verified key of the contact?

**Comment by r10s** [comment]
verified contacts are now avaliable as a "Labs" feature (see QR code options) and can be distinguished from unverified ones by a "blue checkmark":

![image](https://user-images.githubusercontent.com/9800740/41003978-96f2f222-6918-11e8-88a1-aee91ceb46cc.png)

i think this issue can be closed.

**Comment by testbird** [comment]
Uuh well, UI-wise, drawing of checkmarks is implemented, so scraping and closing this is ok. But, the checkmarks are currently automatically drawn for everyone who requests it with a static semi-public token.

In good labs, most things never leave it in another form than scrap. :-) So it's good that only well re-thought and re-worked solutions can get appoved! => https://github.com/deltachat/deltachat-core/issues/168

**Comment by r10s** [comment]
> requests it with a static semi-public token

but it's still up to the inviter to generate the token and to give it to someone out-of-band. so it does not break the out-of-band-concept as such. however, as you mentioned, this is another discussion :)
