### ISSUE TITLE
End-to-end encryption not activated after autocrypt with enigmail

### ISSUE THREAD

**Issue by petmos** [deltachat/deltachat-core#76]
**Delta Chat version**
v0.9.9
**Expected behavior**
Messages to a known contact (which is using autocrypt) should be encrypted.
**Actual behavior**
All messages sent by delta.chat are still unencrypted even when contact has sent an autocrypt header before.
But delta.chat decrypts all encrypted mails sent by thunderbird with enigmail nigthly build from 21-12-2017 correctly.
Enigmail recognises autocrypt header sent by delta.chat correctly and encrypt all messages to delta.chat.

This looks like key sharing works vice versa but delta.chat doesn't activate encryption.

**Comment by r10s** [comment]
does Enigmail send out the header with the flag prefer-encrypt=mutual?

Autocrypt encryption will only be enabled if both ends have set prefer-encrypt=mutal (this is to avoid unexpected undecryptables in a multi-device-setup)

See https://github.com/autocrypt/autocrypt/issues/304#issuecomment-353856021 how to enable the setting.

**Comment by petmos** [comment]
I checked the enigmail header:
autoencrypt: addr=XXXXXXXXX@XXXXX.XXX; prefer-encrypt=mutual; .... where XXXXXXXXX@XXXXX.XXX is always my delta.chat address.
Should't there be an entry with my thunderbird/enigmail address like: addr=my.enigmail@addr.ess; prefer-encrypt=mutual too?
When I tap inside dekta.chat on the received enigmail message and choose Info I see:
"Encryption: End-to-end, unknown signature"

**Comment by r10s** [comment]
> Should't there be an entry with my thunderbird/enigmail address like: addr=my.enigmail@addr.ess; prefer-encrypt=mutual too?

yes, you have to look at emails send out by enigmail. it is important that _both_ ends send out the prefer-encrypt setting. Delta Chat send out out by default, Enigmail has disabled it by default (does not send out the prefer-encrypt header); therefore you have to enable it as described here: https://github.com/autocrypt/autocrypt/issues/304#issuecomment-353856021

**Comment by petmos** [comment]
Sorry, I was unclear. I followed your link and checked  "Prefer encrypted emails from the people you mail with", then I controlled the sent header. But still no prefer-encrypt=mutual from enigmail.

**Comment by petmos** [comment]
It's not a delta.chat related bug.
