### ISSUE TITLE
Error : mailsmtp_rcpt ... unexpected error code

### ISSUE THREAD

**Issue by marukome** [deltachat/deltachat-core#80]
Version 0.11.4 

Sending a message to some recipients produces this error message.

**Comment by r10s** [comment]
Thank you for your report. Can you please provide more details about the used server configuration? And maybe a way how the error can be reproduced.

**Comment by marukome** [comment]
server: i'm using a gmail account 
the issue occurs with very few recipients (not delta-chat users) with varying email providers (i.e. google, hotmail, yahoo)
