### ISSUE TITLE
Have the client pull messages after an off-line period

### ISSUE THREAD

**Issue by ericzolf** [deltachat/deltachat-core#84]
As I have all my Android devices not actively connected to WIFI when the screen is off (it's an option to save energy), IMAP-Push doesn't work properly and chats arrived during this off-line time appear on the client only after I've sent a message myself (or probably as documented somewhere after 30min, but I seldom look at my smartphone for 30min in a row)

I guess the issue would be the same on a desktop, where the client isn't running all the time, or even if you're abroad without WIFI or data roaming, or after re-booting, or being off-line for a certain period of time for any reason. That's why I plug this issue on core.

The client should hence trigger an IMAP-Pull once it comes back on-line to download all chats arrived during the off-line period. At least on Android it's possible for an app to get notified when this happens, and this should be done anyway during any start of the application.

**Comment by Ampli-fier** [comment]
There is another way to update the messages from the server. Instead of sending a message to yourself you could reconnect manually: Advanced settings - Account settings - Hit the checkmark at the top.

**Comment by testbird** [comment]
https://stackoverflow.com/questions/6169059/android-event-for-internet-connectivity-state-change

**Comment by testbird** [comment]
Added the state changes to https://github.com/deltachat/deltachat-core/wiki/IMAP-strategy

**Comment by r10s** [comment]
probably the [new poll-mode](https://github.com/deltachat/deltachat-android/issues/269) will fix this issue:
- polling is done in background
- push-connection is only established when the app goes to foreground
