### ISSUE TITLE
uuencoded attachment included in message body is not detected as attachment

### ISSUE THREAD

**Issue by csb0730** [deltachat/deltachat-core#90]
If this happens, complete attachment is treated as normal text and is copied to database. The result is that DC freezes if this message will be displayed.

In my case a message size of 15MB occured !

@r10s has some details about it.

**Comment by csb0730** [comment]
@r10s 
beside solving this issue IMHO it would be a good idea to check message size before copying it to database.

Proposal:
  There should be an internal emergency limit for max message size (maybe 100kb) to prevent freeze of the application.
  I suspect that there will be some new cases in future which not will be covered due to misinterpreting a message.

**Comment by r10s** [comment]
> beside solving this issue IMHO it would be a good idea to check message size before copying it to database.

This is definitely an good idea

**Comment by csb0730** [comment]
v0.15.0 (github versioncode=513)

Hi @r10s, 
this happens again now for my phone! DC unusable if certain chat is opened.
Dialog appears that DC is not responding and can be closed by Operating System!

Please introduce as soon as possible an emergency limit for database' message size! Then user at least has the chance to delete the affected message.

Maybe this is related to issue N° 254 from deltachat/deltachat-Android?

**Comment by r10s** [comment]
thank you for the additional information, regarding https://github.com/deltachat/deltachat-android/issues/254 - hard to say if this this related, might me.

**Comment by csb0730** [comment]
It must not but it can be.
But ... really: please introduce an emergency limit for text size (and/or bugfix). A standard user will not have a chance to delete such a message by "backup-search message with external db browser-delete it-reimport backup!" :-/

**Comment by r10s** [comment]
> But ... really: please introduce an emergency limit for text size (and/or bugfix).

yes, I think this is a good idea :)

**Comment by csb0730** [comment]
Hi @testbird,
this issue makes the app unusable if it happens! Not important for v1.0 ?!

**Comment by r10s** [comment]
@csb0730 iiuc the milestone is moved to the project here: https://github.com/orgs/deltachat/projects/2

@testbird thank you for pushing this forward. i have no experience with the github project functionality - maybe we can additionally leave the milestones at the project so that people do not get confused? currently, i also find it easier to have a milestone-tagged list, because when i work on the issue list, it seems to be more focused to me. however, maybe it's only my habit :)
but we should take care not to over-engineer these lists and issues so that new people have a chance to understand what is going on here. keeping things simple seems to be one of the hardest jobs :)

**Comment by testbird** [comment]
Sorry, I couldn't try out and finish everything yesterday.

Here is what I did and why:
I created a second project for the 1.0 release https://github.com/orgs/deltachat/projects/2, and reduced it to be merely a simple issue list and monitor.

The advantages are, that
*  it supports one complete list containing the 1.0 issues of both -core and -android. (Instead of the different tabs in the old milestone interface, the open issues are listed in the "To do" column, and the already closed ones under  "Done", .)
* There is no need to manually manage check marks, closing/re-opening a listed issue will automatically move the issue between the "To do" and "Done" columns.
* Compared to the milestone list, it is also possible to drag and drop the issues into a manual order, if desired and where it makes sense, and to add additional notes into the list ("+" on the column). 

Adding further issues can be done through the right panel of an issue (just like with milestones), or through the "+ add cards" search interface on the project page.

 (Only the general "Deltachat Isses" project, shows a "Issue Pool" and a "Lineup (To do)" column in the sense  that it allows picking out issues and create some kind of technically derived bug fixing plan.)

**Comment by r10s** [comment]
As this gets off-topic here, i suggest to continue the discussion at https://github.com/deltachat/deltachat-core/issues/119

**Comment by r10s** [comment]
@csb0730 i think the UUencode'd attachments come from Outlook? If you can send mails from outlook, can you please send one with a larger attachment to r10s at b44t dot com? (so that i have an original mail for testing)

**Comment by r10s** [comment]
does anyone have an idea which MUAs do still send UUencode'd attachments today?

**Comment by r10s** [comment]
i'm really wondering where these UUencode'd mails come from, in outlook it my be the result of an bug, see https://social.technet.microsoft.com/Forums/office/en-US/52bf4928-b6dc-42e4-8ec8-47856ca19f60/outlook-2013-sends-plain-text-with-attachment-mail-as-uuencoded-with-smtp-connection-only?forum=outlook , however, there are not much information available at all (or i am unable to find them)

Anyway, i think i will fix this issue not by handing UUencode'd mails but by just not crashing, the start of the UUencoded'd mail will be shown in plain text then. I do not think that it makes sense to put much development effort into this legacy format - even [microsoft does not longer maintain it](https://msdn.microsoft.com/en-us/library/ms875966(v=exchg.65).aspx) - although they seem to send it in a way ...

**Comment by csb0730** [comment]
Hi @r10s 
as I read this: I find it worth to fix that problem because this is not very difficult.
Anyway, other MUAs don't have a problem with these kind of attachments and
if it wouldn't be fixed I'll have a problem with a significant number of incoming messages!

IMHO this issue should be solved.

**Comment by r10s** [comment]
> if it wouldn't be fixed I'll have a problem with a significant number of incoming messages!

But where do the UUencode'd messages come from?
Also, I do not think that it will _not very difficult_ to implement this, they may be corner cases, multiple attachments, different encoding and so on. Myself is not up for this right now, but I will be happy to support/review suggestions and efforts.

Anyway, this issue was more about the crash and the deadlock which is fixed now. So i think we should leave this issue closed and open a new one as a "feature request", possibly with evidence of MUAs producing this legacy format .

**Comment by Ampli-fier** [comment]
I remember uuencode from the Unix/Linux world. I still use the method to copy a file (e.g. tar or zip file) via the Clipboard between systems.

With the Unix/Linux mail tool 'mailx' or 'mail' one can send attachments _uuencoded_ as described [here](http://www.shelldorado.com/articles/mailattachments.html) from the command line.

Searching the web reveals uuencode support in old Thunderbird versions or by using a plugin (Mnenhy?).

**Comment by r10s** [comment]
Okay, copy+paste uuencode or a `uuencode ... | mail ..` on the command line seem to be good reasons to support uuencoded mails. I was really wondering before where such mails come from in 2018 :)

I reopened the issue, I think sooner or later Delta Chat should support these types or attachments.
I also removed the Release 1.0 Milestone - crashes are fixed and I think if this feature should not hold back a 1.0 release.

**Comment by r10s** [comment]
just playing around a git: thunderbird does not support uuencode out-of-the-box, or? anyone knows which MUA _does_ support it out-of-the-box?

**Comment by csb0730** [comment]
I'm working about this issue together with @r10s to enable DC to handle this.
This is a standard use case.

**Comment by Ampli-fier** [comment]
IAC (I am curious): Where do the mails come from (with uuencoded attachments)?

**Comment by r10s** [comment]
@Ampli-fier apart from the command line as you mentioned yourself I have no idea i don't know, maybe @csb0730 has more information on this in between :)

Regarding For me, on ubuntu 16.04 with Thunderbird, the uuencoded attachments do not work - is there a pluging, a setting switch or sth. like that required?

**Comment by csb0730** [comment]
I'm using Thunderbird 52.6.0 on bunsenlabs hydrogen (Debian 8.2 Jessie base).
It's handling the uuencoded attachments properly :)

**Comment by r10s** [comment]
okay - maybe i am doing it wrong :)
however, there is some evidence of uuencode in 2018 :)

**Comment by csb0730** [comment]
New fork and branch created as agreed with @r10s 

[fork for uuencoded text handling](https://github.com/csb0730/deltachat-core)

**Comment by r10s** [comment]
you have to select the fork `csb0730-uudecode-1`; alternatively, use this direct link: https://github.com/csb0730/deltachat-core/tree/csb0730-uudecode-1

**Comment by csb0730** [comment]
Pull request done

**Comment by r10s** [comment]
@csb0730 i've created a proper frame for calling a function that does the uudecoding work.

uudecoding can be implemented independently of other parts in [mruudecode_do()](https://github.com/deltachat/deltachat-core/blob/master/src/mruudecode.c#L27); i've added some description to the source about how `mrmimeparser.c` expects the function to work.

All implementation details about uudecoding should go to `mruudecode.c`, if functions are needed, they should be static here. To hide the implemetation details `mruudecode.h` should not be modified.

please let me know what you think about this :)

**Comment by r10s** [comment]
great :)

**Comment by csb0730** [comment]
Main customizing is done and new implementation is running. After some code cleaning I will rise a next pull request. Estimation is in next days :-)

**Comment by csb0730** [comment]
See pull request #160 ...

**Comment by csb0730** [comment]
3rd rework launched in PR #161

**Comment by csb0730** [comment]
Continue with that?

See PR 4th rework.

**Comment by r10s** [comment]
i will come back to this, however, currently stability and reliability has a higher priority than adding new features :)

**Comment by csb0730** [comment]
5th rework done - all functions & files renamed to _dc__ naming convention

**Comment by r10s** [comment]
well, all this seems to bind more resources than first thought :)

please let me note that i am still not convinced that uuencode support in 2018 is really necessary.
it even may be dangerous to have code that is very seldomly used and not well tested. this may not help with the goals of stability and resilience.

and i am also not sure if it is a good idea to strengthen old formats that have been replaced by superior formats longly.

i would like to go some steps back in this issue and would like to know:
- are there any other apps that send uuencoded attachments by default
- are there any other apps that can read them by default. 

of course, this can be done by using cli-tools and plugins, however, i do not think this is the main target group.

i am not saying that we should not implement uuencode, however, maybe it is just the wrong time. and i would like some kind of needfinding before.

**Comment by csb0730** [comment]
> well, all this seems to bind more resources than first thought :)

Yes, indeed !  ;-)

But basically this has been caused by the string and pointer handling of C which is not my daily business in programming issues. And not caused by the problem itself ;-)

What I can contribute to the evidence of still existing email attachments of this format is my last received mail in that format with some details:
1. Date 8. Jun 2018
2. Sending MUA is Outlook 32Bit (Version unclear)
3. Mailheader: "X-Mailer: Microsoft Outlook 14.0"
4. Mail properly shown & decoded by Thunderbird 52.8.0 (64 Bit, german, no Add-on's installed) at Debian 8.2 Linux (BunsenLabs)

I saw that here in the complete issue description is no screenshot available how this issue is presented in DC. So here is one:

![screenshot_2018-07-12-22-52-36-uuenc-attachment](https://user-images.githubusercontent.com/30560716/42660795-7b2aa572-862c-11e8-8b63-c43d67d0c40d.png)

- the yellow box shows the uuencoded attachment part
- the red boxes showing the start character of each encoded line

Maybe this helps a little that even other people now recognize such attachments and this issue!

Regarding frequency of that kind of attachment: I can only say that one of my friends sends every week one or two mails I cannot read because of that issue.
He's not an IT skilled user so he don't know something about email encoding details.

Furthermore we cannot control who, what MUA and under what circumstanced this "old" method for email attachments is used.

With all the efforts invested and lessons learned in mind I would estimate that a proper solution is done by about 95%. Let's to the last step :-)

**Comment by csb0730** [comment]
> it even may be dangerous to have code that is very seldomly used and not well tested

Fully agree with that !

I'll provide myself for doing testing. I'm directly affected by this issue anyway  :-)

**Comment by r10s** [comment]
closing this for now, see https://github.com/deltachat/deltachat-core/pull/212#issuecomment-429527284 for some backgrounds

**Comment by csb0730** [comment]
Hi @r10s

to make the issue around uuencoded attachments clear for everyone and to understand the situation in current times, I'm doing some research with all MUA which are available for me and test their behaviour. These results are even for me very interesting ;-)

I'm quite finishing that and will do a summary of all results in support forum in next days.
