### ISSUE TITLE
No Build on F-Droid

### ISSUE THREAD

**Issue by gitkald** [deltachat/deltachat-core#92]
On F-Droid I found the follwing Notes:
**Versions**
We don't have the current version of this app. (Check mode: Tags) (Auto-update mode: Version v%v)
The current (recommended) version is 0.12.0 (version code 510).

**0.12.0**
We can't build this version: The build for this version appears to have failed. Check the build log.
Version code: 510

Please, can someone check this?

**Comment by r10s** [comment]
Have you seen the build log? I have not found it. It should at https://f-droid.org/wiki/page/com.b44t.messenger/lastbuild_510 [via https://f-droid.org/wiki/page/com.b44t.messenger ] however, there are no additional information. Checking out Delta with the f-droid tools locally works (I have not tried a build), so all in all I may be that this is more an F-Droid issue than an Delta issue.
Maybe you can check this more detailed? I do not have the time for it currently.

**Comment by Ampli-fier** [comment]
The last build logs are referenced [here](https://f-droid.org/wiki/page/com.b44t.messenger#Versions). Just that the referenced files do not exist (as you already figured out).
Maybe the [Maintainer Notes](https://f-droid.org/wiki/page/com.b44t.messenger#Maintainer%20Notes): -> **[current](https://gitlab.com/fdroid/fdroiddata/blob/master/metadata/com.b44t.messenger.txt)** and -> **[history](https://gitlab.com/fdroid/fdroiddata/commits/master/metadata/com.b44t.messenger.txt)** provide more info about what could be wrong ...

**Comment by r10s** [comment]
The maintainer notes look as always ..

**Comment by Ampli-fier** [comment]
Still no build log ...

**0.13.0**
We can't build this version: The build for this version appears to have failed. Check the [build log](https://f-droid.org/wiki/page/com.b44t.messenger/lastbuild_511).
Version code: 511 

My gut feeling: Probably related to this [commit](https://github.com/deltachat/deltachat-android/commit/a55edf0ba0fea3ff821a93cb6add9816a105ae12).

**Comment by Ampli-fier** [comment]
Open issue [outdated Delta Chat](https://gitlab.com/fdroid/fdroiddata/issues/1092) at F-Droid with last comment:

```
... many builds are failing. They'll be re-run automatically.
```

**Comment by r10s** [comment]
i've also added some more information to the fdroiddata repo at https://gitlab.com/fdroid/fdroiddata/issues/1092 , maybe we get some help from there.

**Comment by testbird** [comment]
v0.13.0 got available now.
 :-)

**Comment by r10s** [comment]
hooray :) \o/
