### ISSUE TITLE
Provide quota information

### ISSUE THREAD

**Issue by Ampli-fier** [deltachat/deltachat-core#94]
**Proposal**

Extend Core to provide quota information about the mailbox.
A pre-check should be made if the server provides the QUOTA capability.

IMAP command example:

`. getquotaroot inbox`
`* QUOTAROOT inbox user/<username>@<domain>.com`
`* QUOTA user/<username>@<domain>.com (STORAGE 747 102400)`

First value=used space
Second value=max space

Core could trigger a warning when the used space exceeds e.g. 95%.

The frontend could provide info about space usage by showing a simple diagram, like Battery usage.

**Comment by r10s** [comment]
the belonging spec is https://tools.ietf.org/html/rfc2087

unfortunately, the quote is folder-wise which is not perfect for Delta Chat, which, in general does not care about folders (in imap slang, folder=mailbox). so, at least displaying a statistic may be tricky and not really straight-forward.

**Comment by Ampli-fier** [comment]
[This](https://addons.mozilla.org/en-GB/thunderbird/addon/display-quota/) is what I had in mind.
My example above shows the quota for the whole account not just one folder.

**Comment by r10s** [comment]
okay, i see, `user/<username>@<domain>.com` is just a tag (a "quota root name"). one can check which tags apply for a given folder but all tags limit the whole account, not just a folder. and in the rfc2087 the tags are _empty_ in the corresponding example.

**Comment by Ampli-fier** [comment]
By knowing the usage and getting warned before limit is reached, the error case can be avoided.

Even with a bigger mailbox, one day the time will come ;-)

When using DC to exchange larger media (eg. video), the mail (with the encoded and encrypted file) will stay in the mailbox, normally. Unless the user deletes the attachment + the corresponding mail.

I see this as _very nice to have_ :-)

**Comment by r10s** [comment]
:)

**Comment by r10s** [comment]
closing this for now here, of course, the discussion can go on in the new support forum at https://support.delta.chat
