### ISSUE TITLE
Messages not removed from mailbox

### ISSUE THREAD

**Issue by Ampli-fier** [deltachat/deltachat-core#95]
**Version info**: 

Delta Chat Core versions up to 0.12.0

**Observation**:

When deleting a message with Core, the message is only marked as deleted on the server:
`\Deleted`
but is not removed from the mailbox folder.

**Expected behaviour**:
The message shall be removed from the mailbox. A subsequent EXPUNGE is missing.

In addition, when a message is deleted then the corresponding _read/return receipt_ is not marked \Deleted. It would be better to delete this as well.

**Comment by r10s** [comment]
It is now done by a CLOSE-SELECT before the next folder gets selected. CLOSE-SELECT is faster than an EXPUNGE, see https://tools.ietf.org/html/rfc3501#section-6.4.2
